The-Algorithm-Rumbling/Attack-On-Algo

자료구조/나영/BOJ_1158_요세푸스문제_java
- 큐
- 전체 시간 복잡도 : O(n * k)
- 메모리 : 294748 KB | 시간 : 556 ms
- 해당 문제는 ArrayList를 이용해 인덱스 관리를 통하여 순열을 만드는 것이 더 빠르고 효율적일 것 같습니다. 무슨 말씀이신지 알겠죠?
=> Solved: [자료구조] BOJ_요세푸스문제 김나영

자료구조/지우/BOJ_2164_카드2.cpp
- 큐
```
q.pop();          // O(1)
int num = q.front(); // O(1)
q.pop();          // O(1)
q.push(num);      // O(1)
```
- 루프를 N번 도는 동안 O(1) 연산만 수행
- ✅ 시간복잡도: O(N)
- 극단의 범위를 잘 체크해라
- 난 `N=1`의 경우일 때 생각을 못했음
- 1일 때는 애초에 while문에 못 들어간다. ➡️  answer = 1 처리 미리 해줌
=> Solved: [자료구조] BOJ_카드2 홍지우

자료구조/지우/BOJ_2346_풍선터뜨리기.cpp
- 덱
- 각 풍선을 꺼내서 처리하는 데 걸리는 시간: O(N)
- 전체 회전 횟수는 많아야 약 N번 정도 반복
➤ 결론: 전체 시간 복잡도는 O(N^2) (최악의 경우)
- 문제를 잘 읽자 - 음수일 경우 고려 안하고 문제풀이 시작함
- 뒤에서 빼서 앞으로 넣을 때는 1회 더 넣어야 모든 로직이 정상적으로 돌아간다.
- 절대값 쓰는 법: `abs(숫자)`
=> Solved: [자료구조] BOJ_풍선 터뜨리기 홍지우

자료구조/나영/BOJ_2346_풍선 터뜨리기.java
- Deque
- 배열
- for 루프 안에 while이 중첩되어 있지만, 각 풍선은 한 번만 터뜨릴 수 있고,
- visited 체크를 통해 중복 방문을 건너뛰기 때문에
- 전체적으로 이동하는 횟수는 `최대 n번`입니다.
- 즉, 실제 연산 횟수는 선형이므로 `총 시간복잡도는 O(n)`입니다.
- 1은 이미 제거되었다고 생각하고 시작하니까 n-1번 도는 거였는데 n번 돌리는 실수가 생겼다.
- 시간복잡도가 O(n^2)라고 생각했는데, 결국 a 연산은 while문 안에서 n번 실행되므로 O(n)이다.
=> Solved: [자료구조] BOJ_풍선 터뜨리기 김나영

자료구조/나영/BOJ_1935_후위 표기식2.java
- 스택
- 입력 처리: 	O(n + m)
- 후위식 계산: 	O(m)
- 전체 :	O(n + m)
- m = charn.length
- 후위 표기식을 어떻게 풀어야 하는지 알 수 있었습니다.
- second 뒤에 first가 와야 한다는 것
- 처음에 숫자 순서대로 바로 넣기만 하면 되는 줄 알고 stack.add(Double.parseDouble(br.readLine())); 이런 식으로 진행했는데, 들어갈 수 있는 값은 1개이고 AA+A+ 처럼 A가 3번 쓰일 수 있다는 것을 알고 arr 실수 배열을 생성해 값을 미리 넣어주고, 'A' - charn[i]로 각 알파벳에 알맞은 값을 넣어주며 계산했습니다.
=> Solved: [자료구조] BOJ_후위 표기식2 김나영

자료구조/지우/BOJ_1935_후위 표기식2.cpp
- 스택
- 피연산자면 → stack.push() → O(1)
- 연산자면 → stack.pop() 2번 + 연산 1번 + push 1번 → O(1)
```
반복 횟수: s.length() = O(N)
각 연산: O(1)
따라서 총 시간복잡도는 O(N)
```
- 소수점 2째자리까지 출력하는 방법
```
#include <iomanip>
cout << fixed << setprecision(2) << stack.top();
```
- 메모리 초과 이슈
- 그냥 `v['A'-'0']` 이라고 하면 터진다.
- 일단 정상적으로 v의 인덱스는 0,1,2,3,4,,,, 이렇게 해두고
- 값을 넣을 때, `v[s[i]-'A'] `<- A를 기준으로 0을 만들 수 있게 한다.
- 후위표기식,, 이렇게 푸는 거였구나..
- https://wikidocs.net/192124
=> Solved: [자료구조] BOJ_후위 표기식2 홍지우

자료구조/지우/BOJ_1966_프린터큐.cpp
- 큐, 우선순위 큐
- 큐의 전체 연산 수는 `O(N)` 
- `pq.top()`는 `O(1)`, `pq.pop()`은 `O(log N)`
- 각 테스트케이스마다 `O(N × log N)`
- pq 사용법
```
#include <queue>
priority_queue<> pq;
```
- `pair<int, int>`의 사용 - `pair.first`, `pair.second` 로 접근
```
queue<pair<int, int>> q;
```
=> Solved: [자료구조] BOJ_프린터 큐 홍지우

자료구조/지우/BOJ_1874_스택 수열.cpp
- 스택
- stack.push(i) → 최대 N번
- stack.pop() → 최대 N번 (각 숫자는 한 번만 push되고 한 번만 pop)
- cin >> num도 정확히 N번만 일어남
- ✅ 결론: 시간복잡도 O(N)
- 자바의 sb처럼 answer에 문자열 저장해서 한 번에 출력하는 유형의 문제 c++로 처음 풀어봄
- 문제를 잘 이해하고 풀면 잘 풀린다..!
=> Solved: [자료구조] BOJ_스택 수열 홍지우

자료구조/나영/BOJ_1966_프린터 큐.java
- Queue
- 한 테스트케이스 : O(N^2)
- 테스트케이스 T개 : O(T * N^2)
- 처음엔 우선순위 큐로 푸는 건가? 했는데 큐에 배열 넣어서 푸는 방법이었다,,, 오랜만에 배열을 값으로 쓰는 자료구조 문제라서 더 헷갈렸음. 헤헷!
=> Solved: [자료구조] BOJ_프린터 큐 김나영

자료구조/나영/BOJ_2504_괄호의 값.java
- stack
- O(n)
- JAVA의 제곱근 함수 기억이 안났다,,, Math.pow 기억해주기~
- 생각해보니 비트연산자로 거듭제곱 계산하면 더 빠르게 풀 수 있을 것 같다.
- 신경써야 할 게 많았던 문제,,, 머리가 팡팡
- 이것도 배열과 포인터로 풀 수 있을듯??
=> Solved: [자료구조] BOJ_괄호의 값 김나영

자료구조/지우/BOJ_2493_탑.cpp
- 스택
- 모든 요소가 push 1회 + pop 최대 1회 = 총 2N번의 연산 → O(N)
- 보자마자 배열이 생각났지만 O(N^2)이면 N이 50만이니까 제곱되면 안돼..!! 의 냄새는 맡음
- 시도1) 복사본 stack()을 활용해서 높이가 더 낮으면 복사본은 pop() 하고 레이저가 도달할 인덱스를 저장하려고 함
- 매번 스택을 순회하면서 작은 값들을 제거하므로 최악의 경우 O(N²)
- 시도2) stack에는 무조건 가능한 후보지만 저장해서 모든 수를 돌지 않게끔 수정하였다. 
- 높이가 더 낮은 곳 <- 계속 털면서 후보지 불가하게끔
- 다 털었는데 스택에 남아있어? <- 그곳이 레이저 닿을 곳
- 그리고 'i' 넣어 (후보지 등록)
- 스택의 top()과 값만 신경 써서 비교한다면 O(1)을 만들 수 있음을 유의해서 풀자!
=> Solved: [자료구조] BOJ_탑 홍지우

자료구조/지우/BOJ_22942_데이터 체커.cpp
- 스택
- O(N)
- N번 돌면서 stack pop, push, top 모두 O(1)
- 내 방식: 정렬 없이 좌표 기반 벡터로 스캔하는 방식으로 풀었음 (시간복잡도 이득)
- 풀면서 런타임에러 2번 남
- 좌표값이 음수가 될 수 있다는 사실을 인지하지 못하고 인덱스에 그냥 음수를 넣어버림
- `int num1 = x - r + 1100000;` `int num2 = x + r + 1100000;` <- 이렇게 처리함
- `stack.top()`을 하기 전에 `stack.empty()` 확인해주어야 함. 저번에도 이래서 런타임에러 났었잖아!!
=> Solved: [자료구조] BOJ_데이터 체커 홍지우

자료구조/지우/BOJ_1918_후위 표기식.cpp
- 스택
- 시간복잡도는 O(N), N은 수식 문자열의 길이.
- 각 문자에 대해 스택 연산을 최대 한 번씩만 수행.
- 알파벳, 연산자, 괄호 포함 모든 문자를 1-pass 처리함.
- 후위연산식은 '연산자'의 우선순위를 제일 먼저 출력한다는 특징이 있다.
- 우선순위(`*, / `   >   `+,-`)
- 부호 스택에 연산자, 괄호를 우선순위에 맞춰 '제일 먼저 출력되어야 하는 친구를 가장 위에 두는 형식'으로 푼다.
=> Solved: [자료구조] BOJ_후위 표기식 홍지우

자료구조/나영/BOJ_1918_후위 표기식.java
- stack
- O(n)
- 모든 요소에 대한 push와 pop이 한 번만 이루어 짐
- stack을 하나만 사용해 각 연산자들의 우선순위를 비교해서 같거나 높은 경우 전부 빼고, 낮으면 넣는 방식으로 푸는 것이 **후위 표기식** 이란 것을 알게 되었습니다
- 생각보다 간단하면서도 복잡하게 풀 수 있는 문제였습니다,,, stack 마스터의 길은 멀고도 험하다
=> Solved: [자료구조] BOJ_후위 표기식 김나영

구현/BOJ_20546_기적의 매매법.java
- 배열
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
- 문제를 잘 읽자,,, SAMESAME이 있다는 것을 잊고 있었다
- 간단한 구현 문제~ 코드가 길어지는 문제는 오랜만~(눈물이나)
=> Solved: [구현] BOJ_기적의 매매법 김나영

구현/BOJ_20546_기적의매매법.cpp
- X (단순 변수 사용)
- 단순 구현
```
14일 동안 for 루프 돌면서
준현 전략 → 항상 최대 매수
성현 전략 → 3일 연속 상승 시 매수, 3일 연속 하락 시 매도
가격 흐름을 반영해 금액과 보유 주식 수 갱신
마지막 날 가격으로 총 자산 계산 후 비교 출력
```
for 루프: 고정 14회 반복 → O(1) (상수 시간)
내부 연산은 모두 O(1)
따라서 전체 시간복잡도는: 👉 O(1)
- 3일째 뜻 = 1 2 3 채우고 다음 날..
- 난 구현 문제를 너무 복잡하게 푸는 것 같다... 단순한 느낌이 아니다..
- 뿡
=> Solved: [구현] BOJ_기적의매매법 홍지우

구현/BOJ_1244_스위치 켜고 끄기.java
- 배열
- 남학생 : n/k (k=1일 때 최대 n)  ->  O(n)
- 여학생 : 최대 대칭 확장 (최대 n/2)  ->  O(n)
- 그러므로 각 학생 m명 당 최대 시간 복잡도가 O(n)
- 최종 시간복잡도는 **O(m*n)**
- 문제를 똑바로 읽자,,, 출력 방식이 특이하다는 걸 모르고 풀어서 한 번 틀림
- 남자일 경우 while 문에서 l < n이라고 썼었는데, 난 k를 인덱스에 활용해야 하므로 -1을 무조건 해야 하니까 l <= n로 바꿨습니다.
- # 문제 잘 읽고 풀자!!!!!!!!!!!!!
=> Solved: [구현] BOJ_스위치 켜고 끄기 김나영

구현/지우/BOJ_1244_스위치켜고끄기.cpp
- 벡터(배열): 스위치 상태 저장
```
남자학생
각 학생마다 최대 O(N / num) → 최악 O(N)
전체 M명 → 최악 O(M * N)
여자학생
각 학생마다 최대 O(N) (while문 + toggle 구간 최대 N 범위까지 가능)
전체 M명 → 최악 O(M * N)
```
최종
O(M * N)
- 배열 접근 정확히 하자. -1, +1 등 어떤 인덱스에 접근하는지 세밀하게 미리 알고 들어가야 한다.
- 문제를 잘 읽자. 20개만 인출하는거 . 왜 못 읽었어?
- v[num*j] = v[num*j] == 0 ? 1 : 0; <- O면 -- X면 -- <- 값 직접 바꿀 수 있는 방법
=> Solved: [구현] BOJ_스위치켜고끄기 홍지우

구현/지우/BOJ_2753_윤년.cpp
- X(단순 변수)
- 구현
- O(1)
- 공통된 거(400배) if문으로 먼저 처리, 나머지 세부사항은 if문으로 관리하여 풀었음
=> Solved: [구현] BOJ_윤년 홍지우

구현/나영/BOJ_5597_과제 안 내신 분.java
- 배열
- O(n)
- 아무 생각 없이 바로 배열로 풀었는데, 이후 생각해보니 HashSet을 써서 풀어도 좋았을 것 같다는 생각이 들었습니다.
- 만약 학생의 수가 30명으로 명시되지 않은 상태에서 입력값만을 받아 문제를 풀어야 한다면 크기를 명시해야 하는 배열은 사용이 불가하므로 HashSet을 사용해야 합니다.
=> Solved: [구현] BOJ_과제 안 내신 분 김나영

구현/지우/BOJ_4396_지뢰 찾기.cpp
- 벡터
- 구현
```
1. map 입력: O(n²)
2. bombs 저장: O(n²) 내 조건 분기
3. result 초기화: O(n²)
4. 열기 입력 처리: O(n²)
- 열 때마다 주변 8칸 확인: O(1)
- 단, 지뢰 터지면 bombs 전체 순회: O(k), k는 지뢰 개수 ≤ n²
5. 출력: O(n²)
```
- O(n²) + O(n²) + O(n²) = O(n²)
- 문제를 잘 읽자. 테케에 의존하지 않는다.: // 지뢰가 있는 칸이 열렸다면 지뢰가 있는 모든 칸은 별표로 표시되어야 한다. <- '지뢰가 있는 모든 칸!!!!'
- cin 제외하고는 모든 변수 미리 초기화 하는 버릇을 들이자. 제 발 .
- bomb라는 리스트를 만들어 리스트를 조회하는 방법을 활용했다. 덕분에 지뢰 표시하는 걸 for(for()) 하지 않고 최적화 할 수 있었다.
=> Solved: [구현] BOJ_지뢰 찾기 홍지우

구현/나영/BOJ_4396_지뢰 찾기.java
- 배열
- 리스트
- O(n^2)
- → 전체적으로 O(n² + m) 정도인데, m은 list 크기 (지뢰 개수, 최악 O(n²))
- int to char로 하는 거 어떻게 하는 지 까먹음
- (char) (n + '0') 하면 바뀜
- 생각해보니 그냥 result 배열을 int로 두고 숫자로만 구분했어도 됐을 것 같다
- -1은 '*', -2는 '.', 그 외 숫자들은 지뢰가 아닌 열린 부분들
=> Solved: [구현] BOJ_지뢰 찾기 김나영

구현/지우/BOJ_2578_빙고.cpp
- 벡터
- set
- 구현
- 전체 흐름은 최대 25번 반복 (사회자가 25개 숫자 부름)
→ 전체 루프는 25 * (25 + 4*5) = 최대 225번 정도 수행됨 → O(1) (n이 5로 고정되어 있어서)
- set.insert!!!! 기억 안 나서 .push 로 했다가 에러 발생.. 반성.. 
- 어차피 줄을 긋는거기 때문에 상대적 경로 탐색보다는 절대적 경로로 보고 구현함
- 이렇게 절대적이게 할거면 그냥 if (check[i][0] && check[i][1] && check[i][2] && check[i][3] && check[i][4]) <- 이렇게 해도 됐겠다 싶음 크크
- 빙고가 그어졌으면 시작점을 Set에 둠 -> Set.size()는 결국 그어진 빙고줄의 개수
=> Solved: [구현] BOJ_빙고 홍지우

구현/나영/BOJ_2578_빙고.java
- 배열
- O(n^4)
```
- 숫자 찾기
-  매 입력 숫자마다 보드에서 일일이 찾아야 하므로 최악의 경우 O(N²)
- 입력 숫자 개수도 N²이므로 총 N²번 이 작업 수행
→ 전체 숫자 찾기 비용: O(N^2) * O(N^2) = O(N^4)
- 라인 검사 (8방향 × 최대 4칸 검사)
- 각 숫자 찾은 후에 최대 8방향, 각 방향으로 최대 4칸 검사
- 8과 4는 상수이므로 이 부분은 O(1)
전체 시간복잡도
숫자 찾기 작업이 가장 크므로 총 시간복잡도는 O(N^4)
```
```
if (r % 2 != 0) {
if (cnt == 4) {
ans++;
}
cnt = 0;
}
```
- 이 부분을 처음에 반복문 맨 위로 올리고 시작했는데, 그러니까 당연히 cnt가 4가 나올 리 없음,,, 이런 바보자식
- 문제를 잘 읽고 테스트 케이스 확인을 잘 하고 풀자
- 사회자가 말한 숫자의 번호가 아닌, 사회자가 몇 번째 순서로 숫자를 말했는지를 출력해야 했다.
- 뭔가 너무 코드를 단축하려다 보니 더 복잡해진 케이스가 된 것 같습니다.
=> Solved: [구현] BOJ_빙고 김나영

구현/나영/BOJ_10994_별 찍기 - 19.java
- 사용하지 않음
- 구현
- O(n^2)
- sb만을 이용해서 풀어보고 싶어서 한 줄 한 줄 넣어줬는데, 앞으로 이렇게 안 풀듯(디버깅 머리 깨지는 줄)
- 다시 보니 윗쪽/아래쪽에서 아래쪽 for문을 3부터 시작하게 했으면 둘의 코드가 동일했을 듯 합니다. 헤헷...
=> Solved: [구현] BOJ_별 찍기 19 김나영

구현/지우/BOJ_10994_별 찍기 19.cpp
- 벡터
- N 초기화 전에 map(N) <- 이런 식으로 공간 할당해서 안 돌아갔었음.. 자바와 다르다~
- 일단 선언만 해두고 cin  다음에 `map = vector<vector<char>>(4*(N-1)+1, vector<char>(4*(N-1)+1,' '));`
- char 빈공간에 `''` <- 공백 없이 채우면 에러 남.. `' '` <- 무조건 공백 넣어주기 (`vector<char>(4*(N-1)+1,' ')`)
- 구현
```
drawStar()는 재귀적으로 N개의 레벨을 그리며 각 레벨마다 약 O(N)만큼의 별을 그립니다.
전체적으로는 별을 그리는 총 작업량이 등차수열로 증가하며 O(N^2)개의 문자를 출력합니다.
출력 루프도 O(N^2)이므로 전체 시간복잡도는 **O(N^2)**입니다.
```
- N-1 값을 이용할 수 있는 경우에 재귀를 떠올린다.
- 변경되는 지점 = 겉 테두리 -> 겉 테두리에 집중하여 n번째에는 테두리만 그리고 n-1 차례로 넘기며 재귀를 구현했다.
=> Solved: [구현] BOJ_별 찍기 19 홍지우

구현/나영/BOJ_1913_달팽이.java
- 배열
- 구현
- 1시간
- O(n^2)
- map 배열을 모두 채우는 데 드는 시간
- 계속 StackOverFlow가 발생하길래 확인했더니 map[0][0]의 초기값을 세팅하지 않고 0인 상태로 findSnail() 함수에 넣어버렸다
- 함수 구조를 바꾸거나, 미리 초기값을 세팅하는 방법이 있을 듯
- **문제 잘 읽자 자꾸 이상한 데서 틀리지 말고!!!!!!!!!!**
=> Solved: [구현] BOJ_달팽이 김나영

구현/지우/BOJ_1913_달팽이.cpp
- 벡터
- 배열
- 구현
- 전체 달팽이 채우기는 N²개의 칸을 채우므로 반복 횟수는 O(N²)
- 각 이동, 방향 전환, 좌표 체크는 모두 상수 시간
- 따라서 시간복잡도 O(N²), 공간복잡도 O(N²)이다.
- 1차 시도 틀림: 1일 때의 예외처리
- input 1이 들어올 때, while문을 타지 않으므로 pos 초기값을 pair<int, int> pos = {1,1};  <-이렇게 해주는 걸로 해결
- c++에서는 N^2가 먹지 않는다
- #include <cmath> 하고,
- pow(N,2); 
- 풀이방법
- N^2부터 0,0 에서 채워나간다.
- 범위를 벗어나거나, 다음 자리(nxtR, nxtC)에 이미 채워진 수가 있으면 '방향을 바꾼다.'
=> Solved: [구현] BOJ_달팽이 홍지우

구현/나영/BOJ_17413_단어 뒤집기 2.java
- 배열
- 구현
- 27분
- O(n)
- 각 문자당 한 번씩만 접근해 sb에 append 하므로 결국 한 문자당 한 번만 접근함을 알 수 있다.
- 모든 if 문에 sb.append()가 한 번 씩은 들어가므로 전부 뺀 뒤 if 문 외부에서 한 번에 처리하도록 하고 싶었는데, 그렇게 하면 글자 중복&인덱스 오류가 발생해 OutOfMemoryError가 발생합니다
=> Solved: [구현] BOJ_단어 뒤집기 2 김나영

구현/나영/BOJ_20053_최소, 최대 2.java
- 사용하지 않음
- 구현
- O(t*n)
- 미리 설계하지 않고 풀었더니 min max 초기화를 깜빡함ㅎ 미리 계획부터 세우고 풀자,,,
=> Solved: [구현] BOJ_최소, 최대 2 김나영

구현/지우/BOJ_20053_최소, 최대 2.cpp
- x
- 구현
입력된 T개의 테스트케이스 각각에 대해 N개의 정수를 입력받고, 최소·최대값을 탐색합니다.
min, max는 상수 시간 O(1) 연산이므로, 각 테스트케이스는 O(N)
전체 시간복잡도는 **O(T × N)**입니다.
- `#include <algorithm>` -> min, max 쓰게
- `ios::sync_with_stdio(0);` <- 이거 없으면 시초 남
- 원래 같으면 정렬해서 가장 첫 값, 마지막 값 인출했을텐데 <algoritm> 써보고 싶어서 이렇게 품
=> Solved: [구현] BOJ_최소, 최대2 홍지우

구현/지우/BOJ_17413_단어 뒤집기 2.cpp
- 덱
- 구현
- 입력 문자열의 길이를 n이라 할 때, 루프는 n번 반복함.
- deque에 들어간 문자는 한 번씩만 삽입/삭제되어 총 연산은 O(n).
- 최종 시간복잡도는 O(n) 으로 효율적인 구현이다.
- 뒤에 idx++ 되는 프로세스 까먹고 
```
else if(s[idx] == '>') { 
dq.push_back(s[idx]);
popDq();
}
```
이 코드로 > 처리하려고 하니 < 에서 이미 도달한 > 상태에서 idx가 하나 더 뒤로 가면서 > 처리가 안됐었다. 
- `<` 처리할 때 `>` 까지 모두 처리해주는 로직으로 변경하여 해결했다.
=> Solved: [구현] BOJ_단어 뒤집기 2 홍지우

구현/지우/BOJ_1212_8진수 2진수.cpp
- 배열
- 구현
가장 오래 걸리는 for문 - tmp.length()는 최대 3 * N
최종: O(N)
- 처음에 8진수->10진수->2진수로 풀고 호되게 당함
-  왜? int는 최대 10자리만 가능이니까.
- 0 은 000 아니고 0 출력해야 함.. ㅋㅋ
- 진수진수진수 진상진상진상
=> Solved: [구현] BOJ_8진수 2진수 홍지우

구현/나영/BOJ_20291_파일 정리.java
- TreeMap
- 구현
- split → 한 줄당 O(1)
- TreeMap 삽입 put() + getOrDefault() : 	O(log k)
- k는 현재 TreeMap에 담긴 키 수
- keySet 순회
- for (String key : keySet) : O(k)
- map.get(key)	TreeMap에서 값 꺼내기 : O(log k)
- 총 시간복잡도는 O(n * log k) + O(k * log k)
- 평균 : O(n * log k)
- 최악 : O(n * log n)
- split 안 쓰고 substring 쓸라함,, 헤헷!
- getOrDefault 오랜만에 사용해 봄
- 해당 문제는 정렬해야 하므로 HashMap이 아닌 TreeMap을 사용했다
- map의 key와 value를 순서대로 꺼내기 위해 keySet을 통하여 map의 key Set을 꺼냈다
=> Solved: [구현] BOJ_파일 정리 김나영

구현/지우/BOJ_20291_파일 정리.cpp
- map
- 구현
- 문자열 처리: O(T × L) (L은 평균 문자열 길이)
- map 처리: O(T log T)
- mp.count(extension) → O(log M)
- mp[extension]++ or mp.insert(...) → O(log M)
- 출력: O(T)
- 총 시간복잡도: 🔹 O(T × L + T log T)
- c++은 split 함수가 없다..
- mp[extension] 하면 그냥 value 값 나오는거! .second 붙이면 안되잉~~
- C++에서 map, set은 그 자체로 treeMap, treeSet
=> Solved: [구현] BOJ_파일 정리 홍지우

구현/나영/BOJ_15787_기차가 어둠을 헤치고 은하수를.java
- 배열
- 구현
- 재귀
- 명령 처리 시간 : O(m * 0) = O(m)
- milkyWay 함수 처리 시간
- 최대 t-1개 열차와 비교
- 열차당 좌석 20개 비교 → O(20)
- 총 시간복잡도 : O(n^2)
- isS 초기화 잘 해주기,, 이것땜에 디버깅했다
- 근데 시간복잡도 터질 각인데 왜 안터졌지? 헤헷
- 왜냐면 열차 자리 비교할 때 하나라도 다르면 바로 break했기 때문. 사실상 시간복잡도가 O(n)에 가까워짐. 가지치기 중요!
=> Solved: [구현] BOJ_기차가 어둠을 헤치고 은하수를 김나영

구현/지우/BOJ_12933_오리.cpp
- 배열
- 구현
while 루프는 remain이 0이 될 때까지 반복 → 최대 s.length() / 5번 = O(N)
내부 **while(idx < s.length())**에서 문자열 전체 탐색 → 매 루프마다 O(N)
전체 시간복잡도는 O(N²) (최악의 경우: quackquackquack...처럼 연속된 울음소리일 때)
- 다 돈 순서는 readySet에 넣어두고 거기 size()가 0 이면 cnt 추가, 아니면 ++ 하는 걸로 하려 했지만 변수가 꼬이고 재귀 상태를 관리하지 못하면서 다시 품..
- 소거법으로 품
- 큰 while문에서는 유의미한 단어의 수가 0이 될 때까지 돌린다.
- 작은 while문은 진격의 거인이다. idx++만 해가면서 quack을 계속 완성한다. <- 한 while문이 돌면 한 오리가 외칠만한건 다 null(\0)로 바뀌어져 있고 이 오리 개수 cnt ++ 해두면 된다.
=> Solved: [구현] BOJ_오리 홍지우

구현/지우/BOJ_2615_오목.cpp
- 배열
- 구현
main()에서 모든 칸에 대해 검사 → O(19 × 19) = O(1) (상수 크기)
각 칸마다 최대 4방향 검사, 각 방향에서 최대 5칸까지 탐색 → O(4 × 5) = O(1)
전체 시간복잡도는 O(1) — 입력 크기가 작고 고정되어 있어 완전탐색이어도 매우 빠름
- 처음에 가능한 일렬줄로 보려고 했었음(6개 이상이면 안되니까 그냥 열, 행, 대각선으로 잘라놓고 딱 5개인 것만 고르게)
- 문제는 시작점을 관리하는게 힘들었고, 로직이 꼬였음. (for문 6개.. 헤헷)
- 문제에서 중요한 조건: 가장 왼쪽에 있는 바둑알을 출력해야 함 - 이 때문에 왼->오 순서로 돌리면 (가로, 세로, 오른쪽 '위', 오른쪽 아래) 이렇게 돌림. 그럼 무조건 r,c는 가장 왼쪽 바둑알임.
- while문으로 돌리면서 현재 방향으로부터 색이 같은 바둑알 cnt를 모두! 해주고 딱 5개 돌이 모이면 return 해줘야 함
- 여기서 주의: 이전의 것을 간과하면 안됨 (지금부터 5개였는데 지나쳐온 것 포함하면 6일 수 있음) -> pass 된거 방향 거꾸로 한번 타서 바둑 색 체크해줌
- main 문 안에서 `return 0;` 하면 바로 정상 '종 료' 꿀팁@
=> Solved: [구현] BOJ_오목 홍지우

구현/지우/BOJ_17276_배열 돌리기.cpp
- 벡터
- 구현
각 회전 연산 (doClock 또는 revClock)의 시간복잡도는 O(N) — 주대각선/부대각선과 중앙 행/열만 순회.
회전 연산은 abs(d)/45만큼 반복되므로 전체 회전 연산 복잡도는 O((d/45) * N).
입력 및 출력은 O(N²), 따라서 전체 시간복잡도는 **O(T × (N² + (d/45) × N))**입니다.
진짜.. 힘들었다.
- tc가 반복되는 문제다
- `arr.clear(); tmp.clear();` //arr, tmp <- 이거 clear 안해줬더니 런타임에러 남.. 영원히..
- .resize도 습관화 해야 한다.
- 모든 축을 다 돌리는 것을 tmp 만들어 직접 다 지정해줬다.. (다음부터는 그냥 dr[] dc[] 만들어서 할게욤..)
=> Solved: [구현] 배열 돌리기 홍지우

구현/나영/BOJ_20207_달력.java
- 배열
- 구현
- 그리디
- O(n * 365) = O(n)
- 떠오르지 않으면 풀 수 없는 문제,,, 문제를 더 많이 풀어야겠다는 생각이 들었다
- 첨엔 visited boolean 배열로 방문했는지 체크하면서 풀려고 했는데, 구현이 불가능할 것 같아서 각 일정 당 높이를 계산하며 풀었다
=> Solved: [구현] BOJ_달력 김나영

구현/지우/BOJ_14719_빗물.cpp
- 벡터
- 구현
- 바깥 반복문은 H (높이)만큼, 안쪽 반복문은 W (너비)만큼 순회합니다.
- 각 칸에 대해 고정된 연산을 하므로 전체 시간복잡도는 O(H × W)
- 공간복잡도는 벽 정보 저장용 O(W)
- 예외 처리를 잘 생각해야 하는데 문제 들어갈 때 너무 생각이 없었다..
- 1차 시도: (예외) 가장 높은 것을 기준으로 할 때 중간에 생기는 벽은 확인하지 못했다.
- 풀이방법: 벽 하나를 잡고 기준벽보다 같거나 크면 다른 벽이 생기고, 그 안에 물이 쌓이는 것으로 계산
- 틀림: 5 2 0 2 면 2와 2 사이에 물이 쌓이는 건 계산하지 못함
- SOL: 위에서부터 높이 한 층씩 본다. 이때의 벽과 벽 사이의 공간을 센다(tmp++)
- 처음에 벽이 없을 수도 있다. cnt(벽)이 0일 때는 tmp가 안 쌓게 예외 처리를 추가로 했다.
=> Solved: [구현] BOJ_빗물 홍지우

구현/나영/BOJ_14719_빗물.java
- 배열
- 구현
- i가 w까지 조회 : O(w)
- j가 maxIndex까지 조회 : O(w)
- while에서 j-- 하므로 j는 한 번씩만 감소시키며 조회됨 : O(1)
- 최종 시간복잡도 : O(w^2)
- 0부터 w-1까지 높이를 조회하다 현재 높이가 이전 높이보다 높으면 빗물을 담을 수 있는 순간이 생김
- 이 때 만약 이전 값 중에 가장 높은 값(max)이 이전 높이보다 낮다면 물을 담을 수 없으므로 pass
- 그리고 i부터 maxIndex(가장 높은 위치의 인덱스) 까지 돌며 이전 높이보다 높은 값이 있는지 역방향 탐색
- 이 때 j > maxIndex를 해 줘야 ArrayIndexOutOfBounds 문제가 생기지 않음
- 그리고 if (rain[i] < rain[j]) break; 하지 않으면 rain[j] < rain[sample] 인 경우가 들어갈 수 있어 조건 추가해야 함
- maxIndex까지 왔거나 rain[i]보다 높은 곳에 온 경우 빗물 계산해주고 break;
- 어떻게든 h를 쓰지 않겠다는 **의지**
- 근데 h 쓰는 게 맞는 듯 헤헷
=> Solved: [구현] BOJ_빗물 김나영

구현/나영/BOJ_20164_홀수 홀릭 호석.java
- 배열
- 구현
- 재귀
- 한 단계에서 자리수 k에 대해 O(k²) 가지로 세 구간 분리해 분기.
- 자리수는 합하면서 줄어들어 단계 수는 O(log n).
- 전체 시간복잡도 = O(k² × log n).
- 재귀~ 너란 놈 왜 이렇게 익숙해지지 않는 거니~
- 설계 개판으로 하고 푼 결과
- 러시아 국기랑 똑같다고 생각하고 풀었는데, 계속 더해야 할 숫자가 바뀌므로 재귀로 풀었다
- 근데 이제 뎁스 지정이 헷갈렸던,,, for문을 재귀로 바꾸는 능력이 부족한 듯
- 그리고 처음부터 한 자리 숫자가 나오면 재귀 로직에선 sum이 한 번 더 플러스됨. 주의.
- 앞으로 절대 쓰면서 코딩하겠습니다.
=> Solved: [구현] BOJ_홀수 홀릭 호석 김나영

구현/나영/BOJ_5766_할아버지는 유명해!.java
- 배열
- 구현
- O(t * n * k)
- 헤헷,,, 예외케이스 개걸림ㅁㅊ 집중집중~~!!!
- 변수 first는 1등의 인덱스, second는 2등의 값을 받아줬는데, 걍 TreeSet에 넣고 두 번째 값 뺄까 싶기도 했음
=> Solved: [구현] BOJ_할아버지는 유명해! 김나영

구현/나영/BOJ_15886_내 선물을 받아줘 2.java
- 배열
- 구현
- O(n)
- E와 W가 만나는 지점이 무한 루프 도는 지점 => 이 자리에 선물을 놓으면 됨
- 그리고 문제에서 **구사과가 길을 나가는 케이스는 없다** 라고 했으므로 따로 예외 처리는 안 해도 된다.
=> Solved: [구현] BOJ_내 선물을 받아줘 2 김나영

구현/지우/BOJ_15886_내 선물을 받아줘 2.cpp
- 벡터
- 구현
- 바깥쪽 루프는 i = 0 ~ N-1까지 총 N번 반복
- 내부에서 최대 O(N)번의 이동(while 루프)과 O(N)번의 visited/p 배열 갱신이 발생
- 최악의 경우 O(N²) 시간복잡도
- 풀이법
- 모든 시작점을 시도해본다.
- p[] 에서는 이 배열을 돌 때 어떤 선물이 필요한지 표시한다.
- p[1, 1, 1, 2, 2] (그럼 총 2개의 선물 필요)
- E 는 +1, W -1하면서 이동하며 방문
- 이때, 이미 방문한 곳이면 -> `break;`
- 아니면 지금까지 돈 곳 중 선물 번호가 가장 높은 걸 저장
- 돈 곳 중 선물 놓인 곳이 하나도 없어(0이야) -> 선물 개수++
=> Solved: [구현] BOJ_내 선물을 받아줘 2 홍지우

그래프 탐색/나영/BOJ_1260_DFS와 BFS.java
- List
- 배열
- Queue
- 그래프 탐색
- DFS
- BFS
- 간선 입력 : O(n)
- 자식 간선 정렬 : O(n log n)
- DFS, BFS : O(n + m)
- n개의 숫자를 접촉
- 간선을 m번 탐색함
- 저번에도 List를 이용해 푼 문제인데, 다른 방식으로 풀어 보고 싶다
- List로 푸는 경우엔 sort 필수
- Map과 행렬로도 풀 수 있다고 한다
=> Solved: [그래프 탐색] BOJ_DFS와 BFS 김나영

구현/나영/BOJ_17128_소가 정보섬에 올라온 이유.java
- 배열
- 구현
- 누적합
- 입력 및 초기 계산: O(n)
- 쿼리 처리: O(q)
- 총 시간복잡도 : O(n + q)
- 개귀찮은 문제 ㅁㅊ
- 값 비교 고민하다 결국 %를 이용했다... 머리 아픔
=> Solved: [구현] BOJ_17128_소가 정보섬에 올라온 이유 김나영

그래프 탐색/나영/BOJ_11725_트리의 부모 찾기.java
- Queue 
- List 
- 배열 
- 그래프 탐색 
- BFS 
- List 생성, 간선 삽입 시간 : O(n) 
- BFS : O(n) 
- 각 노드를 한 번씩만 탐색
- bfs로 풀어보고 싶어서 풀었다 
- ArrayList 배열을 선언할 수 있지만 
```
Note: Main.java uses unchecked or unsafe operations. 
Note: Recompile with -Xlint:unchecked for details. 
// “Main.java에서 타입 체크가 완전하지 않거나 안전하지 않은 연산을 사용하고 있다.” 는 의미 
// 일반적으로 Generic 사용 시 타입 경고가 발생할 때 뜬다. 
```
- 오류 발생 
- new List<Integer>[n] 처럼 Generic 타입 배열 생성 자체를 허용하지 않음. 
- 하지만 new ArrayList[n + 1] 으로 우회 생성하여 List<Integer>[] 에 할당할 때 타입 안정성이 완전히 보장되지 않아 경고를 띄움.
=> Solved: [그래프 탐색] BOJ_트리의 부모 찾기 김나영

그래프 탐색/나영/BOJ_14940_쉬운 최단거리.java
- Queue
- 배열
- 그래프 탐색
- BFS
- BFS로 모든 요소를 1번씩만 방문 : O(n + m)
- BFS 기본 문제 인데 -1 체크를 제대로 안 함ㅎ 문제 잘 읽기 챌린지 2일차
- map의 값이 0이면 0, ans 배열에 접근하지 않아 값이 0이면 -1, 그 외에는 ans 배열 값을 출력시켰다.
- BFS에서 map이 0일 때 체크는 안 해도 될 듯
=> Solved: [그래프 탐색] BOJ_쉬운 최단거리 김나영

구현/나영/BOJ_22856_트리 순회.java
- 배열
- 구현
- 그래프 탐색
- DFS
- O(n)
- 노드 수에 비례하여 탐색
- **각 간선은 정확히 한 번씩만 탐색**
- dfs() 내부 for 루프는 상수 2회 반복 = O(1)
- 처음엔 그냥 끝까지 갔다가 마지막 노드 방문하면 끝 아닌가? 라고 생각했는데, **중위 순회** 방식이라는 것을 유의하면서 풀어야 했음 (인간적으로 테스트 케이스 추가해주라)
- 그래서 내 부모 노드와, 그 위의 조상 노드가 현재 왼쪽을 탐색 중인지 오른쪽을 탐색 중인지 각각 i, k로 값을 넘기면서 확인하고 마지막 노드까지 탐색한다면 해당 값들을 기반으로 중위 순회를 이어가야 할 지 멈춰야 할 지를 판단
=> Solved: [구현] BOJ_트리 순회 김나영

구현/나영/BOJ_22859_HTML 파싱.java
- String
- 배열
- 구현
- div 태그를 나눠 반복문 실행 - O(t)
- p 태그를 나눠 반복문 실행해 find()에 넣음 - O(p)
- find 내부에서 문자열 순회 - O(l)
- 최종 시간 복잡도 : O(t * p * l)
- 하지만 이론적으로 문자열 s의 길이까지만 탐색하므로 O(s)라고 볼 수 있다.
- 따봉 split아 고마워
- substring으로 title의 문자열, 그리고 p태그 내부의 문자열을 쏘옥 빼 주었습니다.
- 중간의 공백은 sb의 마지막 문자를 확인하면서 중복 공백이 생기지 않게 관리했습니다.
- 마지막에 공백 문자가 들어올 수도 있으므로 sb.deleteCharAt(sb.length()-1)로 공백 제거했습니다.
=> Solved: [구현] BOJ_HTML 파싱 김나영

구현/지우/BOJ_22860_폴더 정리 (small).cpp
- map
- queue
- vector
- pair
- 구현
- N + M개의 폴더 및 파일 정보를 map<string, vector<pair<int, string>>>에 저장하는 데 O(N + M)
- 각 쿼리마다 BFS는 해당 경로 아래의 모든 하위 폴더 및 파일을 한 번씩 순회 → 최악의 경우 O(N + M)
- 따라서 전체 시간복잡도는 O(C × (N + M)), C는 쿼리 개수입니다.
- 안녕 Map .. 오랜만이야.. <키, value> 친구야..
- map<string, vector<pair<int, string>>> 해줌
- map[main] = { [1, 폴A] , [1, 폴B] } <- 이런 식으로 넣어줌
- 큐에 폴더를 넣고 돌림, 이때 중복된 cnt 가능한 친구와 불가능한 친구를 나누었음 (종류cnt, 개수cnt)
- vis[파일이름] = false 일 때만 종류cnt++;
- 이때, vis도 맵으로 처리해줌. map<string, bool>
=> Solved: [구현] BOJ_폴더 정리 (small) 홍지우

그래프 탐색/지우/BOJ_16918_봄버맨.cpp
- 벡터
- 그래프탐색이라고 쓰고 구현이라고 읽는다.
1. 각 `letsbomb()` 실행은 격자 전체(R×C)를 한 번씩 순회하므로 **O(R × C)**
2. `letsbomb()`는 최대 N번 중에서 \*\*홀수 초(1초 제외)\*\*에만 실행되므로 최대 약 N/2번 반복됨
3. 따라서 전체 시간복잡도는 \*\*O(N × R × C)\*\*이며, 최악의 경우 **O(200 × 200 × 200) = 8,000,000**
- 영(0)이 아니라 오(O) 다 헤헷
- || 써야 하는데 && 쓰고, C대신 R 써서 돌리는 바람에 디버깅해야 했다 (진짜 . 한 번 할 때 좀 꼼꼼히 제발.)
- 풀이방법
- 0으로 제외하고 `홀수번째`는 일부 폭탄이, `짝수번째`는 전체 폭탄이 보인다는 규칙을 찾았다.
- N이라는 시간에 도달할 때까지 **_홀수 초가 등장하면 일부 폭탄을 터트린다._**
- 정방향 순회하며 . 이면 O로 바꾼다 (나머지 공간에 폭탄 설치)
- 근데 visited 된 . (즉, 폭탄이 터져서 . 된 친구) 는 바꾸면 안된다. 
- O을 마주하면 본인 포함 4방향으로 터트린다.
- 본인과 4방향 Vis=true 해주면서 터트리기
- 여기서 잠깐!!!! 다른 폭탄이 4방향 중에 있다? <- 요놈은 살려둬. (어차피 터진다. 그리고 얘가 자기 주변도 터트려야 한다.)
=> Solved: [그래프 탐색] BOJ_봄버맨 홍지우

그래프 탐색/나영/BOJ_16918_봄버맨.java
- 배열
- 구현
- 그래프 탐색
- DFS
- 입력 : O(R * C)
- DFS 탐색 : O(n)
- 폭발 시 폭탄 처리 : O(4 * R * C)
- 최종 시간복잡도 : **O(n * R * C)**
- 이건 그래프 탐색이 아니라 구현 아닌가요
- 케이스 별로 다 나눠서 폭탄을 설치할지 말지 결정해야 해서 머리 빠지는 줄 알았음
- 무조건 1초부터 시작하므로, 처음 폭탄의 위치를 받을 때 int 2차원 배열에 설치된 폭탄 위치에 1을 넣어준다.
- 그리고 dfs(1) 로 시작해 n == 1일 때, cnt가 2이거나 cnt - 3이 홀수일 때 (생각해보니 이 부분 걍 cnt가 짝수일 때로 넣으면 될 듯), 그 외의 케이스를 나누어 폭탄의 지나간 시간과 추가로 놓을지 말지 체크했다.
- 귀찮은 문제,,, 컄!
=> Solved: [그래프 탐색] BOJ_봄버맨 김나영

그래프 탐색/나영/BOJ_2667_단지번호붙이기.java
- Queue
- 배열
- 그래프 탐색
- BFS
- 입력 : O(n ^ 2)
- bfs() : O(n ^ 2)
- Collections.sort(list) : (log n^2) =2(log n)
- 최종 시간복잡도 : O(n ^2 * log n)
- list sorting 안해줘서 한 번 틀림 헤헷
- 무난무난 BFS BFS~~~
=> Solved: [그래프 탐색] BOJ_단지번호붙이기 김나영

그래프 탐색/나영/BOJ_13549_숨바꼭질 3.java
- Queue
- 배열
- 그래프 탐색
- BFS
- DP
- O(k)
- k번까지 BFS가 돌아가므로 최대 시간복잡도는 O(k)
- 배열의 크기 조정이 약간 고민이었던,,
- 2*n 을 먼저 돌려서 가장 빨리 도착하는 경우를 세어 준다
- 그리고 check() 함수에서 dp[b]가 -1이 아닌 경우, 즉 이미 해당 위치를 방문한 경우 que에 넣지 않는다
- 그리고 돌려돌려~~~
- 그럼 짜잔~ 최소 거리가 나옴
=> Solved: [그래프 탐색] BOJ_숨바꼭질 3 김나영

그래프 탐색/지우/BOJ_17836_공주님을 구해라!.cpp
- 큐
- 벡터
- 그래프탐색(BFS)
BFS로 최대 N × M개의 칸을 탐색하므로
- 탐색 복잡도: O(N × M)
각 칸에서 상하좌우(4방향) 이동을 시도하므로
- 이웃 탐색 복잡도: O(4 × N × M) → O(N × M)
최종 시간복잡도는
👉 O(N × M)
- 그람을 얻고, 안 얻는 경로가 BFS 내에서 서로 '다르다' 는 교훈을 위한 문제
- (지난번 time+0 , time+1 을 분리해서 생각해야 했던 문제와 동일하다)
- 그람을 얻은 순간부터는 같은 vis를 쓸 수도 없다 - 완전히 다른 경로가 되기 때문이다.
- vis로 구분할 경우, 3차원 배열을 사용해서 vis[r][c][검 찾 유무] 사용해야 한다.
- 풀이법
-  평소처럼 가다가 그람을 마주한 순간!
- 그람이 있는 자리에서 총 거리를 바로 구할 수 있다. (현재까지의 거리 + 목표-r + 목표-c)
- ans에 넣어준다. (항상 검이 있는 자리가 더 빠르진 않다. 여기서 바로 ans를 구하면 안됨)
- 그러고 검이 없는 것처럼 BFS는 계속 돈다.
- 목표지점에 도달했을 때, 검O 거리와 검X 거리 중 더 작은 거리를 ans로 삼는다.
=> Solved: [그래프 탐색] BOJ_공주님을 구해라! 홍지우

그래프 탐색/지우/BOJ_13023_ABCDE.cpp
- 벡터(리스트용)
- 그래프탐색(dfs)
- 정점 수 N개에 대해 각 정점에서 DFS 수행 → O(N)
- DFS는 최대 깊이 5까지, 각 깊이마다 인접 리스트 탐색 → O(5 × 평균 차수)
- 전체 시간복잡도는 최악의 경우 O(N × 4⁴) ≈ O(N) 수준 (탐색 깊이 고정)
- cnt가 5가 되는 순간! 콜스택이 모두 True가 되면서 최종적으로 1을 출력하게끔 설계했다.
- 인접리스트 돌면서 nxt 노드 세계관 방문 열고 dfs 탐색 쭉 나아가게 하고. 방문 닫아서 다른 세계관도 열릴 수 있게 처리했다.
=> Solved: [그래프 탐색] BOJ_ABCDE 홍지우

그래프 탐색/나영/BOJ_7576_토마토.java
- Queue
- 배열
- 그래프 탐색
- BFS
- 입력 : O(n * m)
- BFS  : O(n * m * 4) = O(n * m)
- 최종 시간복잡도 : O(n * m)
- que의 size를 이용해서 하루가 언제 지나갔는지를 체크하는 문제
- 마지막 날에 익은 톰뭬이러가 que에 들어가므로, days에 -1을 해야 한다.
- 헤헤 설탕 뿌린 토마토 먹고싶슴다
=> Solved: [그래프 탐색] BOJ_토마토 김나영

그래프 탐색/나영/BOJ_2668_숫자고르기.java
- 배열
- 그래프 탐색
- DFS
- DFS : 한 i에 대해 depth n까지 들어갈 수 있음 -> O(n ^ 2)
- 조합 문제 아님? 했는데 n이 100이라 무줙건 터짐,, 이런 제 기 랄
- 그래서 자식을 타고 가야 한다고 생각하고 풀었다 -> 도착한 자식이 맨 처음 dfs에 들어간 값과 같을 때 해당 사이클은 선택 가능
- cnt == i
- dfs에서 나온 뒤 cnt == i 라면 set에 넣어 주고 finish[i] = true 처리해 이미 방문한 곳은 넘어가게 하려고 했,,는데 생각해보니 그러면 이 배열을 dfs에서 방문처리 시켜줬어야 했음ㅋㅋ 이거 빼고 해도 똑같음 바보자식;
=> Solved: [그래프 탐색] BOJ_숫자고르기 김나영

그래프 탐색/지우/BOJ_7569_토마토.cpp
- 벡터 
- 큐
- 그래프탐색(BFS)
1. 모든 칸을 한 번씩 방문 → O(H × R × C)
2. 각 칸마다 6방향 탐색 → 최대 6 * O(H × R × C)
3. 전체 시간복잡도는 **O(H × R × C)**
- 3차원 배열이지만 이전 문제랑 풀이는 똑같다.
- `maps.resize(R, vector<vector<int>>(C, vector<int>(H,0)));` 이런거 처음 써봤어용
- 가로 칸의 수 = C, 세로 칸의 수 = R  <- 이거 문제 읽을 때 헷갈리지 말좌!!!!
=> Solved: [그래프 탐색] BOJ_토마토2 홍지우

그래프 탐색/지우/BOJ_2573_빙산.cpp
- 그래프탐색(BFS)
check()는 매년 최대 N*M → 최악의 경우 O(NM)
melting() 역시 매년 O(NM) → 각 빙산 녹이기 위해 4방향 탐색
전체는 최대 year * N * M, year는 빙산 높이에 비례하지만 10^3 이하 수준이므로 충분히 통과
- 드디어 '학습'이라는게 돼서 문제 보자마자 떠오른 DFS는 집에 보내버림. 너로 풀면 시간 백퍼 오래 걸리겠지?
- 근데 BFS로 풀어도 어차피 N*M으로 다 방문하므로 DFS의 경우에도 결국 N*M*Year 이라는건 똑같았다 - 헤헤헤ㅔ (이건 또 되는 문제네 진짜 혼란하다 혼란해)
- 여기서 핵심 : 녹는 빙산 반영을 '한 번에' 해줘야 한다. 녹이면서 내려가면 다른 빙산에 영향을 줄 수 있다. Year 단위로 자를 것!
- 풀이
1. input 들어오면서 0보다 큰 빙산들은  q에 넣는다. 그 후 bfs로 넘기기
2. bfs에서는 
- 1)너 2동강 이상 나니? check()  | 2)남은 빙산이 하나도 없니? (q에 든 것들이 0) 를 먼저 체크한다.
- 이번 년도 남은 빙산(doneIce) = q.size(); 로 지정해주고 이 빙산들을 다 처리할 때까지 while문 돌린다.
- 주변 4방 탐색하며 0이 있으면 빙하가 녹아야 한다. 빼야 하는 애들을 dp[그자리]-- 해줬다. 바로 반영하면 영향을 미치니까 안된다.
- 빙산 다 처리하면 'YEAR++' 한 해가 다 흘렀다.
3. melting(); <- dp에 저장된 수를 활용해 빙하를 녹인다.
4. 이후 다시 bfs를 돌린다. 반영된 빙하가 들어가있을 …
=> Solved: [그래프 탐색] BOJ_빙산 홍지우

그래프 탐색/나영/BOJ_18513_샘터.java
- Queue
- 배열
- 그래프 탐색
- BFS
- O(k) : 최대 k개의 새로운 수를 찾으므로 최대 시간복잡도는 O(k)이다.
- 지우의 도움으로 인해 풀 수 있었다. 이 문제의 핵심은 **long** 이었다
- 집터의 범위는 정해지지 않았으므로 int의 범위를 벗어날 수 있다
- 이 부분만 신경 쓰면 양쪽으로 넓어지는 BFS 문제로, 모든 집터가 다 세워지면 멈추면 됩니다.
- 생각해보니  while(k > 0)으로만 조건 했어도 됐을 듯
=> Solved: [그래프 탐색] BOJ_샘터 김나영

그래프 탐색/지우/BOJ_14502_연구소.cpp
- 그래프탐색(DFS, BFS)
- DFS 벽 세우기: 최대 (N × M)C3 = O((N × M)³) // 조합 `64 C 3`
- BFS 바이러스 퍼뜨리기: 한 번당 O(N × M)
- 총 시간복잡도: O((N × M)³ × (N × M)) = O((N × M)⁴)
- 하.. 아직 난 멀었다.. 깔끔하게 한 번에 똑! 하고 풀고싶다 졍말..
- 2차원 배열에서 i가 N*M까지 돌면, r과 c를 특정할 수 있다. 마치 input 받을 때를 생각하면 된다. 
- `r = i/M`; `c = i&M`;
- q는 깊은 복사가 안된다. 
- viruses(map에서 2)를 리스트로 저장해서, 추가된 벽 개수가 3개가 될 때 check() 함수-> Viruses 들을 q로 옮겨줬다.
- 안전지대 구한 방법: 
- 처음 input 들어올 때 0인 구역(안전지대 구역) 저장한다. - totalSafe
- 여기서 벽 3개가 추가되니 -3
- infected 수에 바이러스들(2인지점)도 포함이 되니 그 부분은 뺄 필요 없으니 더함 (+viruses.size()) 그리고 q에서 나온 모든 감염지점들 빼주기(-infected);
- 조합 64C3
- 현재 위치(Idx) 기준으로 내가 갈 곳 `for(int i=idx; i<N*M; i++) {`으로 나아가게 되면 64 중 3개만 선택하는 시간복잡도를 가질 수 있다. 
- `maps[r][c] =1; dfs(wallCnt+1, i+1);` <- `i=idx `이번 차례에 벽 세운 경우
- maps[r][c] = 0; <- 원래 상태로 복귀 (그럼 …
=> Solved: [그래프 탐색] BOJ_연구소 홍지우

백트래킹/지우/BOJ_N과 M (1).cpp
- 벡터
- 백트래킹
- 순열
- 한 자리마다 최대 N개의 숫자 선택 → 깊이 M까지 탐색
- 즉, 시간복잡도는 O(N × (N−1) × ... × (N−M+1)) = O(NPm) (순열)
- 최악의 경우 O(N!) (N=M일 때) → N ≤ 8이면 완전탐색 가능
- 3 자리 티오 -> N * N-1 * N-2 : 이런 식으로 진행되는 문제
- dfs() 들어오면 1~N까지 돌리면서 선택한 경우(vis=true, ans에 넣어주기) 그리고 선택 다시 풀기 진행하면서 다음 dfs()로 넘어간다. vis 안된 애들 주워서 넣기. -> 이렇게 모은 ans가 총 M개 모이면 출력
=> Solved: [백트래킹] BOJ_N과 M (1) 홍지우

그래프 탐색/지우/BOJ_말이 되고픈 원숭이.cpp
- 그래프탐색(BFS)
- BFS 탐색에서 상태는 (행, 열, 말 이동 횟수)로 표현되므로 총 상태 수는 R * C * (K+1)개입니다.
- 각 상태에서 최대 12개의 이동(일반 4방향 + 말 이동 8방향)을 고려하므로, 전체 연산은 O(R * C * K)입니다.
- 즉, **시간복잡도는 O(R * C * K)**이며, 최악의 경우 약 200 * 200 * 30 = 1,200,000으로 충분히 통과 가능한 수준입니다.
- 공주님을 구해라! 처럼 BFS를 돌다가 `**다른 칸으로 갈 수 있는 옵션이 여러 개**`인 문제
- dp[r][c][horse] : r,c 지점에 말 이동법을 horse번 사용해서 왔다! 는 뜻
- k번만큼의 차원을 달리 둬서 품
=> Solved: [그래프 탐색] BOJ_말이 되고픈 원숭이 홍지우

그래프 탐색/나영/BOJ_2206_벽 부수고 이동하기.java
- Queue
- 배열
- 그래프 탐색
- BFS
- BFS : 모든 칸을 최대 두 번 씩만 탐색 => **O(n * m)
- 말되원의 마일드한 버전
- visited 3차원 배열로 1이면 벽을 부술지 말지 체크하고, 0이면 벽 부수기 여부를 wall로 갖고 다니며 방문 체크한다
=> Solved: [그래프 탐색] BOJ_벽 부수고 이동하기 김나영

백트래킹/지우/BOJ_15655_N과 M (6).cpp
- 벡터
- 백트래킹(조합)
- dfs(i+1, sIdx+1)로 호출되며 깊이 M까지 탐색 → 최대 재귀 깊이 M
- 각 깊이에서 선택지는 이전보다 하나 줄어듦 → 총 경우의 수는 O(NCM)
- 각 조합마다 길이 M인 결과 출력 → 총 시간복잡도는 O(NCM × M)
- 즉, 조합(Combination) 문제이며, 시간복잡도는 O(NCM × M) 정도입니다.
- 다음 picks에 올 애를 찾을 때 현재+1 부터 N까지 찾는다
=> Solved: [백트래킹] BOJ_N과 M (6) 홍지우

백트래킹/나영/BOJ_6443_애너그램.java
- 배열
- 백트래킹
- 순열
- Array 정렬 : O(m log m)
- dfs : 순열을 탐색. 최악의 경우 O(m!) -> cnt == perm.length일 경우 sb에 대입하므로 최종 O(m * m!)
- 위를 n번 반복
- 최종 시간복잡도 : **O(n * (m long m + m * m!))**
- 순열을 추출하되, 동일한 순열이 또 출력되어선 안 된다
- pre를 이용해 해당 인덱스에서의 이전 값을 저장하고 현재 값과 비교해 동일하면 continue 시켰다
=> Solved: [백트래킹] BOJ_애너그램 김나영

그래프 탐색/지우/BOJ_18352_특정 거리의 도시 찾기.cpp
- Queue, Vector, Set
- 그래프탐색
- 그래프는 정점 수 N, 간선 수 M → BFS 한 번으로 모든 정점 방문하므로 O(N + M).
- 각 정점마다 최대 한 번만 큐에 들어가고, 인접리스트 탐색으로 간선 순회 → 총 O(N + M).
- 출력은 최종적으로 최대 N개의 정점 출력 → O(N).
- 특정 최단 길이에 도달하는 여러 노드를 인출하는 문제
- dp에 거리를 담아서 dp값이 K가 나온 수를 set에 담아 인출했다. (ordered_set이라서 자동으로 사전순 정렬)
=> Solved: [그래프 탐색] BOJ_특정 거리의 도시 찾기 홍지우

그래프 탐색/나영/BOJ_16954_움직이는 미로 탈출.java
- Queue
- 배열
- 그래프 탐색
- BFS
- O(T × N × N × 9)
- 하지만 T(벽이 움직이는 턴의 수)는 8이 최대이고, N 또한 8이 최대이므로 해당 문제의 시간복잡도는 상수와 가깝다.
- **O(1)
- 처음에 구현했을 때 벽 이동 시 맨 윗 줄 벽을 아래로 내리고 원래 위치의 벽은 . 처리했는데, 그럼 아랫줄 벽을 바꿀 때 이전에 바꿔주었던 윗줄의 벽에 영향이 간다.
- 그래서 visitedWall을 통해 해당 위치의 벽이 이미 윗줄에서 이동한 벽인지를 확인해 . 처리할지 말지를 결정했다(해당 위치의 벽을 없앨지 말지 결정)
- 사람 이동은 무난 bfs로 처리했고 visited 배열은 while 루프 돌 때마다 초기화시켰다
- 우선 사람이 먼저 이동해야 하므로 벽의 위치를 wall에 저장해 사람 이동 이후 하나씩 빼면서 벽을 이동시켰다.
=> Solved:[그래프 탐색] BOJ_움직이는 미로 탈출 김나영

백트래킹/나영/BOJ_15651_N과 M (3).java
- 배열
- 백트래킹
- 중복순열 => 각 자리마다 n가지 선택이 가능하고, 이를 m번 반복함
- 최종 시간복잡도 : **O(n ^ m)
- 중복된 순열을 추출하므로 dfs 안에서 1~n까지 for문을 돌면서 m 크기의 배열에 숫자를 대입
=> Solved: [백트래킹] BOJ_N과 M (3) 김나영

백트래킹/나영/BOJ_15656_N과 M (7).java
- 배열
- 백트래킹
- 중복순열 -> **O(n^m)**
- 중복순열 탐색 + 지정된 수를 배열에 저장해 출력해야 함
- Arrays.sort로 배열을 소팅하고 dfs로 중복순열 탐색 로직을 짰다(걍 for문 돌려돌려~~!)
=> Solved: [백트래킹] BOJ_N과 M (7) 김나영

백트래킹/나영/BOJ_15657_N과 M (8).java
- 배열
- 백트래킹
- 중복조합 : nHm -> n-1+m C m
- 배열을 받고 해당 배열 안의 숫자에서 중복조합을 고르는 문제
- 제약 없이 for문 돌려돌려돌림판
=> Solved: [백트래킹] BOJ_N과 M (8) 김나영

백트래킹/나영/BOJ_15655_N과 M (6).java
- 배열
- 백트래킹
- 순서 상관하지 않고 숫자를 뽑음 -> 조합 -> nCm
- 최종 시간복잡도 : nCm * m (출력 시 소요되는 시간이 m)
- 갑자기 등장한 일반 조합
- 중복 조합에 익숙해진 난 당황,, 하진 않고 그냥 i에 1 더해서 dfs 함
=> Solved: [백트래킹] BOJ_N과 M (6) 김나영

백트래킹/지우/BOJ_1174_줄어드는 수.cpp
- 벡터
- 백트래킹
1. 가능한 모든 감소하는 수를 생성하는 DFS는 최대 2¹⁰ - 1 = 1023개의 조합을 만든다 → O(2^10) = O(1) (상수).
2. 각 조합을 숫자로 변환하는 과정은 O(자릿수) = O(10) → 전체 여전히 상수 시간.
3. 생성된 1023개의 수를 정렬 → O(1023 log 1023) ≈ O(1) (상수).
dfs를 돌려서 
- 다음 수 num++; 
- if(nxt[nxt.size()-2] > nxt[nxt.size()-1])  to_string(num);
- dfs(depth+1, num+1)
- else { dfs(depth, num+1); }
- ◀️  이게 너무 오래 걸리니까  while문으로 num++; <- 조건에 만족하면 dfs(depth+1, nxtNum) 로 바꿈
- (근데 여기서 끝 두 자리만 보는게 아니라 그 위에 숫자도 더 봐야 함 -> 즉, 오래 걸린다.)
___
___
'줄어드는 수'
- 9 8 7 6 5 4 3 2 1 0
- 차례로 가면서(back하지 않고) 모든 경우의 수를 벡터에 모은다. (dfs(s+1))
- 9 (> `9 8`, `9 8 7`, `9 8 6`,,) ~ ~ ~ `1 0`,`0 `
- if(!picks.empty()) 면 결과값에 다 넣기 
- 이 모든 걸 모은 arrPicks를 sort 한다.
- 그럼 arrPicks[N-1] 은 N번째로 작은 줄어드는 수이다.
- 가장 큰 줄어드는 수는 끝이 존재한다. 9876543210 이다. arrPicks의 마지막 수이다.
- arrPicks.size() 보다 N이 같거나 크면 …
=> Solved: [백트래킹] BOJ_줄어드는 수 홍지우

백트래킹/지우/BOJ_15664_N과 M (10).cpp
- 벡터
- 조합
1. 조합이므로 전체 시간복잡도는 O(nCm) = O(N! / (M!(N-M)!))
2. 중복 수 방지를 위해 같은 깊이에서 이전 값(pre)과 비교하여 skip → 중복 제거
3. 정렬 후 중복 제거 + 순차 탐색(s부터 시작)으로 효율적인 조합 생성 가능
- 조합형태로 이전과 같이 같은 수로는 같은 깊이를 가질 수 없게 처리했다.
=> Solved: [백트래킹] BOJ_N과 M (10) 홍지우

백트래킹/지우/BOJ_1062_가르침.cpp
- 벡터, Set
- 백트래킹
1. DFS로 `totalChars`에서 **(K−5)** 개를 고르는 모든 조합 탐색 → 경우의 수 `C(C, K-5)`  
2. 각 조합마다 `check()` 실행 시 **N**개의 단어를 확인하고, 단어당 최대 **U**(고유 문자 수)만큼 검사 → `O(N × U)`  
3. 전체 시간복잡도: `O( C(C, K-5) × N × U )`, 여기서 **C ≤ 21**, **U ≤ 21**  
시간초과 2번 났다..
개선 과정
1. ❌ antic 처리 안 함 + ❌picks Set으로 들고다님 + ❌조합을 끝내면 모든 N개의 단어의 length를 전부 picks와 비교해서 풀었다
-  C(26,K) * N * L(단어 총 길이)
2. ❌antic 처리 안 함 + ⭕ picks[bool] 로 해서 포함 여부를 26개의 알파벳 O/X로 표현 + 🔺각 N개의 단어에서 중복을 제외한 포함 알파벳들만 순회함
-  C(26,K) * N * U(단어별 고유 알파벳 수)
3. ⭕ antic 사전처리 -> antic 5글자는 이미 처리한 것으로 취급하고 조합
- C(26-5, K-5) * N * U
- 5개가 무슨 큰 차이가 있겠어~ 했는데 시간초과를 줄일 수 있는 핵심이었다.
=> Solved: [백트래킹] BOJ_가르침 홍지우

백트래킹/나영/BOJ_2580_스도쿠.java
- Set
- ArrayList
- 배열
- 벡트래킹
- 구현
- 빈 칸이 n개일 때, 1~9까지 모든 숫자를 빈 칸에 대입 => 최대 O(9^n) => O(9^81)
- 하지만 해당 문제는 **스도쿠가 가능한 경우 하나만 출력** 하면 된다!
- 그리고 숫자를 채워갈수록 남은 빈 칸에 필요한 숫자의 개수가 크게 줄어들었으므로 O(9^81)까지 가는 경우는 없다.
- 빈 칸 List 채우기 : O(81)
- 출력 : O(81)
- 스도쿠 문제의 핵심은 빈 칸의 행, 열, 3*3 사각형 내부에 1~9까지의 숫자가 중복 없이 들어가야 한다는 것이다.
- 그래서 행, 열, 3*3 에 있는 숫자의 종류를 저장할 set1, set2, set3을 만들었다.
- 그리고 처음 숫자를 받아올 때 set들에 map에 있는 숫자들을 알맞은 위치에 add한다.
- 만약 빈 칸이라면 list에 해당 r, c를 add한다.
- 그리고 dfs 시작! 
- dfs에는 depth만 넘겨주고, list.get(depth)로 빈 칸의 r, c를 추출한다.
- for문을 돌려 추출한 r, c, 1~9까지의 숫자를 check 해 선택한 숫자가 해당 빈 칸과 관련된 set1, set2, set3에 있다면 return false한다.
- 만약 선택한 숫자가 모든 set에 없다면, 해당 숫자를 set1, set2, set3에 추가하고 map의 값을 바꿔준 뒤 dfs(depth+1)로 다음 빈칸으로 넘어간다.
- dfs 종료 이후에는 set에 추가한 숫자를 remove 합니다.
=> Solved: [백트래킹] BOJ_스도쿠 김나영

백트래킹/나영/BOJ_9663_N-Queen.java
- 배열
- 백트래킹
- 퀸은 "각 행과 열에 1개" 씩 놓여야 하므로 O(n!)
- check 메서드를 통해 행/열/대각선 체크 : O(n)
- 최악의 시간복잡도 : **O(n * n!)**
- 하지만 행, 열, 대각선을 기준으로 visited 확인해 가지치기를 진행하기 때문에 실제 시간복잡도는 이보다 훨씬 작다.
- Queen never die
- 처음엔 퀸을 놓으면 그 아래 행에 퀸이 이동할 수 있는 위치를 전부 방문 처리하려고 했는데, 그럼 돌아올 때 복구가 귀찮을 거 같아서 그냥 이전 행의 퀸이 현재 위치로 올 수 있는지를 확인한 뒤 dfs에 다음 행을 넘겼다.
- check 메서드를 따로 만들어 이전 행의 퀸들이 현재 위치로 올 수 있다면 return false, 아니면 return true 했숩니당.
=> Solved: [백트래킹] BOJ_N-Queen 김나영

백트래킹/지우/BOJ_18430_무기공학.cpp
- 벡터
- 백트래킹
1. DFS의 재귀 깊이는 N*M (각 칸을 한 번씩 검사)  
2. 각 칸마다 최대 4방향 부메랑 배치 시도, 각 시도는 O(1) 범위·방문 체크 수행  
3. 최악의 경우 시간복잡도는 O(4^(N*M)), 하지만 백트래킹 가지치기로 실제 탐색량은 훨씬 작음  
- 부메랑 중심이 될 idx를 뒤로 넘기며 배열을 돌게끔 했다. (이건 진짜 하나하나 다 돌아야 하는 문제!)
- ㄴ ㄱ 등 4방향으로 돌린다. (makeSum())
- 그 중심을 선택하지 않는 경우도 고려한다 dfs(idx+1, sum); 
- idx 넘겨서 하나하나 다 보는 문제에서는 의미있는 dfs 후, 아무런 일도  일어나지 않고 다음으로 갈 수 있는 dfs도 돌려야 하는 공통점이 보인다.
- inRange() N,M 다를 때 M 꼭 신경 써주기!!!
=> Solved: [백트래킹] BOJ_무기공학 홍지우

백트래킹/나영/BOJ_2661_좋은수열.java
- 배열
- 백트래킹
- dfs : 1, 2, 3을 붙이면서 n자리 수열 생성
- check로 동일 부분수열이 인접할 시 가지치기
- 이론적으로는 O(3^n)
- check : 최대 길이 n의 문자열에서 n/2 길이까지의 부분수열을 탐색해 동일한지 확인
- 이론적으로는 O(n^2)
- 문자열의 길이가 매번 다르므로 이것보단 작음
- 최악의 시간복잡도 : **O(3^n * n^2)**
- 해당 문제는 dfs로 받은 문자열의 length/2 까지 반복문을 돌리면서 해당 문자열 내부의 동일 부분수열이 인접하는지를 확인하는 문제였다
- 그래서 1~length/2까지 문자열을 substring해 front와 back으로 문자열을 나눈 뒤 서로가 같은지 비교했다
- 길이 n까지 왔다면 출력해주고 System.exit(0) 때리기~~
=> Solved: [백트래킹] BOJ_2661_좋은수열 김나영

그래프 탐색/나영/BOJ_22868_산책 (small).java
- Queue
- ArrayList
- 배열
- 그래프 탐색
- BFS
- List<Integer> ex2 = new ArrayList<>(q); : 최악의 경우 O(n) 의 시간복잡도
- BFS : 최대 O(n + m) 번 확장
- 최종 시간복잡도 : **O((n + m) * n)**
- 처음에는 경로 조합을 구해 list에 더하고, 해당 list를 sorting 해 맨 첫 번째에 위치한 경로를 빼서 방문 처리하는 방식을 썼다.
- 근데 그러면 오류 발생,,, 그리고 시간복잡도도 좋지 않을 듯
- 그래서 그냥 que 자체에 ArrayList를 넣고 경로를 추가해가며 도착점에 도달했을 때 해당 경로를 방문처리하고, 반대로 bfs를 돌려 최소 경로를 구했습니다.
=> Solved: [그래프 탐색] BOJ_산책 (small) 김나영

그래프 탐색/지우/BOJ_22868_산책 (small).cpp
- 그래프탐색(BFS)
그래프 입력 및 정렬:
O(M + N log N) — 정점마다 인접 리스트를 정렬 (sort)
BFS 두 번 수행 (왕복):
O(N + M) — 각각의 BFS에서 모든 정점과 간선을 한 번씩 방문
전체 시간복잡도:
O(N log N + M) — 정렬 + 왕복 BFS 탐색
- 골드3 이상은 시간복잡도가 O(N^2)이 되지 않게 하는게 무척 중요한 것 같다
[1차 시도] - O(N^2)
- 지나간 경로를 벡터에 넣고 그 routes 자체를 큐에 넣고 돌렸다.
- BFS로 풀어서 O(N)이 될거라 기대했지만 벡터 복사가 매 q에 넣을 때마다 발생하면서 N번 더 걸리는 문제가 생겼다.
- queue<vector<int>> q에서 경로 전체를 저장하고 복사
- q.push(currV)에서 매번 벡터 전체를 복사
🤔 여기서 DP를 떠올렸는데 목적지까지의 최단거리는 알 수 있었지만 돌아갈 때 처리가 불가능했다
💡 인접리스트를 만들면서 가볼까나
[SOLVED] 
- 큐를 인접리스트(adj)를 따라 가면서 
- p[다음] = 현재; 이렇게 인접한 것들을 모으는 배열을 만든다.
- 마지막 지점에 도착한다.
- 마지막 지점부터 p를 타면서 시작지점까지 간다.
- vis 초기화 한 다음에 p에 속하는 애들은 vis 다시 처리해준다.
- 지나는 지점만큼 ++ 해서 거리를 더해준다.
- 큐 초기화하고 마지막 지점을 넣어준다.
- 이제 돌아간다.
- goBack 라인에서 시작지점 만나면 countRoutes(); 마찬가지로 해주면 답이 뿅!
=> Solved: [그래프 탐색] BOJ_산책 (small) 홍지우

백트래킹/나영/BOJ_16922_로마 숫자 만들기.java
- Set
- 배열
- 백트래킹
- 4가지 숫자를 n 번 선택하는 **중복조합**
- k에서 n개를 뽑는 중복조합 공식
- O( C (n + 4-1, 4-1) ) = **O( C ( n + 3, 3 ) )**
- 4개의 숫자를 n개 뽑으면서, 총 몇 개의 숫자 합이 나올 수 있는지 체크하기
- 중복조합으로 탐색하면서 sum을 set에 저장해 합의 중복 제외
=> Solved: [백트래킹] BOJ_로마 숫자 만들기 김나영

백트래킹/나영/BOJ_15566_개구리 1.java
- 배열
- 브루트포스
- 백트래킹
- n개의 개구리에서 n개의 순열을 추출하므로 : nPn = n!
- n개의 개구리들의 m개의 관계를 조사 : n*m
- 최종 시간복잡도 : **O(n! * n * m)**
- 입력값이 많아서 그게 헷갈렸던 문제
- 단순하게 생각했을 때, n개에서 n개를 뽑는 순열 배열을 만들고, 중간중간 이전에 선택된 연꽃과 연꽃에 놓인 개구리, 그리고 현재 연꽃과 내가 선택하고자 하는 개구리의 
- 개구리의 선호 연꽃
- 두 개구리의 선호 대화 주제 수치
- 를 비교해 선택 가능하면 dfs에 해당 개구리를 넘겨주고 cnt == n+1이면 sb에 더하고 return 시켰다
=> Solved: [백트래킹] BOJ_개구리 1 김나영

그래프 탐색/지우/BOJ_17129_윌리암슨수액빨이딱따구리가 정보섬에 올라온 이유.cpp
- 벡터, 큐
- 그래프 탐색(BFS)
- 전체 격자판 크기는 n x m이고, BFS는 각 칸을 한 번씩만 방문 → O(n x m)
- 각 칸에서 최대 4방향으로 이동 시도하므로 상수 시간 연산 → O(1)
- 총 시간복잡도는 O(n x m)
- 여러 숫자를 활용해야 하는 기본 BFS 문제
- 시작점 q에 넣어주고 시작. (이때, 거리는 0 이고 최단거리dp[][]가 그대로 반영해주길 원하기 때문에 처음에 모두 -1로 초기화해둠)
- bfs로 점차 나아가다가 3,4,5 라는 3보다 큰 숫자를 만나면 dp에 있는 최단거리 출력 -> 그 후 바로 exit(0);
- 위에서 Exit 안됐다는 건 q도 다 털리고 Bfs() 함수 return 되었다는 것 -> 즉, 불가능 케이스 _ NIE 출력
=> Solved: [그래프 탐색] BOJ_윌리암슨수액빨이딱따구리가 정보섬에 올라온 이유 홍지우

그래프 탐색/나영/BOJ_1697_숨바꼭질.java
- 배열
- Queue
- 그래프 탐색
- BFS
- 최악의 경우 총 100000개의 칸을 탐색
- **O(100000)**
- 전에 풀지 않았나?,, 했는데 역시나~
- 2배 이동, -1, 1 순서대로 이동시키면서 가장 빠르게 도착할 수 있는 경우의 수 계산
=> Solved: [그래프 탐색] BOJ_숨바꼭질 김나영

백트래킹/나영/BOJ_1497_기타콘서트.java
- Set
- 배열
- 백트래킹
- 재귀 탐색 : 최악 2^n번 가능
- 곡 확인 : 최대 m개의 곡을 확인할 수 있으므로 O(m)
- 최종 시간복잡도 : O(2^n * m)
- max를 어느 지점에서 갱신해야 할 지가 고민이었던 문제
- set에 곡의 길이를 담아 재귀 돌리고, max에 지금까지 나온 곡 개수 중 가장 많이 사용한 곡 개수를 저장해 set의 사이즈가 max보다 크면 ans=cnt로 갱신하고, 같으면 ans와 cnt 중 더 작은 값으로 갱신한다.
- 재귀를 돌릴 때에는 notes라는 리스트를 만들어 만약 새로 추가된 곡이 있다면 해당 기타를 사용한 채로 재귀를 돌린다
=> Solved: [백트래킹] BOJ_기타콘서트 김나영

그래프 탐색/나영/BOJ_5014_스타트링크.java
- Queue
- 배열
- 그래프 탐색
- BFS
- 최대 F개의 노드를 탐색할 수 있음 : O(F)
- U만큼 더하고, D만큼 빼면서 노드를 탐색해가는 BFS
=> Solved: [그래프 탐색] BOJ_스타트링크 김나영

그래프 탐색/나영/BOJ_1303_전쟁 - 전투.java
- 배열
- 그래프 탐색
- DFS
- 최대 n*m개의 칸을 탐색할 수 있음 : O(n * m)
- DFS를 사용해 W, B인 경우 사방탐색으로 인접한 병사들까지 탐색하며 N으로 값을 바꾼다
- 맨 끝까지 가면 1을 return 하고, 돌아오면서 cnt += dfs를 통해 각 영토가 +1 된다
- dfs 하기 전에 현재 위치 방문 처리 필수!
=> Solved: [그래프 탐색] BOJ_전쟁 - 전투 김나영

그래프 탐색/나영/BOJ_17129_윌리암슨수액빨이딱따구리가 정보섬에 올라온 이유.java
- Queue
- 배열
- 그래프 탐색
- BFS
- O(n * m)
- 기본 사방탐색 bfs,,인데 난 음식을 출력하는 줄 알았는데 이동 거리를 출력하는 거였음; 이럴거면 음식 왜 나눴냐
- 좌표랑 이동 거리 que에 넣고 돌려돌려
- map의 값이 2보다 크면 멈추고 이동거리 return해
=> Solved: [그래프 탐색] BOJ_윌리암슨수액빨이딱따구리가 정보섬에 올라온 이유 김나영

백트래킹/지우/BOJ_12101_1, 2, 3 더하기 2.cpp
- String
- 백트래킹
- DFS로 1, 2, 3의 조합으로 n을 만드는 모든 경우 탐색 → 최대 O(3^n)
- 각 경로에서 문자열 이어붙이기는 최대 O(n)
- 총 시간복잡도는 O(n * 3^n) (단, k번째 해답 찾으면 조기 종료됨)
- 각 자리에 1~3이 중복을 허용하여 만들 수 있는 모든 부분집합을 구하는 느낌으로 풀었다.
- 첫째 수를 제외하고는 " + i " 를 직접 string에 저장해가며 풀었다.
- 총 합이 n이 되면 cnt를 올려주고. 그 개수가 k가 되면 바로 s를 출력하고 종료해줬다.
=> Solved: [백트래킹] BOJ_1, 2, 3 더하기 2 홍지우

백트래킹/나영/BOJ_7682_틱택토.java
- 배열
- 백트래킹
- 구현
- 말의 개수가 9개로 한정되어 있으므로, 전체 입력 1개 당 O(1)의 시간이 듦
- 주어진 테스트 케이스의 개수가 T개라고 가정
- 최종 시간복잡도 : **O(T)**
- 구현으로 풀 수 있을 거 같아서 풀었는데
- 백트래킹으로 푸는 게 나을듯,,
- 시간복잡도도,, 어차피 첨부터 가능한 케이스 모두 구해놓고 set에 있는지 확인하면 될 거 같아서 백트 추천
- 일단 X와 O의 개수를 세서, sumO == sumX 이거나 sumO == sumX - 1인 경우만 가능하므로 확인
- 그리고 대각선/행/열 기준으로 빙고가 있는지 확인하고, 있다면 각각 sumO2와 sumX2에 빙고 개수 추가
- 그리고 빙고가 존재한다면, X, O 둘 다 빙고가 있거나, X, O에 빙고가 있는데 다음 말이 놓여진 경우를 제외하고 valid 처리한다. 이 때 아니라면 invalid 처리도 **반드시** 해 줄 것
- 모든 invalid를 통과했다면,,, 빙고는 없지만 모든 칸에 말이 있는 경우 valid 처리 해 준다
- 그럼 지옥의 미로를 통과한 틱택토 결과를 출력할 수 있다
=> Solved: [백트래킹] BOJ_틱택토 김나영

그래프 탐색/지우/BOJ_9019_DSLR.cpp
- 벡터, 큐
- 그래프 탐색
- 구현
- 각 상태(0~9999)를 한 번씩만 탐색하므로 BFS 시간은 O(10000)
- 각 상태에서 최대 4개의 연산(D, S, L, R) 수행 → O(1)
- 총 시간복잡도는 O(4 * 10000) = O(40000)
- /, % 를 잘해야 하는 '구현' 문제였다. - 이걸 벡터로 접근하니까 코드만 복잡해지고 시간초과 가능성 업업업!
- 총 나올 수 있는 숫자는 9999가 최대니까 vis 공간을 10000만 만들었다.
- BFS는 이용만 당한 문제다.
=> Solved: [그래프 탐색] BOJ_DSLR 홍지우

그래프 탐색/나영/BOJ_12851_숨바꼭질 2.java
- Queue
- 배열
- 그래프 탐색
- BFS
- 0~100,000개의 칸을 한 번 씩 방문할 수 있음 : O(100,001)
- 각 정점에서 간선이 3개 생길 수 있음 : O(300,000)
- 최종 시간복잡도 : O(100,001 + 300,000) = **O(100,000)**
- 저번 숨바꼭질 문제와 비슷했던 문제
- 대신 이번엔 최소 경로를 가지는 모든 경로의 개수까지 구해야 했다
- 그래서 만약 k에 도착했을 때 ans 가 -1이라면 최소 경로 갱신시키고, 해당 타이밍에 k에 도착하는 모든 경로 개수를 cnt에 더한다.
- 그리고 만약 q[1]이 ans보다 커졌을 경우, 다음 경로 타이밍으로 넘어간 것이므로 return시킨 뒤 ans와 cnt를 출력한다.
=> Solved: [그래프 탐색] BOJ_숨바꼭질 2 김나영

그래프 탐색/지우/BOJ_13913_숨바꼭질 4.cpp
- Vector, Queue, Deque
- 그래프 탐색
- BFS로 각 위치(0~100000)를 한 번씩 방문하며 최단 거리 계산 → O(100001)
- 각 위치에서 이동 가능한 세 가지 경우 (x-1, x+1, x*2) → O(1)
- 총 시간복잡도는 O(3 * 100001) = O(100000)
- 처음에 string으로 모든 경로를 저장하며 갖고 다니려 했으나 문자열이 매 단계에서 복/붙이 되는 과정에서 시간 복잡도가 너무 증가해버림..
- 어차피 !vis[]로 한 번 간 곳은 막고있으니 pre[nxt] = curr의 개념을 활용해 경로를 타고타고 추적할 수 있게 했다.
- for( int cur = 마지막 도착지 ; cur != -1; cur = pre[cur] ) 을 하면 역추적 가능
- 근데 경로는 처음부터 인출해야 하니까 deque 활용해서 모아두고 한 번에 출력~
=> Solved: [그래프 탐색] BOJ_숨바꼭질 4 홍지우

그래프 탐색/지우/BOJ_1707_이분 그래프.cpp
- 벡터, 큐
- 그래프 탐색
- 각 테스트케이스마다 BFS로 모든 정점과 간선을 탐색 → O(V + E)
- 전체 정점은 한 번만 방문하며, 간선은 양방향으로 한 번씩 탐색
- 총 시간복잡도는 O(T * (V + E)) (T는 테스트케이스 수)
- 이분 그래프란? 중간에 순회가 일어나서는 안되는 그래프이다.
- 방문하지 않은 정점이 있다면 q에 태우고 adj인접리스트에 따라서 순회가 일어난 부분이 있는지 찾는다
- 동작 순서는 start 은 1 번 색깔로 채우고(dp[정점] = 1) 그 다음 인접한 정점은 -1 번 색깔로 채운다. (dp[정점] = -1)
- 인접하면 무조건 색이 달라야 하는 규칙으로 q에 넣고 인접리스트를 타고타고 가면서 확인하는 것이다.
- 이때, 만약 인접 노드가 이미 색이 칠해져있는데 현재 노드와 색이 같다면??!?! => 순회 발견
- 아니라면 이분 그래프
=> Solved: [그래프 탐색] BOJ_이분 그래프 홍지우

백트래킹/지우/BOJ_7490_0 만들기.cpp
- 벡터
- 백트래킹
- 연산자 선택은 N - 1곳, 각 위치마다 3가지 선택 → O(3^(N - 1))
- 각 수식마다 출력용 문자열 생성 → O(N)
- 총 시간복잡도는 O(3^(N - 1) * N)
- 어차피 모든 수의 나열은 1234..N일테니, 아스키코드가 가장 작은 공백' '부터 +, - 순으로 계산해줬다.
- 오름차순이니 dfs(s) for(int i=s; ) dfs(i+1) 이 공식을 생각했었는데 '각 자리에 무조건 하나씩은 선택해야 하는 점!' 때문에 for문을 지웠다.
- ' ' 공백이면 이전 수를 10의 자리로 갖고 현재 수를 1의 자리로 가져야 한다. pre를 저장하고, 음수인지 양수인지에 따라 상황에 알맞게 pre*10+현재 수를 직접 계산하며 진행해줬다.
=> Solved: [백트래킹] BOJ_0 만들기 홍지우

그래프 탐색/지우/BOJ_5427_불.cpp
- 그래프 탐색
- 맵의 크기는 h x w이며, 불과 사람 BFS에서 각 칸은 한 번씩만 탐색 → O(h * w)
- 각 시간 단위마다 불 먼저 확산, 그 다음 사람 이동 → 각 단위 연산은 O(1)
- 총 시간복잡도는 O(h * w) (불과 사람 BFS 각각 최대 한 번씩 수행됨)
- 이것도 풀었던 것 같은데...
- bfs() 로직: 1초마다 한 번씩 돌아간다.
- n초에 불을 4방향으로 퍼지게 한다.
- n초에 상근이는 갈 수 있는 4방향으로 간다. ('.'인 곳으로)
- 여기서 범위를 벗어나면 탈출~!
=> 만약 상근이가 갈 수 있는 곳이 없어 sq가 비게 된다면 그냥 Return (ans가 갱신되지 않았으므로 IMPOSS)
=> 다른 초까지 갈 수 있으면 bfs() 또 돌리기
=> Solved: [그래프 탐색] BOJ_불 홍지우

백트래킹/지우/BOJ_20208_진우의 민트초코우유.cpp
- 벡터
- 백트래킹
- 백트래킹으로 우유 마시는 모든 순열을 탐색 → 최대 O(m!)
- 각 경우마다 이동 가능 여부(거리 계산)와 방문 처리 → O(m)
- 총 시간복잡도는 O(m! * m), 단 m ≤ 10이하로 제한되어 탐색 가능
- input의 모양새에 속지 않아야 하는 문제였다...
- 처음에 dp[r][c][초코우유개수] = 체력으로 설정하여 BFS로 풀려고 했으나 이러면 어떤 우유를 마셨는지 또 저장해야 하고..
- 벽 같은게 없어서 거리가 확실하므로 꼭 최단거리를 Bfs를 통하지 않아도 abs(r-r2) + abs(c-c2) 이런 식으로 하면 쏘옥 구해짐..!!!
[SOLVED]
- 초코우유의 위치를 milks에 저장한다.
- dfs에서 모든 초코우유를 돌면서 만약 해당 초코우유를 아직 줍지 않았다면
- 진우의 위치부터 초코우유까지의 거리와 진우 체력을 비교해 얻을 수 있는지 확인한다.
- 얻을 수 있다면 얻는다는 가정 하에 -> Dfs(깊어지기) / 원상복구 진행
- 이때, 모든 진우의 위치에서부터 진우의 집까지의 거리를 maxAns로 저장하면서 돌린다. ans는 자동으로 집까지 돌아갈 수 있는 상황 속 가장 많이 주운 우유의 개수를 저장할 수 있게 된다.
=> Solved: [백트래킹] BOJ_진우의 민트초코우유 홍지우

그래프 탐색/지우/BOJ_3055_탈출.cpp
- 그래프 탐색
- 격자 크기 R x C에 대해 물과 고슴도치 각각 BFS → O(R * C)
- 각 칸은 물 또는 고슴도치가 최대 한 번만 방문 → O(1)
- 총 시간복잡도는 O(R * C)
- 불이랑 비슷한 문제~
- `고슴도치는 물이 찰 예정인 칸으로 이동할 수 없다. 즉, 다음 시간에 물이 찰 예정인 칸으로 고슴도치는 이동할 수 없다. 이동할 수 있으면 고슴도치가 물에 빠지기 때문이다. `<- 그래서 1분에 대해서 물 먼저 돌려주고 고슴도치 이동시켰다!
- 물 먼저 퍼지게 하고 -> 고슴도치 현재 위치에서 다음으로 '.'으로 갈 수 있니~ 없니~
=> Solved: [그래프 탐색] BOJ_탈출 홍지우

그래프 탐색/지우/BOJ_2194_유닛 이동시키기.cpp
- 큐, 벡터
- 그래프 탐색
- 격자 크기는 N x M이며, BFS로 각 위치에서 최대 4방향 이동 → O(N * M)
- 각 이동마다 직사각형이 충돌 없이 이동 가능한지 검사 → O(A * B)
- 총 시간복잡도는 O(N * M * A * B)
- A, B ≤ 10, N, M ≤ 1000 수준이라면 충분히 탐색 가능한 범위
- 시간복잡도가 더 타이트했다면 누적합으로 풀어야 함..!
- 하지만 그냥 각 위치마다 AxB 순회하며 체크해도 됐던 문제
- if(!vis[nr][nc]) <- 이거 쓰는거 까먹고 제출했다가 메모리 초과 났음 헤ㅔ헤 (vis 확인 안하면 메모리 초과가 나는구나..? 알게 됨)
=> Solved: [그래프 탐색] BOJ_유닛 이동시키기 홍지우

백트래킹/지우/BOJ_1759_암호 만들기.cpp
- Vector
- 백트래킹
- C개의 문자 중 L개를 고르는 조합 → O(C choose L)
- 각 조합마다 자음/모음 개수를 검사 → O(L)
- 총 시간복잡도는 O((C choose L) * L)
- 들어온 알파벳들을 sort 하여 사전순 오름차순에 맞게 alphabets 의 알맞은 자리를 만들어준다.
- 오름차순으로 가게끔 for(int i=s; ..) dfs(i+1)을 해준다.
- 돌아가는 중에 자음 개수와 모음 개수를 판별하여 넣어준다.
- 총 L개의 알파벳이 선택되었으면 정렬된 alphabets을 훑으며 vis 된 자리의 애들을 출력해준다.
=> Solved: [백트래킹] BOJ_암호 만들기 홍지우

완전탐색/지우/BOJ_18511_큰 수 구성하기.cpp
- 벡터
- 완전탐색
- DFS로 숫자를 붙이며 만들 수 있는 수를 전부 탐색 → O(K^L) (L = N의 자릿수)
- 각 탐색마다 숫자 비교는 O(1), 최대 자릿수는 log₁₀(N)
- 총 시간복잡도는 O(K^log₁₀(N)), N ≤ 10^9일 경우 완전탐색 가능
- 민초우유, 텔레포트3의 return 없는 무한 업데이트용 if 문이 핵심
- 가진 수를 활용해 중복 없는 수열이 N보다 작거나 같은 것들 중 가장 큰 수를 구하여라
- N보다 작거나 같은 애들이면 계속~~ 값 비교해서 그 중에 가장 큰 값을 계속 계속 업데이트 한다.
- 처음에 N의 자릿수를 신경 써서 구하려고 했는데 N=15, nums = {7} 의 경우와 같이 조건에 만족하지만 자릿수는 다른 수를 인출하지 못하겠다..! 싶어서 요로케 품
- 이거의 흔적인 depth가 dfs 인자로 있는데.. 스윽 무시해주세여.... 헤헤
=> Solved: [완전탐색] BOJ_큰 수 구성하기 홍지우

백트래킹/나영/BOJ_1038_감소하는 수.java
- ArrayList
- 배열
- 브루트포스
- 백트래킹
- 10개의 숫자를 돌며 가능한 모든 부분집합을 구해 list에 더함 : 2 ^ 10 = 1024
- list.contains : 최악 O(n) = O(1024)
- Collections.sort : O(N log N)
- 최종 시간복잡도 : **O(1024)**
- 저번 줄어드는 수 문제와 똑같은데, 값이 int형을 벗어날 수 있으므로 반드시 long으로 받아야 했다
- 그 외엔 9~0까지 돌며 list에 가능한 모든 줄어드는 수를 더하고 정렬 후 원하는 숫자를 출력하면 됨
- Set 써서 풀면 O(n^2)에서 O(n log n)으로 줄일 수 있음
=> Solved: [백트래킹] BOJ_감소하는 수 김나영

완전탐색/지우/PG_최소직사각형.cpp
- 벡터
- 완전탐색
1. 각 명함마다 정렬: O(N)
- 정렬 대상이 2개 뿐이므로 O(1) * N = O(N)
2. 전체 명함을 순회하면서 최대값 계산: O(N)
=> 총 시간 복잡도: O(N)
- 가로에는 둘 중 더 작은 수 /  세로에는 둘 중 더 큰 수 이렇게 sort를 활용해 배치시킨다.
- return 가로들 중 가장 큰 수 * 세로들 중 가장 큰 수
=> Solved: [완전탐색] PG_최소직사각형 홍지우

완전탐색/나영/PG_최소직사각형.java
- 배열
- 완전탐색
- 배열의 길이 : L일 때, 모든 배열의 원소에 대해 최대 한 번 탐색 : O(L)
- 완탐으로 안풀고 그리디로 풀기
=> Solved: [완전탐색] PG_최소직사각형 김나영

문자열/지우/BOJ_11559_Puyo Puyo.cpp
- 구현, 그래프 탐색, 시뮬레이션
1. 한 번의 라운드(연쇄)에서 전체 맵을 탐색하므로 각 라운드는 **O(R × C)**  
2. 각 색 그룹 탐색은 BFS로 이루어져 한 라운드 안에서 최대 **O(R × C)**  
3. 최대 연쇄 횟수를 K라 하면 총 시간복잡도는 **O(K × R × C)**  
- R, C 선언 안하고 6, 12로 푸니까 헤드빙빙~ 전역으로 딱 정해두고 푸니까 편~안~
1. 더이상 pop이 터지는 경우가 일어나지 않을 때까지 while문을 돌린다. 
- while문은 초기에 isS를 false로 두고 4방향 탐색 ㄱㄴ하면 true로 바꾼다
2. 4이상의 색 묶음이 있다면 모두 '.' 으로 바꿔준다. (연쇄pop)
3. 모든 pop이 끝나면 Down() 시작
- 각 열을 돌면서 색깔 리스트를 저장한다.
- 끝 열부터 색깔 리스트 뒤에서부터 순서대로 위치시킨다.
=> Solved: [그래프 탐색] BOJ_Puyo Puyo 홍지우

완전탐색/지우/PG_모의고사.cpp
- 벡터
- 완전탐색
1. 수험생별 정답 패턴을 O(N)에 맞춰 미리 생성합니다.
2. 각 수험생의 정답 수를 O(N)으로 비교하며 점수를 계산합니다.
3. 전체 시간복잡도는 O(N)입니다, N은 문제 수 (answers의 길이)입니다.
- 내가 약 9개월 전의 나보다 더 비효율적으로 풀었다는게 안 . 믿 . 겨 .
- answers의 수만큼 1,2,3의 수들을 모두 채워주고
- 정답 일치하는지 체크해주고
- 가장 큰 점수와 일치하는 애들 다 ansewr에 넣어주면 된당
=> Solved: [완전탐색] PG_모의고사 홍지우

완전탐색/지우/PG_소수 찾기.cpp
- Vector, Set
- 완전탐색
1. 가능한 모든 순열 조합을 탐색하는 DFS는 O(n!)입니다. (n = 숫자 길이)
2. 각 조합마다 소수 판별을 위해 O(√m)의 시간이 소요되며, m은 숫자의 최대값(최대 7자리 수일 수 있음).
3. 전체 시간복잡도는 **O(n! × √m)** 수준이며, n ≤ 7 이므로 실질적으로는 충분히 빠릅니다.
- IsPrime 메서드 대 등 장! ( num이 있으면 num % _2부터 루트(num)까지_ == 0 이 나오면 소수가 아님!)
- 순서 있는 모든 부분집합 만들어서 소수인지 판별해줬다!
=> Solved: [완전탐색] PG_소수 찾기 홍지우

완전탐색/지우/PG_피로도.cpp
- 벡터
- 완전탐색
- 모든 던전 방문 순서를 시도하는 완전탐색 DFS 구조입니다.
- 던전 수가 n개일 때, 가능한 경우의 수는 최대 **n! (순열)**입니다.
- 각 경우에서 조건을 확인하므로 전체 시간복잡도는 O(n!) 입니다.
- 방문한 순서가 중요한 dfs 돌리기! 처음부터 끝까지 돌리면서 해당 순서에 갈 곳 골랐다
=> Solved: [완전탐색] PG_피로도 홍지우

문자열/지우/BOJ_16916_부분 문자열 2.cpp, 문자열/지우/BOJ_16916_부분 문자열.cpp
- String 
- 문자열
[KMP]
- 실패 테이블 생성(`makeTable`)은 패턴 길이만큼 탐색 → O(M)
- 본 문자열 탐색(`kmp`)은 매칭 실패 시 점프하므로 전체적으로 O(N)
- 총 시간복잡도는 O(N + M) (N = |s|, M = |p|)
[strstr]
- `strstr()` 함수는 문자열 `s`에서 `p`를 찾기 위해 최악의 경우 O(|s| * |p|) 수행
- 내부적으로는 보통 Naive 방식 (부분 문자열을 한 칸씩 비교) 기반
- 총 시간복잡도는 O(N * M) (N = |s|, M = |p|)
※ 단, 일부 구현체(GNU C++)에서는 `strstr`이 최적화되어 평균적으로 더 빠를 수 있음 (GCC의 라이브러리 구현인 libstdc++에서는 O(N+M)의 시간 복잡도의 알고리즘으로 구현되어 있다고 한다.)
- KMP를 알아보자... (알아보지 말자.._) https://www.youtube.com/watch?v=yWWbLrV4PZ8
시간초과의 역사
- 간단하게 for문 2개로 풀려고 했으나 out-
- string.find()를 사용하려고 했으나 이것도 O(N*M)이다.
- strstr 이라는 좋은 친구를 알게 되었다. .. 요긴하게 써야겠다 호히히
- kmp는,, mismatch 하면 갈 자리를 미리 저장해둔다는 개념인데 여러 번 다시 개념 보면서 익숙해져야 할 것 같다
=> Solved: [문자열] BOJ_부분 문자열 홍지우

문자열/지우/BOJ_16171_나는 친구가 적다 (Small).cpp
- string
- 문자열
1. 알파벳만 추출하는 과정에서 문자열 `s`를 한 번 순회 → **O(|s|)**
2. `strstr()` 함수는 내부적으로 최대 **O(|s| × |k|)** 의 서브스트링 비교 (단, c++에서는 예외적으로 빠르게 구현되어 있음)
3. 전체 시간복잡도는 **O(|s| × |k|)** — 단, `k`가 매우 짧으면 사실상 \*\*O(|s|)\*\*에 가까움
📌 |s|: 입력 문자열 `s`의 길이
📌 |k|: 검색 문자열 `k`의 길이
- strstr( string.c_str(), 2.c_str() ) != NULL 을 또 다시 활용했다
- 알파벳인지 확인하는 메서드를 활용해 s에서 알파벳만 걸러서 비교했다.
=> Solved: [문자열] BOJ_나는 친구가 적다 (Small) 홍지우

그래프 탐색/나영/PG_단어 변환.java
- Queue
- 배열
- 그래프 탐색
- BFS
- bfs 
- 각 word를 que에 최대 한 번씩 넣음 : O(n)
- 하나의 단어를 꺼낼 때마다 길이 n의 words 배열을 돌며 이미 방문한 단어인지, 아니라면 한 글자만 바뀌었는지 check로 확인 : O(n)
- check
- 현재 문자열 s1과 이동할 문자열 s2를 비교해 한 글자만 바뀌었는지 확인 : O(l)
- 최종 시간복잡도 : **O(n^2 * l)**
- begin 문자열에서 target으로 갈 수 있는지 확인하기 위해 일단 words에 target이 있는지 체크했다
- 그리고 bfs를 통해 begin에서 한 글자만 바뀐 다음 문자열, 그 문자열에서 한 글자만 바뀐 다음 문자열... 이렇게 이동하면서 target 문자열까지 갈 수 있는지 최단 거리를 확보하여 답을 도출했다!
=> Solved: [그래프 탐색] PG_단어 변환 김나영

백트래킹/나영/BOJ_1759_암호 만들기.java
- 배열
- HashSet
- 백트래킹
- 조합
- 길이 C의 배열에서 L개의 문자를 순서 없는 조합으로 선택 : C(C, L)
- check 메서드 : 길이 L의 배열을 검사하여 모음/자음 개수 확인, sb에 append : L
- 최종 시간복잡도 : **O(C(C, L) * L)**
- 미리 모음만 있는 set을 만들어 C개의 문자에서 L개를 선택한 뒤, 가능한 암호인지 검증할 때 해당 문자가 set에 있다면 모음 변수++, 아니면 자음 변수++ 해 갯수를 확인한다(지금 생각해보니 걍 전체 길이 - 모음 개수 했어도 됐을 듯)
- 이 때 Arrays.sort 잊지 않음 깔깔
- Arrays.asList()로 ArrayList를 직접 생성할 수 있다는 것을 알게 되었다
=> Solved: [백트래킹] BOJ_암호 만들기 김나영

그래프 탐색/나영/BOJ_2194_유닛 이동시키기.java
- Queue
- 배열
- 그래프 탐색
- BFS
- 모든 칸을 최대 한 번 탐색 : n*m
- check 메서드 : O(1)
- findWall 메서드 : O(A * B)
- 최종 시간복잡도 : **O((n*m) * (A*B))**
- 처음엔 visited 배열 하나만 두고 장애물/이미 방문한 지점 체크하려고 했는데, 그럼 findWall에서 장애물 체크 시 이미 방문한 지점도 장애물로 인식했음
- 그래서 map, visited를 따로 두고 각각 장애물용/방문 지점 체크용으로 나누어 사용했다
- check 메서드로 이동 시 해당 방향의 범위 확인
- findWall 메서드로 이동할 칸의 장애물 여부 확인
=> Solved: [그래프 탐색] BOJ_유닛 이동시키기 김나영

문자열/지우/BOJ_20154_이 구역의 승자는 누구야?!.cpp
- String, 배열
- 문자열, 구현
1. 문자열 `s`의 길이만큼 반복하므로 입력 길이를 N이라 할 때 → O(N)
2. 각 반복에서 상수 시간 연산 (배열 접근, 덧셈 등)만 수행 → O(1)
3. 전체 시간복잡도는 **O(N)** — 입력 문자열 길이에 비례
- 각 두 자리씩 값을 더해주며 pos를 이동시켰다.
- A - 'A'는 0이 나온다는 사실을 이용했다.
=> Solved: [문자열] BOJ_이 구역의 승자는 누구야?! 홍지우

문자열/지우/BOJ_1181_단어 정렬.cpp
- String, Set
- 문자열
1. 문자열 N개를 `set`에 삽입할 때마다 O(log N) 시간 소요 → 총 **O(N log N)**
2. 삽입 시 길이와 사전순으로 정렬되므로 별도 정렬 과정 필요 없음
3. 출력은 O(N), 따라서 전체 시간복잡도는 **O(N log N)**
- 정렬 기준이 1. 문자열의 짧은 것부터 2. 사전 순
- tree set 활용해서 <{문자열 길이, 문자열} > 로 넣어주고 정렬된 순서대로 출력해줬다.
=> Solved: [문자열] BOJ_단어 정렬 홍지우

백트래킹/나영/BOJ_7490_0 만들기.java
- 문자열
- 문자열
- 백트래킹
- dfs :  각 단계에서 3가지 선택 → 경우의 수는 3 ^ 𝑛−1 
- 매 경우마다 check() 실행 → 𝑂(𝑛)
- 전체 시간복잡도 = 𝑂(3^𝑛⋅𝑛)
- 문자열이 싫어요
- 돌리는 것까진 됐는데 문자열 복구 후 연산 디버깅 개빡,,
- 생각을 하면서 코드를 짜자!
=> Solved: [백트래킹] BOJ_0 만들기 김나영

문자열/나영/BOJ_9046_복호화.java
- String
- 배열
- 문자열
- 입력 문자열 전처리: 공백 제거 후 문자 배열로 변환 → O(L) 
- 문자 등장 횟수 세기: 1번 루프를 돌며 알파벳 카운트 → O(L) 
- 최빈 문자 판별: 한 번 더 루프 돌며 최대 빈도와 유일성 확인 → O(L) 
- 최종 시간복잡도: 테스트 케이스 수 T를 곱하면 **O(T * L)**
- cnt 배열로 각 알파벳 당 빈도수를 저장
- max와 maxChar를 통해 가장 빈도수가 큰 값, 해당 알파벳을 저장하고, 다음 알파벳이 빈도수가 같거나 서로 다른 알파벳일 경우 isS = false 처리해 사용 가능한지 체크
- 문자열 힘들다 깔깔
=> Solved: [문자열] BOJ_복호화 김나영

문자열/나영/BOJ_16171_나는 친구가 적다 (Small).java
- String
- 문자열
- replaceAll("[0-9]", "") : O(L)
- 이거 안 쓰고 주석 처리한 부분 사용하면 최대 O(L^2)
- s.contains(keyword) : O(L * M)
- contains라는 개꿀 메서드를 배운 날. 오늘을 공휴일로 지정해야 한다. 부분 문자열도 이거로 풀면 됐음,,, ㄷㄷ
- replaceAll("[0-9]", "") 해당 메서드와 정규식을 통해 문자열 내 모든 숫자를 제거할 수 있음
=> Solved: [문자열] BOJ_나는 친구가 적다 (Small) 김나영

완전탐색/나영/PG_모음 사전.java
- 배열
- 완전탐색
- 5^1 ~ 5^5까지 탐색 가능
- 최종 시간복잡도 : **O(5^1 + ... + 5^5) = O(3905)**
- 중간에 끊는 부분을 잘못하고 있었삼,,, 언제쯤!!!!! 백트래킹 실력이 늘 것인가
- return 타입을 boolean으로 처리해 특정 문자열에 다다르면 return true, 아니고 문자열 길이가 5를 넘어갈 경우 return false 시킨다
=> Solved: [완전탐색] PG_모음 사전 김나영

구현/나영/BOJ_2469_사다리 타기.java
- 배열
- 구현
- 문자열
- find 메서드 : 0~k-1까지 사다리에 따른 원소 위치 변경 => O(k)
- top, bottom 배열 구성을 위해 find 메서드를 최대 n번 돌림 => O(n * k)
- dfs : 0~k-1까지 원소를 최대 한 번 접근하여 사다리로 위/아래 배열이 맞춰질 수 있는지 확인 => O(k)
- 최종 시간복잡도 : **O(n * k)**
- 그냥 dfs로 냅다 모든 사다리 조합 구하면 2^26이라 개터짐
- 최종 도착한 사다리 위치를 제공하므로, 비어있는 배열 m을 기준으로 맨 위~m-1까지 player의 위치 지정, 최종 도착한 위치~m+1까지 player 위치 지정한다.
- 그리고 dfs를 통해 m-1과 m+1의 player 위치를 비교하며 현재 위치의 player가 다를 때 양 옆 player가 swap 가능하면 바꿔주고, 바꿔도 짝이 맞지 않다면 return false한다.
=> Solved: [구현] BOJ_사다리 타기 김나영

그래프 탐색/지우/BOJ_17141_연구소 2.cpp
- 그래프 탐색
1. **바이러스 위치 M개 조합:**
* 전체 바이러스 위치 수를 `V`라고 할 때, M개 선택 → **조합 수 = C(V, M)**
* 최대 10개 중 5개 선택해도 **252개** 수준이므로 **O(C(V, M))**
2. **각 조합마다 BFS 탐색:**
* 한 번의 BFS는 **N×N 격자 전체를 탐색** → **O(N²)**
3. **총 시간복잡도:**
* **O(C(V, M) × N²)**
* 최대: `V=10`, `M=5`, `N=50`이면 → `252 × 2500 = 630,000` → **충분히 빠름**
- '모든' 빈 칸에 처음에 배치받지 못한 2 칸도 포함해야 했다 (97% 반례케이스)
- 문제 잘 읽자..
- dfs로 M개의 바이러스 배치할 곳 정하면 -> bfs()로 그때의 경우에서 바이러스가 모든 곳에 퍼지는 시간을 구했다. 
- 모든 조건에 맞다면 return Time~ 아니면 MAX 값을 넣어 ans가 작은 값으로 업데이트 되지 않게 했다.
=> Solved: [그래프 탐색] BOJ_연구소 2 홍지우

백트래킹/나영/BOJ_19942_다이어트.java
- ArrayList
- 배열
- 백트래킹
- dfs : 모든 부분집합을 탐색하므로 2^n
- 리스트 복사 : O(n)
- 최종 시간복잡도 : **O(n * 2^n)** 이지만, 모든 경우에 리스트 복사를 하지는 않음
- i와 idx를 자꾸 혼용해서 씀,,, 디버깅지옥;
- 무조건 **사전 순 정렬** 이므로 min이 현재 선택된 재료들의 최종 값보다 커야 해당 재료를 사용할 수 있다
- min이 초기화되지 않은 경우도 꼬옥 체크해서 -1 출력해주기!
=> Solved: [백트래킹] BOJ_다이어트 김나영

시뮬레이션/지우/BOJ_5212_지구 온난화.cpp
- 시뮬레이션
1. 모든 칸을 한 번씩 탐색하며 각 칸의 주변 4방향을 확인 → O(R * C)  
2. 주변 바다(‘.’)가 3칸 이상인 육지(‘X’)를 따로 저장 후 갱신 → O(R * C)  
3. 전체 시간복잡도는 O(R * C), 입력 크기만큼 선형적으로 처리됨
- 유효한 작은 박스 어떻게 인출하면 좋을지 고민이 있었다
- X인 칸의 r,c를 모두 받아서 가장 작은 수(sr,sc) 가장 큰 수 (er,ec)로 설정하면 됐다
=> Solved: [시뮬레이션] BOJ_지구 온난화 홍지우

시뮬레이션/나영/BOJ_5212_지구 온난화.java
- 배열
- 시뮬레이션
- reMap, find 메서드 모두 n*m 크기의 map의 요소를 한 번씩만 접근하면서 섬의 개수 파악
- 최종 시간복잡도 : **O(n * m)**
- 출력을 어떻게 해야 할 지 고민이었는데, 처음엔 map의 값을 바꿔서 출력하지 않도록 하려 했지만 그냥 findR, findC를 통해 시작점/끝점을 sR, n, sC, m에 각각 넣은 뒤, 0~n, n-1~0까지 돌려 한 행에 섬이 없는 경우 sR++, n--로 해당 행을 출력하지 않게 했고, 마찬가지로 열의 경우도 sC++, m--로 출력 출발 지점/도착 지점을 바꿔 주었다.
=> Solved: [시뮬레이션] BOJ_지구 온난화 김나영

시뮬레이션/나영/BOJ_1713_후보 추천하기.java
- ArrayList
- 배열
- 시뮬레이션
- 구현
- 추천 수 : m번
- 사진 틀 확인/후보 제거 : O(n)
- list.contains(a) → O(n)
- 최소 추천 후보 탐색 → O(n)
- list.remove(index) → O(n)
- list 정렬 : O(n log n)
- 최종 시간복잡도 : O(m * n + n log n)
- 맨 나중에 들어온 사람을 제거해야 하는 줄 알았는데, 추천 수가 동일하게 가장 적으면 **가장 오래 list에 있었던 사람** 을 제거하는 거였음; 문제안읽기챌린지시작
- list의 size가 m과 동일해진다면 한 명 제거해야 함. list를 돌며 가장 추천 수가 적은 학생 리스트를 prospect에 저장
- 지금 생각해보면 걍 prospect 안 쓰고 숫자 변수 쓰면 됐을 듯 헤헷
- 그리고 가장 앞에 있는 학생 쏘옥 빼서 list에 제거 후 a 넣어주기!
=> Solved: [시뮬레이션] BOJ_후보 추천하기 김나영

시뮬레이션/지우/BOJ_14891_톱니바퀴.cpp
- Vector
- 시뮬레이션
- 구현
1. 톱니바퀴 개수는 고정 4개이므로 `Solve()`에서 최대 4번 회전 여부 체크, `Turn()`에서 톱니 8개 이동  
2. 회전 횟수는 K번이고, 각 회전당 처리 시간은 O(1) (톱니 수 고정이므로)  
3. 전체 시간복잡도는 **O(K)** → K ≤ 100일 경우 충분히 빠름 (실질적으로 상수 시간 알고리즘)
- Solve()에서 한 번만 처리되는게 아니라 '연쇄적'으로 처리되는 걸 고려했어야 했다
- 오른쪽으로 맞닿는 부분이 어디까지 영향이 가는지 미리 파악해서 배열에 반영해준다.
- 왼쪽으로 맞닿는 부분이 연결연결 어디까지 영향이 가는지 미리 파악해서 배열에 반영해준다.
- 연결 끊겼으면 Break; (그 다음엔 안 움직이니까)
- Turn은 배열돌리기 처럼 하나씩 공간 밀고 남은 공간에 tmp 저장된거 넣어줬다
=> Solved: [시뮬레이션] BOJ_톱니바퀴 홍지우

투 포인터/지우/BOJ_21921_블로그.cpp
- Vector
- 투 포인터
1. 한 번의 while 루프로 슬라이딩 윈도우 구현 → O(N)  
2. 각 요소는 정확히 한 번씩만 더하고 뺌 → O(1) 연산 * N  
3. 전체 시간복잡도: O(N), 공간복잡도: O(N) (입력 배열 저장)  
- p2를 하나씩 움직이며 더하다가 p1과 p2의 차이가 X만큼 날 때, 현재까지의 sum을 최댓값과 비교하고 p1의 위치를 옮겨주며 다시 시작
- 7번줄 : I/O 속도 줄여주는 코드 추가 + 21~27번 줄: max 값 처리하면서 바로 cnt 갱신해주기 코드 추가 => 속도 4배 향상(84ms > 20ms)
=> Solved: [투 포인터] BOJ_블로그 홍지우

백트래킹/지우/BOJ_19942_다이어트.cpp
- Vector, Set
- 백트래킹
1. DFS로 각 식재료 선택 여부를 결정하므로 전체 경우의 수는 O(2^N)
2. 각 DFS 경로에서 영양소 누적과 조건 검사, 배열 복사 등이 O(N) 이하로 수행
3. 최종 시간복잡도는 O(2^N * N)이며, N ≤ 15일 때 현실적으로 처리 가능
- set의 정렬 기능을 적극 활용해서 풀었당당당
- dfs(식재료, 비용, 단, 지, 탄, 비) 이렇게 데리고 다닌다.
- dfs에서 해당 식재료를 넣을까~? 뺄까~? 를 수행한다.
- 만약 제공된 Limits에 대해 단, 지, 탄, 비가 모두 해당 수를 넘는다면 정답 후보군이다.
- set에 (비용, 선택된 재료들 벡터)를 넣어준다. <- 이럼 가장 작은 비용, 사전 순으로 가장 빠른 picks가 자동정렬된다.
- 가장 적은 비용은 변수로 관리하면서 가지치기에 활용해줬다!
=> Solved: [백트래킹] BOJ_다이어트 홍지우

시뮬레이션/나영/BOJ_20165_인내의 도미노 장인 호석.java
- 배열
- 시뮬레이션
- 입/출력 : O(n×m)
- R번의 라운드 진행 : O(R)
- changeMap() : 최악의 경우 한 줄 전체까지 while 문이 반복 : O(max(n, m))
- 최종 시간복잡도 : O(n×m) + O(R * max(n, m))
- 라운드마다 공격수가 무너뜨린 도미노의 개수를 체크해야 했던 문제
- changeMap 메서드
- 공격수가 특정 위치의 도미노를 특정 방향으로 무너뜨렸을 때, 해당 위치의 map 값을 cnt에 넣고 while문을 돌기 전 미리 -1 해줘야 한다(본인을 무너뜨리는 값도 포함되어 있기 때문에)
- while문을 돌며 다음 위치로 넘어갈 때 해당 위치의 도미노가 무너지지 않은 상태라면 ans++ 해 주고 cnt에 해당 도미노 숫자 -1, cnt 중 더 큰 값을 넣어 준다
- 수비수가 원복하기 전에 ans를 갱신해야 한다!
=> Solved: [시뮬레이션] BOJ_인내의 도미노 장인 호석 김나영

시뮬레이션/나영/BOJ_20055_컨베이어 벨트 위의 로봇.java
- 배열
- 시뮬레이션
- 구현
- 한 턴(step) 연산:
- rotate() → O(n)
- moveRobots() → O(n)
- 로봇 올리기 → O(1)
→ 합쳐서 O(n)
- 전체 반복 횟수(step) = 내구도 0인 칸이 k개 될 때까지 → 최악 O(step)
- 최종 시간복잡도 : **𝑂(𝑠𝑡𝑒𝑝⋅𝑛)**
- 문제 좀 잘 써줘라
- 문제 이해가 어려웠던 문제,,, 어차피 n 레일에 다 내려버리니까 레일의 길이가 사실상 한정되어 있고 내구도랑 로봇만 와리가리 하면 됐었다
=> Solved: [시뮬레이션] BOJ_컨베이어 벨트 위의 로봇 김나영

백트래킹/지우/BOJ_1405_미친 로봇.cpp
- Vector
- 백트래킹
1. 최대 탐색 깊이는 N이며, 각 위치에서 최대 4방향으로 이동 → O(4^N)
2. 방문 체크로 중복 경로 방지, 하지만 좌표 기준으로는 완전탐색에 가깝다
3. 따라서 시간복잡도는 **O(4^N)**이며, N ≤ 14 정도까지는 실시간으로 가능  
- 문제 이해가 좀 어려웠지만..
- 결국엔 이전 걸 방문하지 않고 N번을 성공적으로 간 경로의 지금까지의 확률을 구하면 되는 문제였다.
- 최대 14번 움직이니까 100x100이라는 큰 공간을 만들어서 돌게 만들었다.
---
- 소수점 자리수 결정하는거 c++에서 오늘 처음 써봤다.
```
#Include <iomanip>
cout << fixed;
cout.precision(몇 자리 수?)
cout << float 자료형을 가진 어떤 변수
```
=> Solved: [백트래킹] BOJ_미친 로봇 홍지우

문자열/지우/BOJ_9342_염색체.cpp
- Set, String
- 문자열
1. 테스트 케이스마다 문자열 한 번 순회 → O(L) (L: 문자열 길이)
2. 총 T개의 테스트 케이스에 대해 수행 → O(T × L)
3. 전체 시간복잡도는 **O(T × L)**, 문자열 길이와 테스트 수가 작다면 충분히 통과 가능
- ㅎㅎ... 빡구현이란.. 이런 것일까..?
- check 변수를 조건을 만족한 step이라고 생각하며 풀었다
- check = 0 : 문자열은 {A, B, C, D, E, F} 중 0개 또는 1개로 시작해야 한다.
- check = 1, 2, 3 : 그 다음에는 A, F, C가 하나 또는 그 이상 있어야 한다.
- check = 4 : 그 다음에는 {A, B, C, D, E, F} 중 0개 또는 1개가 있으며
- check 5 : , 더 이상의 문자는 없어야 한다. <= check 5가 나왔다는 건 아직 안 끝났다는 거 out!!
---
- 정규표현식을 사용하면 .. Solve 메서드를 한 줄컷 할 수 있다고 한다.. 공부해봐야겠다..
- https://hamait.tistory.com/342
```
#include <regex> // 정규 표현식 라이브러리
// 문제의 규칙을 정규 표현식 패턴으로 정의
regex pattern("^[A-F]A+F+C+[A-F]$");
if (regex_match(s, pattern)) {
cout << "Infected" << "\n";
} else {
cout << "Good" << "\n";
}
```
=> Solved: [문자열] BOJ_염색체 홍지우

백트래킹/지우/BOJ_2239_스토쿠.cpp
- Vector
- 백트래킹
1. 최대 빈칸이 81개이므로 완전탐색 경우의 수는 O(9^K), (K: 빈칸 수, 최악은 K=81)
2. 각 칸마다 유효성 검사는 O(9) (행/열/3x3 체크)
3. 최악의 시간복잡도는 **O(9^K × 9) ≈ O(9^K)** (하지만 백트래킹으로 실제 탐색 수는 훨씬 적음)
- 인덱스 하나씩 옮기면서 maps[][]=0인 곳에 1~9 의 수를 대입해본다. 
- 행에 같은 수가 있는지(checkRow), 열에 같은 수가 있는지(checkCol), 3x3에 같은 수가 있는지(check9)에 만족하면? 해당 수를 넣고 백트~
- 오늘의 디버깅
- int sr = (x/3)만 해두고 *3 잊고 돌렸더니 - 어쩐지 값이 이상하게 나오드라~  
- r <sr+3; 인데 그냥 <3을 해버렸었음... 헤헷
=> Solved: [백트래킹] BOJ_스도쿠 홍지우

그래프 탐색/나영/BOJ_2638_치즈.java
- Queue
- 배열
- 그래프 탐색
- BFS
- while문 : 최대 days 번 반복
- BFS : 
- 한 반복에 각 칸을 최대 1번 방문할 수 있음  O(n*m)
- reMap : 각 칸을 한 번씩 방문하며 녹일 치즈가 있는지 확인 : O(n*m)
- 최종 시간복잡도 : **O(days * n * m)**
- 처음에 치즈를 녹일 때 가장자리에서 출발해 **외부 공기**에만 접근해야 한다는 점을 유의해야 함
- 가장자리에는 치즈가 없으므로 0, 0부터 bfs를 돌려 만약 0을 발견한다면 que에 넣어 주고, 1을 발견하면 해당 위치의 remove 배열에 공기와 접촉한 횟수를 ++ 해준다. 그리고 que에 넣지 않는다.
- 여기서 vis 처리 위치 잘못 써서 디버깅함,,, 젝이랄
- 모든 bfs가 끝나고 reMap을 통해 remove가 2 이상인 경우 cheese-- 하고 0으로 바꿔준다
- 그리고 days++해주고 cheese가 0보다 크다면 킵고잉. 아니면 days 출력.
- 애초에 치즈 개수가 0일 때도 대비했다.
=> Solved: [그래프 탐색] BOJ_치즈 김나영

문자열/나영/BOJ_20437_문자열 게임 2.java
- ArrayList
- 배열
- 문자열
- 슬라이딩 윈도우
- 문자열 한 번 순회 : 각 문자 인덱스 리스트 저장 → O(N)
- 각 문자 리스트에서 윈도우 크기 K로 순회
- 리스트 크기 총합은 N을 넘지 않음 → O(N)
- 최종 시간 복잡도 = O(N)
- 처음엔 누적합 배열로 풀려고 했는데, 알파벳의 종류가 여러 개이다 보니 각 알파벳 당 누적합을 구하기가 너무 어려웠음,,, 그리고 시초 날 거 같았음
- 슬라이딩 윈도우로 풀어야 한다는 것을 알고 각 문자열을 받을 때마다 해당 문자 리스트에 그 문자가 존재하는 인덱스를 모두 넣음
- 그리고 list를 돌며 start 를 출발 인덱스, end를 출발 인덱스 + k - 1로 놓고 가장 짧은 문자열의 길이와 해당 문자가 같을 경우 가장 긴 문자열의 길이를 구한다
- 생각해 보니까 어차피 두 문자는 무조건 같으므로 ch[start] == ch[end]는 굳이 안 해도 될듯 헤헷
=> Solved: [문자열] BOJ_문자열 게임 2 김나영

시뮬레이션/나영/BOJ_15683_감시.java
- ArrayList
- 배열
- 시뮬레이션
- 백트래킹
- 브루트포스
- cctv 개수 = k개
- cctv 별 분기 수 : 
- 1 : 4개
- 2 : 2개
- 3 : 4개
- 4 : 4개
- 5 : 1개
- dfs() : 분기 ^ cctv 개수의 곱 => 4^k1​ ⋅ 2^k2 ​⋅ 4^k3 ​⋅ 4^k4 ​⋅ 1^k5​
- 최대 4^k
- change() : 벽이 있을 때 or n, m의 끝까지 탐색하면서 사각지대 파괴 -> Max(n, m)
- cctv 모두 선택 후 사각지대 개수 탐색 -> O(n * m)
- 최종 시간복잡도 : **O(4^k * n *m)
- 분기가 많아서 헷갈렸던 문제,,,
- 하지만! 메서드와 함께라면 무섭지 않아
- 근데 이제 d 표시를 cctv 2에서 잘 체크해야 하는
=> Solved: [시뮬레이션] BOJ_감시 김나영

문자열/나영/BOJ_20210_파일 탐색기.java
- 배열
- 문자열
- 구현
- Arrays.sort() : O(n log n)
- 정렬 한 번에 한 문자열의 끝까지 탐색 가능 : O(문자열 길이 l)
- 최종 시간복잡도 : O(n log n * l)
- Arrays.sort를 이용해 푸는 문제
- 내부 정렬 로직 짜는데 죽고싶었음.
1. a, b 두 배열의 인덱스를 각각 0부터 변수 idx1, idx2에 받고 시작
2. 만약 현재 위치의 문자가 둘 다 숫자라면 숫자 뭉치를 꺼내서 크기 비교를 해야 함
- 숫자가 아닐 때까지 idx1, idx2를 증가시키고 sb에 append
- 이 때 앞자리가 0일 수 있으므로 해당 경우엔 sb에 넣지 않고 zeroCnt++한다.
- 모든 숫자를 꺼냈다면 길이 비교, 값 비교, zeroCnt 비교 후 return 한다.
3. 하나만 숫자일 경우 a1 - b1을 return한다
4. 둘 다 문자일 경우 대문자로 바꾼 뒤, 문자 자체가 같은지, 같다면 둘 중 하나가 소문자인지 확인한다
5. 둘 다 문자인데 값이 같을 경우에는 미리 if (a1 != b1) 문으로 빼 준다.
- 구현하느라 머리에 쥐날거같음
=> Solved: [문자열] BOJ_파일 탐색기 김나영
