The-Algorithm-Rumbling/Attack-On-Algo

자료구조/나영/BOJ_1874_스택 수열.java
- stack
- 배열(포인터)
- O(n)
- cur를 증감시키는 과정이 총 n번까지만 진행
- n^2로 보일 수도 있지만, stack 안에서 오름차순으로 차근차근 정수를 넣어야 하므로 결국 while문이 도는 최종 횟수가 n번이 됩니다.
- 늘 for문 안의 while문을 보면 n^2라고 생각하고 싶어지지만, 조금 더 깊이 생각하는 것이 좋을 것 같다고 생각했습니다.
- 처음에 cur을 쓰지 않고 stack.peek()와 visited 배열을 사용했는데 시간 초과가 나서 cur로 변경했습니다. 카운트 방법에 대해 좀 더 고심해야 할 것 같습니다.
- 아 맞다 StringBuilder 초기화 방법
1. 재선언
2. sb.delete();
3. sb.setLength(0);
=> Solved: [자료구조] BOJ_스택 수열 김나영

자료구조/나영/BOJ_10799_쇠막대기.java
- stack
- 모두 O(n)
- stack.add() ➜ O(1)
- stack.pop() ➜ O(1)
- stack.size() ➜ O(1)
- 또한 n번 순회하므로 ➜ O(n)
- 스택과 포인터를 둘 다 이용해 문제를 풀었는데, 거의 차이는 없는 듯 하다
- 메모리/시간에서 스택이 약간 더 느리고 메모리 소모가 있다.
- Stack ver - 메모리 : 14928 KB, 시간 : 112 ms
- Cnt ver    - 메모리 : 14184 KB, 시간 : 88 ms
=> Solved: [자료구조] BOJ_쇠막대기 김나영

자료구조/나영/BOJ_2493_탑.java
- stack
- O(n)
- stack 두 개를 활용해서 수신 받을 탑과 송신하는 탑을 각각 s1, s2로 설정한다.
- 그리고 s1에서 원소를 하나씩 s2에 넣으면서 s1.peek() **즉, 왼쪽에 있는 탑** 의 높이가 s2에 있는 탑보다 높을 경우 s2.peek()의 높이가 더 커지기 전까지 s2의 원소를 빼 준다.
- stack 2개를 활용하는 점을 포인트로 두었습니다.
- 만약 오른쪽으로 비교한다면 queue 하나, stack 하나를 사용해서 풀어야 할 것 같다고 생각했습니다.
=> Solved: [자료구조] BOJ_탑 김나영

자료구조/지우/BOJ_2800_괄호 제거.cpp
- 스택
- Set(TreeSet)
- 재귀(백트래킹)
1. 가능한 선택 조합: 2^M
- v.size() = M → 각 괄호쌍마다 선택지 2가지 (제거 or 유지)
2. 각 조합마다 문자열 생성:O(N)
- 문자열 길이 N에 대해 visited[i] == true인 위치를 제거하면서 새 문자열 생성
3. 결과 저장 set<string>에 insert 문자열의 길이 = O(N)
- set에 문자열 삽입 = O(log K), K는 현재까지의 삽입 수
✅ 결론
```
(조합 수) × (각 조합에서 문자열 생성 시간)
= O(2^M × N)
```
- 여러 개의 괄호쌍을 조합하며 재귀로 푸는 신선한 경험 
- 일반 재귀 + 쌍을 갖고 가기
- depth는 쌍의 총 개수(그 안에서 포함?/비포함? 각각의 경우로 깊이가 쭈욱 깊어지기)
- 일반 재귀로 풀었는데 어떻게 하면 사전순으로 내보낼 수 있지..? 디버깅을 통해 고민 많이 함
-> c++에서 Set(TreeSet)을 처음 써봤음. 자동정렬, 중복 제거
- Set 문법
- set.insert(값) 
- 값 뽑을 때
```
for(auto i:set) { i }
```
=> Solved: [자료구조] BOJ_괄호 제거 홍지우

자료구조/나영/BOJ_2800_괄호 제거.java
- 스택
- 리스트
- 셋
- 전체 시간복잡도 : O(n * 2^k * k)  = > k는 괄호 쌍의 개수
- 재귀적으로 괄호쌍을 **제거하거나 유지** 해야 하기 때문에 경우의 수가 **2^k**
- TreeSet은 이진탐색트리 기반이므로 삽입에 O(log n)
- 최대 2^k 개의 문자열을 삽입할 수 있으므로 O(log 2^k) == O(k)
- 인덱스를 디지게 잘 활용했어야 하는 문제,,,
- list에 각 괄호의 인덱스를 지정해 재귀로 각 인덱스들을 true false 처리해가며 제거하는 문제였다.
- TreeSet을 사용하면 사전 순으로 자동 정렬해 줌
- 재귀 함수에서 자동으로 사전 순 정렬은 어려운 듯,,,?
=> Solved: [자료구조] BOJ_괄호 제거 김나영

구현/지우/BOJ_20207_달력.cpp
- 벡터
- 구현
일정 입력 처리에서 각 구간마다 O(end - start + 1) 수행 → 전체는 O(N × D), 최악의 경우 N=1000, D=365.
이후 면적 계산 단계는 days[1~366]을 한 번 순회하므로 O(365) = O(1).
전체 시간복잡도는 O(N × D), 즉 **최악의 경우 O(365,000)**
- 벡터 공간을 366으로 딱 알맞게 뒀다 (각 칸이 날짜를 의미하게) 
- 중간에 벡터[366]을 접근할 수 있다(while문 i++가 되면서) \ 이때 **지정 안한 공간에서 0이 아닌 엄청 큰 수가 나온다.** - 사실 지정 안 한 공간을 접근하는 것 자체가 문제긴 함
- 벡터[366] = 0으로 해두던가 아님 while(days[i] > 0 && i <366) { <- 이렇게 해줌으로써 해당 상황을 방지할 수 있다.
난 아직 c++이 미흡한 듯.. 헤헷
- 풀이방법
- 등장하는 날짜를 카운트배열로 채웠다 (1-2일 days[1]++; days[2]++;)
- 일정이 겹치면 카운트배열은 증가한다.
- 0이 되기 전까지의 배열의 수(dayCnt) * 카운트배열 속 일정이 제일 많이 겹친 날(maxSchedule) 을 더해가면서  다 끝나면 최종값을 반환하면 된다.
=> Solved: [구현] BOJ_달력 홍지우

구현/나영/BOJ_16719_zoac.java
- 배열
- 구현
- find(0) 에서 0 ~ charn.length 까지 돌며 가장 사전순으로 앞에 있는 문자를 찾음 : O(N)
- visited 배열울 돌며 TRUE 인 값 출력 : O(N)
- find(index)로 가장 사전순 앞의 문자 인덱스를 기준으로 다시 시작
- find(index)에서 index ~ charn.length 까지 돌며,,, : O(N)
- 위 작업을 N번 반복
- 그래서 최종 시간복잡도는 O(N) * N = O(N^2)
- 진짜 인생 역대급 개막장구현
- 인덱스 0을 기준으로 charn 배열을 한 번 돌며 가장 작은 사전 순 문자를 찾고, visited 처리 후 find(index)로 해당 위치부터 charn 배열 끝까지 도는 로직을 설계
- 이 때 if (cnt >= charn.length - n) break; 해당 구문으로 index부터 문자열 마지막까지 전부 visited 되었다면 이제 이 인덱스부터는 탐색하지 않아도 됨. break 시킴
- 근데 여기서,, 예를 들어서 zoac의 경우 출력값이
```
A
AC
OAC
OAC
ZOAC
```
- 이렇게 나옴. 이유는 A에서 가질 수 있는 모든 문자열을 append 하면 다시 find(0)으로 돌아감. 이 때 O가 가장 사전 순 앞 글자이므로 visited 처리한 뒤 sb2에 append 하고, find(O의 인덱스) 재귀를 탐.
- 이 때 O는 이미 추가되었고, 그 다음 문자열들도 이미 다 visited 되었는데 find 재귀를 한 번 더 타면서 동일 결과가 출력됨
- 이를 방지하기 위해 if (tmp > 'Z') …
=> Solved: [구현] BOJ_zoac 김나영

구현/나영/BOJ_18311_왕복.java
- 배열
- 구현
- O(n + k)
- n번 입력받고, 최대 k번 반복하여 남아있는 거리를 계산함(모든 arr의 인자가 1일 경우)
- 이해가 안 되는 점
- 왜 k를 long 타입으로 바꾸니까 통과하는가,, => 알고 보니 k의 범위가 n(최대 100,000) * 50,000 = 5,000,000,000 즉 50억까지 갈 수 있다,,ㄷㄷ 문제 잘 읽자
- 3과 4 사이에 딱 도착했을 때, 즉 코스 3이 딱 끝나는 지점에서 다음 코스가 현재 내 코스임을 모르고 짰음. 헤헷
- 그냥 cnt로 계속 인덱스 돌면서 k의 각 코스의 거리를 빼다가 0보다 작아지는 시점의 인덱스 쪽 코스가 정답임.
=> Solved: [구현] BOJ_왕복 김나영

구현/지우/BOJ_18311_왕복.cpp
- 벡터
- 구현
왕복은 최대 2N-1번 이동하며 각 칸마다 O(1) 연산 수행
최악의 경우 K가 매우 커도 각 칸에서 K를 줄이므로, 총 시간은 O(N)
전체 시간복잡도는 O(N), 공간복잡도는 O(N) (입력 배열 저장용)
- 1차 풀이) K가 왕복이 가능할만큼 크다는 것을 간과하고 모든 거리마다 트랙 정보를 저장한 배열로 두고 풀려 했다.
- 런타임에러 왜? K-(총 수-K) 하려고 했는데 이때 음수가 나오고 벡터[음수]로 접근할 가능성이 있음
- 일단 안됨 -> 벡터 공간을 누적된 길이만큼 할당하는게 애초에 불가능하다..
- 2차 풀이) K에서 트랙의 길이만큼 빼가면서 해당 트랙을 지났을 때 '음수'가 되면 해당 트랙을 cout 한다.
- isReturn bool변수를 관리하며 갈 때는 idx(트랙 몇 번째)++, 올 때는 idx-- 를 한다.
=> Solved: [구현] BOJ_왕복 홍지우

구현/지우/BOJ_1316_그룹 단어 체커.cpp
- set
- 구현
- 문자열 하나당 최대 길이 L만큼 순회하며 set 삽입/탐색 (O(L log L))
- 총 N개의 문자열에 대해 반복하므로, 전체 시간복잡도는 O(N * L log L)
- 만약 그룹 단어가 아니라면 중간에 return 시켜야 하므로 메서드로 구현함
- 이전 단어와 다르다! <- 새로운 단어 OR 그룹 단어 깨는 단어
- set에 원래 있던 친구? 그룹 단어 깨졌다! return(cnt에 추가 안됨)
- set에 없었음? 새로운 단어다! set에 넣어주자!!
- 다 풀어놓고 cnt 위치, set 위치 잘못 넣어두고 으잉 뭐지? 함 .. (제 발..)
=> Solved: [구현] BOJ_그룹 단어 체커 홍지우

구현/나영/BOJ_1316_그룹 단어 체커.java
- 배열
- Set
- 구현
- 단어가 n번 반복 * charn 배열 안의 문자열 탐색
- 이 때, 같은 문자이면 j++로 패스하므로 사실상 **한 문자당 한 번씩만 탐색함**
- 근데 나 너무 같은 방식으로만 푸는 듯,, 맨날 while 문 때리는 거 같다. 이건 overdoes.
- 그래서 받은 문자열을 한 번 돌면서 새로운 알파벳 나타나면 list에 저장해 한 알파벳 당 한 번만 저장한 뒤 돌릴까 했는데 그럼 문자열 한 번 돌고 또 list도 도는 거라 의미가 없다고 판단했음.
- 그래서 charn 배열을 돌면서 새로운 알파벳이 나타나면 set에 contains 되었는지 확인 후 없으면 add하고 새로운 알파벳이 나오기 전까지 j++함.
- 심플한 문제인데 다른 사람이 어떤 방식으로 푸는 지 보는 게 좋을 듯
=> Solved : [구현] BOJ_그룹 단어 체커 김나영

그래프 탐색/지우/BOJ_1260_DFS와BFS.cpp
- 벡터
- 큐(BFS용)
- 그래프탐색(DFS, BFS)
- **그래프 입력 및 정렬:**
O(M + N log N)
(정점별 인접 리스트 정렬 포함)
- **DFS 및 BFS 탐색:**
각각 O(N + M)
(정점과 간선을 한 번씩 방문)
- **총 시간복잡도:**
O(N + M + N log N)
(정렬 포함 전체 시간)
-  방문할 수 있는 정점이 여러 개인 경우에는 정점 번호가 작은 것을 먼저 방문
- 각 정점에 대한 인접리스트를 sort해서 사용함 
- DFS
- for문을 돌리면 어차피 끝이 있기 때문에 기저조건을 달아주지 않아도 된다.
- 이 문제의 경우, 가장 '첫' 답을 인출하면 됐기 때문에 visDfs[] = false로 문을 닫진 않았다. 
- DFS는 늘 전역변수를 바로 활용할 수 있다. 다음 친구를 바로 true로 처리하고 답에 연결했다.
- BFS
-  늘 푸는 공식대로 풀었음
=> Solved: [그래프 탐색] BOJ_DFS와 BFS 홍지우

구현/지우/BOJ_17128_소가 정보섬에 올라온 이유.cpp
- 벡터
- 구현
- 초기 사전 계산 (mulnSum, sumAll)은 O(N)
- 각 쿼리는 최대 4개의 범위만 수정 → O(1)
- 총 시간복잡도는 **O(N + Q)**로, N, Q ≤ 200,000에서도 시간초과 없음 ✅
- 시간복잡도 계산을 잘해야 하는 문제였다. Q번 input 들어오며 N번을 돌기만 해도 20만*20만 <- 2초여도 부족
- 조회 및 계산의 시간복잡도를 낮출 수 있도록 변수와 벡터(리스트)를 적극 활용했다.
- 벡터
- 범위별(시작지점 인덱스에 둠) - 곱한 값을 넣어둔다 `scopes[시작점] = 연속4칸의곱`
- 번호별 - 각 어떤 범위에 있는지 넣어둔다 `whatScopes[소 지점] = {1,2,7,8} `
- 변수: total
- 총 값을 구한 뒤, 4번 (whatScopes에 들어있는 범위의 값)을 빼고, *(-1)을 해서 다시 더해주면 된다.
=> Solved: [구현] BOJ_소가 정보섬에 올라온 이유 홍지우

그래프 탐색/지우/BOJ_11725_트리의 부모 찾기.cpp
- 벡터(리스트)
- 큐
- 그래프탐색(BFS)
- 간선 입력은 N-1번으로 O(N)
- BFS 순회는 각 노드를 한 번씩 방문하므로 O(N)
- 전체 시간복잡도는 O(N)
- **`트리의 루트 = bfs의 시작점`** 라는 아이디어 필요
- 양방향 리스트로 저장해도, 시작점 먼저 타기 시작하면 결국 방문하는 건 단방향이 되면서 부모->자식 흐름이 가능해짐
- q에 먼저 들어간 것이 부모(par), 아직 방문하지 않고 부모(par)의 인접리스트에 있는 것이 자식(child) ◀️ `p[Child] = par` 로 반영해주기
=> Solved: [그래프 탐색] BOJ_트리의 부모 찾기 홍지우

그래프 탐색/지우/BOJ_14940_쉬운 최단거리.cpp
- 벡터
- 큐
- 그래프탐색
- bfs
- **2차원 배열에서 bfs 한 번당 O(N*M)**
- bfs(tr, tc)는 단일 BFS로 모든 칸을 최대 한 번씩 방문 → O(n × m)
- main()에서 입력 처리 및 출력 포함한 나머지 연산도 O(n × m)
- 처음에 2차원배열 bfs() 시간복잡도를 1000^2 일거라고 생각하지 못하고 품
- 모든 정점을 방문하면서 타겟까지 bfs() 돌림 <- 1000^4 되면 당연히 시간초과
- 시초 보자마자 떠올림 -> dp[][] 즉, dist 배열에 저장하면서 나아가야겠다..
- 우선 dp[][] 초기값을 -1로 둔다 (왜? 타겟에서 출발한 bfs가 못 도달하면 -1로 그대로 남아있어야 하기 때문)
- 타겟일 때, 0 일 때는 무조건 dp[][] 가 0일 수 밖에 없다 <- 갱신이 필요하지 않으니 미리 `dp[][] = 0; `으로 세팅해준다.
- 시작점을 타겟으로 하여 상,하,좌,우를 n*m 박스 안에서 계속 돌리며 `dp[][]==-1` <- 즉, visited되지 않은 곳을 찾아 타겟부터 해당 지점까지의 거리를 넣어준다.
=> Solved: [그래프 탐색] BOJ_쉬운 최단거리 홍지우

구현/지우/BOJ_22859_HTML 파싱.cpp
- 덱
- string
- 구현
- HTML 문서 전체 길이가 최대 1,000,000이므로 input.length()는 최대 1백만입니다.
- 첫 번째 while문에서는 각 문자마다 한 번씩만 탐색하고, <...> 또는 일반 텍스트 단위를 deque에 저장하므로 O(N).
- 두 번째 while문에서도 deque에서 각 요소를 한 번씩만 처리하므로 전체 시간복잡도는 **O(N)**입니다.
- 공백을 포함한 한 줄을 그대로 받는 법: `getline(cin, 변수명)`
- 한 번에 돌아가서.. 넘 후 감 격 스 러 워 요.. (그치만.. 코드가 좀 더러워용.. 헤헤ㅔ)
- 1번째 while문: 덱에 `[ <main> | <div title=" "> | <p> | paragraph 2 | <i> | Italic Tag | </i> | <br > | </p> ,,,] `이런식으로 넣는다
- 2번째 While문: 
-  / 닫힌 건 무시한다. (main, div의 닫힘 태그) + main도 무시
- div 여는 태그: " " 안에 있는 글자만 뽑아서 출력한다.
- p 태그 안: 다른 태그(i br),쌩글자 둘 중 하나가 있다. 이때, 쌩글자만 tmp에 모아서 출력할 준비
- 2가지 조건(시작 끝 공백 ❌  + 2 공백 연속 ❌ ) 만족하게끔 For문 검사
=> Solved: [구현] BOJ_HTML 파싱 홍지우

그래프 탐색/지우/BOJ_2667_단지번호붙이기.cpp
- 벡터
- 큐
- 그래프탐색 - BFS
- 입력 및 2중 for문 전체 탐색 → O(N²)
- BFS에서 각 칸은 한 번만 방문 → 전체 BFS 시간도 O(N²)
- 정렬(sort)은 O(K log K) (K는 단지 수, 최대 N² 이하)
- counts[currNum]에 cnt 담으려고 했더니 이러면 공간 다 만들어줘야 하잖아.? <- 그냥 인덱스는 안 중요하니까 counts.push_back(cnt)만 해도 되네~
- vis 안 씀. 지나간 곳은 2이상의 currNum으로 채워줌. (같은 집단끼리는 같은 숫자가 채워지게끔) 
- 주변에 1이 있으면 가서 currNum으로 바꿔주기
- 전체 체크할 때도 1인 곳만 가서 섬 탐색 시작하기
=> Solved: [그래프 탐색] BOJ_단지번호붙이기 홍지우

그래프 탐색/지우/BOJ_7576_토마토/토마토(ver.bfs).cpp, 그래프 탐색/지우/BOJ_7576_토마토/토마토(ver.dfs_시초).cpp
- 벡터
- 큐
- 그래프탐색(BFS)
- DFS _ 시간초과
---
이렇게 동시에 여러 군데로 퍼져나가는 문제는 BFS를 '먼저' 떠오르는 버릇을 들이자.
1. 큐에 들어간 각 칸은 최대 1번만 방문됨 → O(N*M)
2. 각 칸마다 상하좌우 4방향 확인 → 4 * O(N*M)
3. 전체 시간복잡도는 **O(N*M)** 으로 매우 효율적
1. 매 단계마다 전체 맵을 2중 for문으로 탐색 → O(N*M)
2. 각 재귀마다 새로 방문배열 초기화 + 깊이탐색 → 최대 N*M번 재귀
3. 전체 시간복잡도는 **O((N*M)^2)** 이상 → **TLE 발생**
---
- BFS, DFS 어떤 문제에 쓸지 잘 생각하고 들어가자. 쩨발!!
- 큐에 넣을 친구가 들어온다 -> 큐에 바로 넣는다 : 이렇겐 처음 풀어봤다..
- 큐에 남은 애들 = 익은 토마토 
- 큐가 empty 될 때까지 -> 익은 토마토가 미치는 영향이 없어질 때까지
- vis 안 쓰고 걸린 시간 dp 맵도 안 쓰고 풀어봤음
- 그대신 maps에 익은 애들을 [이전+1]로 쌓아가며 시간 관련 숫자들로 채웠음 (그럼 '0'인 곳만 찾아서 가니 어차피 vis 역할을 함)
- 익은 애들의 영향 -> 다음 map `안 익 -> 익` 할 때, `이전 익은` 애+1 하면? 거기까지 가는데 걸린 시간+1
- 초기 익은 애: map[][] = 1
- 얘 때문에 다음에 익힌 애: map[][] = 이전+1 = 2 (즉, 여기까지 걸린 시간이 저장된다. 근데 시작이 1이라서 나중에 1 빼줘야 함)
=> Solved: [그래프 탐색] BOJ_토마토1 홍지우

그래프 탐색/지우/BOJ_2668_숫자고르기/숫자고르기(ver.dfs).cpp, 그래프 탐색/지우/BOJ_2668_숫자고르기/숫자고르기(ver.조합-시초).cpp
- 벡터
- set(dfs의 경우)
- 그래프탐색(DFS)
- 조합으로 풀었더니 시초 엔딩 코히히
---
1. 각 노드에서 한 번씩 DFS 수행 → O(N)
2. DFS 안에서 순환 탐색은 최대 O(N)
3. 전체 시간복잡도는 **O(N^2)** → N ≤ 100 이면 충분히 통과 가능
1. 크기가 1~N인 조합을 모두 생성 → O(2^N)
2. 각 조합마다 `check()` 함수에서 집합 비교 → O(N log N)
3. 전체 시간복잡도는 **O(2^N × N)** → N = 100일 때는 **절대 불가능**
1. 가능한 모든 조합을 만들고 확인하려고 하므로 경우의 수가 **지수적으로 증가 (2^N)**  
2. 그 중에서도 정답이 후반부에 있어야만 멈추므로 대부분의 경우 **모든 조합을 탐색**
3. DFS 방식은 "사이클 여부만 확인"하므로 선형으로 동작, 조합은 불필요하게 낭비적인 탐색 
---
- 솔직히.. 진짜.. 어려웠다.. 조합으로 풀고 그 방식대로 dfs로 넘어가는게 불가능했다.
- 루프 도는 경로로 따라서 리스트로 저장하고 마지막에 ans에 다 넣어주면 굳이 한 번 더 안 돌겠지 생각했었다.
- 이때 vis 관리하는게 복잡해지면서 로직이 꼬였다.
- dfs 호출의 경로, 이전의 다른 dfs 호출에서 이미 탐색이 끝난 친구 vis를 따로 관리해야 했는데 정답을 발견했을 때의 처리가 어려웠다.(`for (int i = next; i != curr; i = arr[i])` { <- 이게 대체 뭐람..) 그래서 그냥 풀이법 바꿨다.
- 푼 방법: 그냥 간단하게 생각하는게 더 옳은 길
- 루프는 …
=> Solved: [그래프 탐색] BOJ_숫자고르기 홍지우

그래프 탐색/나영/BOJ_2573_빙산.java
- Queue
- 배열
- 그래프 탐색
- BFS
- DFS
- 빙산의 최대 높이만큼 녹음 => O(H)
- 빙산의 갯수만큼 BFS, DFS 탐색 => O(I)
- 로직 시간복잡도 : O(H * I)
- 빙산의 최대 높이는 10, 빙산의 최대 갯수는 10,000개
- 빙산이 녹으면 map에 0으로 반영하는데, 다음 빙산으로 넘어갈 때 바다인 부분이 해당 년도에 녹은 빙산의 위치인지를 확인해야 헀다
- 그래서 wasIce 배열을 통해 해당 년도에 빙산이 녹을 경우 그 위치에 true 처리해 빙산이었는지 아닌지 확인
- 그리고 find 메서드에서 dfs()를 남은 빙산 개수만큼 돌려 빙산이 2개 이상 분해되었는지 확인
=> Solved: [그래프 탐색] BOJ_빙산 김나영

그래프 탐색/나영/BOJ_16973_직사각형 탈출.java
- Queue 
- 배열 
- 그래프 탐색 (근데 이제 거의 구현인)
- BFS 
- find로 한 번 검사할 때 상/하, 좌/우 테두리만 범위 내이고 벽이 존재하는지 확인 => O(max(h, w))
- bfs()로 4번 탐색
- 이 연산을 최대 O(n * m)만큼 반복
- 최종 시간복잡도 : O(n * m * max(h, w))
- 그냥 구현을 푼 기분
- find 함수 내부에서 nr, nc를 선언하려고 했는데, 그럼 나중에 que에 넣을 때 어려워져서 그냥 for문으로 4방탐색 할 때 nr, nc를 선언하고 넘겨줬다
- 그리고 find 함수에서 d, nr, nc를 받으면 옮길 사각형의 최소/최대 꼭짓점 값의 범위를 check()로 확인하고 d의 값에 따라 상/하/좌/우  확인 => 해당 부분의 테두리만 범위/벽 확인했습니다
=> Solved: [그래프 탐색] BOJ_직사각형 탈출 김나영

그래프 탐색/나영/BOJ_16234_인구 탐색.java
- Queue
- 배열
- List
- 그래프 탐색
- BFS
- 날짜는 최대 2000까지 나올 수 있음 => while문이 최대 2001까지 반복
- bfs() 메서드는 전체 n^2의 모든 좌표를 방문하며 연합이 존재하는지 확인 : O(n^2)
- 4방 탐색의 경우 상수이므로 제외
- 최종 시간복잡도 : O(2000 * n^2)
- 처음엔 visited2 배열, dfs() 메서드를 추가해 bfs 돌고 난 뒤의 연합국의 값을 전체 합의 평균으로 바꿔주려고 했음
```
static void dfs(int r, int c, int avg) {
        map[r][c] = avg;
        visited2[r][c] = true;
        for (int d = 0; d < 4; d++) {
            int nr = r + dr[d];
            int nc = c + dc[d];
            if (check(nr, nc) && visited[nr][nc] && !visited2[nr][nc]) {
                dfs(nr, nc, avg);
            }
        }
    }
```
- 그런데 visited 배열은 bfs 시 방문한 나라를 표시해주는 것이고, 날짜가 지날 때에만 초기화된다.
-  이렇게 돌리면 다음 연합국을 찾고 해당 연합국의 값을 dfs로 변경할 때 연결되지 않았지만 이전에 방문한 타 연합국의 수도 바뀔 수 있었다(내가 int 배열로 1, 2 이렇게 연합국을 표시한 게 아니라 그냥 boolean으로 방문했는지 …
=> Solved: [그래프 탐색] BOJ_인구 이동 김나영

그래프 탐색/지우/BOJ_16973_직사각형 탈출.cpp
- 그래프탐색(BFS)
- 누적합
- 누적합 배열 계산: O(N × M) — 전체 지도에 대해 prefix sum을 미리 계산
- BFS 탐색: 각 칸 최대 한 번 방문하므로 O(N × M)
- possible 함수: 누적합을 이용해 직사각형 내 벽 유무를 O(1)에 판단하므로 BFS 내에서도 전체 시간은 O(N × M)
- possible 함수 시간복잡도 최적화 하느라 죽는 줄 ..
- 이게 범위 H,W 내로 돌면서 == 1 인지 체크하면 거의 N*M 만큼 돌아오는 칸 안에서 4방탐색할 때 H*W 를 다 돌아야 하니까 시간이 터졌다.
- SOLVED: 누적합을 저장하여 r,c까지 오는데 벽이 몇 개 있었는지 더해서 prefix 배열에 저장한다.
- possible 안에서 `가장 끝 벽 누적값 - HW범위 미포함 누적값`을 빼서 벽의 개수를 본다. 그 값이 0이면 거긴 벽이 없는 것
- 나머진 sr,sc부터 시작하는 무난한 BFS 문제로 풀었다.
=> Solved: [그래프 탐색] BOJ_직사각형 탈출 홍지우

그래프 탐색/지우/BOJ_1967_트리의 지름.cpp
- vector
- 그래프탐색(DFS)
- DFS는 트리의 모든 정점을 1번씩 방문 → DFS 한 번당 시간복잡도는 O(n)
- DFS를 2번 실행하므로 총 시간복잡도는 O(2n) = O(n)
- 입력 처리와 인접 리스트 생성도 O(n) → 전체 알고리즘은 O(n)
- 무방향은 곧 양방향이다
- 1부터 가장 깊고 모인 가중치가 제일 큰 애가 주인공이다
- 그 주인공으로부터 인접리스트를 따라 더이상 갈 수 없는 끝지점에 도달하는 dfs를 돌린다. 그 중 sum이 가장 큰 친구를 채택한다.
=> Solved: [그래프 탐색] BOJ_트리의 지름 홍지우

그래프 탐색/나영/BOJ_14502_연구소.java
- Queue
- 배열
- 그래프 탐색
- DFS
- BFS
- 벽을 세우는 경우의 수
- 바이러스를 퍼뜨릴 때 시간복잡도 : O(n * m)
- 벽을 세우는 경우의 수 * 바이러스를 퍼뜨리기 : O(K^3 * n * m)
- 이 문제를 두 번이나 풀었음에도,, dfs 시 r과 c 관리를 제대로 하지 못함;
- 풀고 나서 gpt에게 물어봤는데, 
```
for (int i = idx; i < n * m; i++) {
int r = i / m;
int c = i % m;
}
```
- 이렇게 인덱스 관리를 하는 방법도 있다.
- 난 걍 nr == r일 때 c가 nc보다 작은 지만 확인했다 => 작거나 같은지로 확인했다가 틀림,, 왜냐? 그럼 map[r][c]는 단 한번도 컨펌받지 못하고 continue 되기 때문,, 불쌍한 map[r][c] ㅠㅠ
- dfs로 벽을 3개 세우는 모든 경우의 수를 구한다
- 그렇게 벽을 총 3개 세우면 bfs로 바이러스 활동시키고 0의 개수를 구해 max값에 반영했습니다
=> Solved: [그래프 탐색] BOJ_연구소 김나영

그래프 탐색/나영/BOJ_2636_치즈.java
- Queue
- 배열
- 그래프 탐색
- BFS
- DFS
- BFS : 최악의 경우 모든 칸을 한 번씩 탐색 => O(n * m)
- DFS: 모든 칸 탐색하며 치즈의 개수를 구함 => O(n * m)
- days : n*m이 최악이지만, 앵간하면 n/2, n/3의 범위에서 끝날 듯
- 최종 시간복잡도 : O(n * m * days)
- 치즈가 감싸진 빈 공간은 접근하면 안되므로, BFS 시 1을 만나면 방문 처리하고 0으로 바꿔줬습니다.
- 그리고 0이며, 방문하지 않았으면 que에 넣습니당
- 치즈를 다 녹이면 before에 이전 치즈의 범위를 저장하고, DFS로 치즈의 범위를 확인합니다.
- 치즈 맵 받을 때 cnt 초기화 안 해주면 95%에서 틀림
- 그리고 cnt 0이면 치즈 다 녹은 거니까 break~~
=> Solved: [그래프 탐색] BOJ_치즈 김나영

그래프 탐색/나영/BOJ_4179_불!.java
- Queue
- 배열
- 그래프 탐색
- BFS
- BFS : 
- 지훈이가 이동 => 최대 O(n * m)
- 불이 이동 => 최대 O(n * m)
- que의 사이즈만큼 루프를 돌지만, 결국 모든 칸을 한 번만 방문하기 때문에 따로 더 곱할 수는 없다.
- 최종 시간복잡도 : **O(n * m)**
- 처음엔 지훈이가 먼저 이동하고 불을 이동하려고 했는데, 그렇게 하면 지훈이가 테두리에 도착하는 타이밍을 잡기가 어려웠다
- que1에서 빼면서 하나씩 가장자리인지 확인하려고 했는데 지훈이가 먼저 이동하고 que1에 넣고, 그 이후에 불이 이동하니까 que1엔 사망한 지훈이가 반영되지 않음
- 그래서 불을 먼저 이동하고 지훈이를 이동시켰다. 그럼 불이 먼저 붙은 자리에 지훈이가 가지 못하므로 올바른 자리를 찾아간다.
=> Solved: [그래프 탐색] BOJ_불! 김나영

그래프 탐색/지우/BOJ_4179_불!.cpp
- 그래프탐색(BFS)
- spreadFire()는 불이 퍼질 수 있는 모든 칸을 BFS로 탐색 → O(R × C)
- escape()는 지훈이의 모든 이동 경로를 BFS로 탐색 → O(R × C)
- 입력 처리 및 그 외 로직도 대부분 O(R × C) → 전체 시간복잡도는 O(R × C)
- 불 처리 후 J 처리하는 DFS로 태울까 했는데 시초 엔딩일 것 같아서 선회함
- fireDP
- 불이 도달하는 시점을 저장하는 저장소
- 불이 도달하지 않은 곳은 INF로 채우기. 불 시작점 0(0초부터 거기였으니까). BFS를 돌리면서 다음 불의 장소(이전 장소 시간 +1) 
- 불 방문x는 INF/ 불이 닿은 곳은(nr) dp[r]+1 / 닿을 곳은 dp[r]+1 보다 큰 곳이면 아직 불 안 닿은 곳이므로 가서 차지해준다.
➡️ 이러면 fireDP에는 불이 도착한 시간이 다 저장되어 있다.
여기 베이스에서 
- escape() 메소드 : J가 도달한 시점은 '불이 도달한 시점보다 더 작아야 함'
- 조건을 달고 그에 충족되는 위치만 q에 넣고 돌리면
- 결국 Q에 남아서 가장자리에 도착하는 아이는 탈출한 친구이다.
=> Solved: [그래프 탐색] BOJ_불! 홍지우

그래프 탐색/나영/BOJ_1600_말이 되고픈 원숭이.java
- Queue
- 배열
- 그래프 탐색
- BFS
- BFS로 최대 모든 칸을 탐색 : O(w * h)
- 이 때, 한 칸을 horse만큼 접근할 수 있음
- 그러므로 최종 시간복잡도는 **O(horse * w * h)**
- 작년에 푼 말되원 죽지도 않고 또 왔네
- 그때는 애먹었지만 이젠 3차원 배열이란 것을 알지 후후
- visited를 3차원 boolean 배열로 설정해 horse의 개수에 따른 각 칸의 방문 여부를 따로 체크
- 어차피 4방탐색은 horse가 없어도 실행 가능하므로, 언제나 실행시키고 말의 움직임만 horse >0인지 확인
- 인류는 3개의 배열을 사용할 수 있어야 한다
=> Solved: [그래프 탐색] BOJ_말이 되고픈 원숭이 김나영

백트래킹/지우/BOJ_15657_N과 M (8).cpp
- 벡터
- 백트래킹
- 순열
- 깊이가 M, 각 깊이마다 선택지는 최대 N개 → O(N^M)
- dfs(i, sIdx+1) 호출로 인해 중복 허용 없이 비내림차순 조합 탐색
- 따라서 전체 시간복잡도는 **O(조합 수 * M) = O( (N+M-1)C(M) * M )**에 가까움 (출력 포함)
- (4) 와 같은 문제
- 이전에 가져온 수부터 N까지 담으면서 업데이트
=> Solved: [백트래킹] BOJ_N과 M (8) 홍지우

그래프 탐색/나영/BOJ_9466_텀 프로젝트.java
- 배열
- 그래프 탐색
- DFS
- DFS : 모든 칸을 최대 한 번만 탐색하므로 **O(n)**
- 이전 문제와 비슷하게 사이클을 찾아야 하지만, 시간 최적화가 필요한 문제였다
- 그래서 dfs 시 **방문했지만 end 처리되지 않은 노드**를 발견하면 해당 노드에 사이클이 존재한다는 의미이므로 for문을 통해 뒤로 추적하면서 사이클 탐색
- 이전 코드는 visited를 모든 dfs마다 초기화했는데, 그렇게 하니 터져서 visited를 초기화하지 않는 방법으로 진행했습니다.
=> Solved: [그래프 탐색] BOJ_텀 프로젝트 김나영

백트래킹/나영/BOJ_14888_연산자 끼워넣기.java
- 배열
- 백트래킹
- 순열
- 연산자 개수에 제한이 없다면 O(4^n-1)
- 하지만 연산자의 개수가 지정되어 있으므로 최종 시간복잡도는 
- 중복순열을 이용해서 연산자를 추출하는 문제
- 숫자는 순서를 무조건 지켜야 하므로 그대로 두고, 부호에 대해서만 dfs 돌려 갯수가 0이 아니라면 추출시켰다
- 다시 생각해보니 pre를 이용해 동일한 부호에 대한 중복값을 제거했다면 더 최적화되었을 것 같다 헤헷
=> Solved: [백트래킹] BOJ_연산자 끼워넣기 김나영

그래프 탐색/나영/BOJ_22946_원 이동하기 1.java
- 배열
- 그래프 탐색
- DFS
- 원 sort : O(n log n)
- connect(i) : 최악의 경우 모든 쌍의 원을 비교 -> **O(n^2)**
- dfs : 최악의 경우 모든 정점 탐색 -> **O(n^2)**
- 최종 시간복잡도 : **O(n^2)**
- 죽고싶었다
- 원을 반지름 기준으로 sorting해 포함 관계의 순서를 유지하도록 함
- 그리고 각 원마다 connect로 모든 원에 대해 포함관계인지를 확인(만약 하나라도 자신을 포함하고 있다면 return)
- 이 때 포함관계인지는 find로 확인했는데, 이것이 long 타입으로 변환해주지 않으면 부동소수점 문제로 잘못된 값이 나올 수 있다고 함... 모든 걸 정수로 판단해야 했던 거임;
- 그래서 바꿔주고, dfs로 저장한 간선을 탐색하며 가장 많이 이동할 수 있는 값을 찾았더니 pass
=> Solved: [그래프 탐색] BOJ_원 이동하기 1 김나영

그래프 탐색/지우/BOJ_16932_모양 만들기.cpp
- 벡터, 큐, 셋
- 그래프탐색(BFS)
- 처음 N × M 격자를 한 번씩 탐색하여 BFS로 각 그룹을 나누고 크기 계산 → O(N × M)
- 각 칸에 대해 상하좌우 인접한 그룹의 크기를 더함 → 매 칸마다 최대 4번의 인접 체크로 O(N × M)
- 전체 시간복잡도는 O(N × M)
업데이트를 계속 할 필요는 없으니까 모든 정보가 저장된 배열을 활용했다.
1. 초기 map에서 bfs() 돌리기
- groupNames[][] 에 같은 그룹이면 같은 그룹 name을 갖도록 한다.
- groupSizes[][] 에 총 그룹의 사이즈를 넣는다.
2. 정방향 순회하면서 0 인 부분을 발견하면 4방탐색한다.
- 각 0 칸 에서의 인접한 칸들의 groupSizes[][]를 다 더한다. (근데 다 다른 그룹에 속한 애들의 size여야 함. - 그래서 set씀_이미 방문한 GroupName은 안되게끔!!!)
=> Solved: [그래프 탐색] BOJ_모양 만들기 홍지우

백트래킹/지우/BOJ_15665_N과 M (11).cpp
- 벡터
- 중복을 제거한 순열(중복 허용 안함, 방문 체크 없음)
1. 중복 숫자가 없으면 총 경우의 수는 O(N^M) (중복 가능하므로)
2. 하지만 `pre == nums[i]` 조건으로 **같은 깊이에서 같은 숫자 사용 방지 → 중복 제거**
3. 따라서 실제 시간복잡도는 **중복 제거된 N^M 이하**, 정확히는 **중복 없는 중복순열**
- 각 자리에서 처음부터 ~ 끝까지 올 수 있는 상황
- 여기서도 중복된 결과는 나오면 안됨
- 같은 깊이의 숫자를 저장하여 같은 깊이, 같은 숫자에서 2번 타지 않도록 한다.
=> Solved: [백트래킹] BOJ_N과 M (11) 홍지우

백트래킹/나영/BOJ_1182_부분수열의 합.java
- 배열
- 백트래킹
- 각 원소에 대한 모든 부분집합을 추출
- 각 원소들은 선택할지, 안 할지 두 가지 선택지가 생김
- 최종 시간복잡도 : **O(2^n)**
- 부분집합을 전부 선택하는,,데 공집합은 빼야 했던 문제
- 그래서 return 조건에서 start가 0인 경우는 공집합이므로 제외했고, 그 외애는 sum이 s와 같을 경우 ans를 더해주었다.
=> Solved: [백트래킹] BOJ_부분수열의 합 김나영

백트래킹/나영/BOJ_15664_N과 M (10).java
- 배열
- 백트래킹
- 중복 없이 조합을 뽑아야 함
- nCm
- 최종 시간복잡도
- prev를 사용하면서, start를 dfs에 파라미터로 보내 시작점과 같거나 이전 값으로는 접근하지 못하게 했다
=> Solved: [백트래킹] BOJ_N과 M (10) 김나영

백트래킹/나영/BOJ_15666_N과 M (12)_3.java
- 배열
- 백트래킹
- 중복 허용 조합을 추출하는 문제
- n + m - 1 C m 
- 최종 시간복잡도
- prev를 이용하면서 중복 허용 조합을 추출하는 문제
- dfs에 start 값을 넘길 때 i+1이 아닌 i값을 넘겨 자기 자신도 선택할 수 있게 했다
=> Solved: [백트래킹] BOJ_N과 M (12)_3 김나영

백트래킹/지우/BOJ_14712_넴모넴모 (Easy).cpp
- 벡터
- 백트래킹
1. **최악의 경우**: 모든 칸마다 놓을지/안놓을지 두 가지 경우를 재귀로 탐색 → \(O(2^{N x M})\)  
2. **가지치기 효과**: `if(maps[r-1][c] && maps[r][c-1] && maps[r-1][c-1])` 조건으로 일부 탐색이 줄어듦 → 실제는 더 작음  
3. **공간복잡도**: `maps`는 \(O(N \times M)\) 크기의 2D 배열, 재귀 호출 스택은 최대 \(O(N \times M)\)  
아이디어 생각하는데 힘들었던 문제
[1차 아이디어]
- 모든 경우의 수 2^{N x M} - 2*2가 가능한 경우의 수 : 이렇게 하려고 했다
- 그러나 2*2를 만족한 네모 외에 다른 빈 칸들도 조합으로 처리를 해줘야 하고, 중복도 빼야 하고.. 뭔가 이 길이 아닌 것 같았다.
[SOLVED]
- (N+1)*(M+1) 판을 만들어두고 2x2를 만족하지 않게끔 dfs를 돌렸다.
- 정방향 순회하며 
- (위, 대각선 위, 왼쪽)이 모두 true이면 절대 현재 위치는 방문하지 않게끔 한다. // 2x2 만들어지기 직전이니까!!!
- 그냥 idx+1 해서 다음으로 넘기기
-  그게 아니면 방문한다! 다음! dfs(+1) / 방문 안 한다! 다음! dfs(+1)
- 예전에 썼던 int r = idx / 열 , int c = idx / 행; 아이디어 사용했다.
=> Solved: [백트래킹] BOJ_넴모넴모 (Easy) 홍지우

백트래킹/지우/BOJ_2661_좋은수열.cpp
- String
- 백트래킹
1. 깊이 N까지의 DFS를 수행하며, 각 단계에서 최대 3개의 숫자를 시도하므로 기본 경우의 수는 3^N  
2. 매 단계에서 새로운 숫자를 붙일 때, 길이의 절반까지(최대 N/2) 부분 문자열 비교를 수행 → O(N)  
3. 최악의 경우 시간복잡도는 O(N * 3^N), 하지만 가지치기로 인해 실제 탐색량은 크게 줄어듦  
- string.substr(시작점, 길이)를 사용했다. 마치 sql 을 푸는 것 같았다.
- 121312 수열을 비교할 때 1↔ 2 | 13 ↔ 12 | 121 ↔ 312 
- for(비교할 사이즈 = 1; 비교할 사이즈 <= 전체길이/2)
- 각 자리에 1,2,3 중 하나씩 넣어보며 좋은수열일 때만 dfs에 넣게끔 풀었다. 따라서 원상복구는 하지 않았다
- 이 절차를 따라 N개의 자리수를 다 만들면 exit(0); 으로 인출. 왜냐? 늘 1부터 채웠으니 이게 제일 작은 값이니까!
=> Solved: [백트래킹] BOJ_좋은수열 홍지우

백트래킹/나영/BOJ_22944_죽음의 비.java
- Queue
- 배열
- 백트래킹
- 그래프 탐색
- BFS : 모든 칸을 체력 * 우산 내구도만큼 돌 수 있음 => O(n^2 * (h + d))
- check(), visited 갱신, 큐 삽입/삭제 :  O(1)
- 최종 시간복잡도 : **O(n^2 (h + d))**
- 백트래킹으로 풀라고 낸 문제 그래프 탐색으로 풀기
- 방문 처리에 대해 고심했는데, 처음엔 우산 개수, 내구도, 체력을 모두 체크하면서 돌려야 하나 했는데 그냥 해당 지점에서 visited의 값이 현재 내 체력 + 우산 내구도보다 작으면 방문할 수 있도록 했으면 됐었다.
- 생각보다 아이디어 문제인 듯,,, 방문 처리를 어떻게 하느냐가 가장 관건이었던 거 같다
=> Solved: [백트래킹] BOJ_죽음의 비 김나영

백트래킹/지우/BOJ_22944_죽음의 비.cpp
- 벡터, 큐
- 백트래킹
- 그래프탐색
1. **최대 정점 수**: `dp`가 2차원 배열이므로, 방문 상태 개수는 최대 `N^2`.
2. **간선 수**: 각 정점에서 최대 4방향으로 이동하므로, 간선 수는 `O(4 * N^2) = O(N^2)`.
3. **총 시간복잡도**: BFS이므로 `O(N^2)`.
**제한 조건 대입 시**  
`N = 500` → 최대 연산 횟수 ≈ 250,000 (충분히 1초 이내 수행 가능)
- 어렵다 .
- 이 문제도 다음으로 넘어갈 때의 조건이 다른 문제이다. 즉, vis 배열을 잘 처리해야 하는 문제 (어떻게 갈 곳, 안 갈 곳을 구별할지가 관건)
- 그러나 map 자체가 바뀌진 않는다. 체력에 따라 갈 수 있는 곳이 달라질 뿐.
➡️ dp[r][c] = 총 체력의 **최댓값**!
- 총 체력 = power(사람 체력) + umb(우산 내구도)
- dp는 갈 수 있는 최대 체력만 갈 수 있다. if(dp[nr][nc] < total) 만 q에 넣어주기
- (**`vis 역할`**) 다녀온 곳은 무조건 현재 체력보다 크니까 다시 돌아가지 않게 된다.
- (**`문제 특수성 반영 vis _ 간 곳도 다시 갈 수 있음`**) 다른 우산 내구도 덕분에 체력이 더 커진 친구도 앞 친구가 다녀간 곳을 방문할 수 있게 된다. 왜? 체력 깡패니까.
- U, . 일 때의 총 체력을 모아 마지막에 판별해서 넣어줄지 말지~ 결정하게끔 코드를 짰다
- [문제 잘 읽자.] U 인 곳을 방문했을 때, 새로 쓴 우산에도 내구도-1 이 진행된다. 
- 예제 3을 보면 E 도착 시 체력 1이 …
=> Solved: [백트래킹] BOJ_죽음의 비 홍지우

백트래킹/지우/BOJ_1799_비숍.cpp
- 벡터
- 백트래킹
1. 흰 칸과 검은 칸을 분리해 각각 DFS 탐색 → 각 경우의 좌표 수를 M_white, M_black이라 하면 탐색 복잡도는 O(2^(M_white) + 2^(M_black)).
2. 각 DFS에서 대각선 방문 여부를 확인하는 데 O(1), 깊이 M에 대해 백트래킹을 수행하므로 최악은 O(2^M).
3. N ≤ 10에서 M_white, M_black ≤ 50이므로 전체 시간복잡도는 실질적으로 O(2^50)보다 훨씬 작아 제한 시간 내 가능.
- 체스의 특성이 시간복잡도를 줄일 수 있었던 key였다
- 흰,검을 반반 나누면 2^50이 되면서 10초 내에 들어올 수 있게 된다. (안 나누면 전체 다 도니까 2^10)
시간복잡도 줄인 방법
1. `1 리스트 활용` : 1의 자리에 넣을지, 안 넣을지만 관리하면 돼서 시간복잡도를 줄일 수 있다.
- 그런데 여기서 더 나아가, **체스의 흰 칸(벡터 whites), 검정칸(벡터 blacks)을 나누어서 관리**해야 했다.
- 비솝은 대각선에만 영향을 미치므로 흰 칸, 검정 칸 끼리는 '독립사건'으로 관리해줘도 된다.
2. \ 방향 대각선 visited[r-c+N-1] , / 방향 대각선 visited[r+c] 활용
- 지난번 배운 대각선 vis 처리 활용했다.
이제 dfs를 흰칸, 혹은 검정칸들의 1에 대한 리스트를 가능하다면 넣을 땐? 뺐을 땐? True,false 백트래킹 해주면 된다.
=> Solved: [백트래킹] BOJ_비숍 홍지우

백트래킹/나영/BOJ_18429_근손실.java
- 배열
- 백트래킹
- 순열
- n개의 숫자에서 n개를 순서 생각하며 뽑음 => nPn = n!
- 최종 시간복잡도 : **O(n!)**
- k가 아니라 4를 넣고 풀어서 한 번 틀림,,, 껄껄
- 순서를 생각하며 뽑아야 하므로 **순열** 문제
- arr에서 하나씩 뽑고, 방문하지 않았거나, sum + arr[i] 가 500보다 큰 곳의 경우 visited 처리한 뒤 cnt == n이면 500보다 큰 지 확인
=> Solved: [백트래킹] BOJ_근손실 김나영

백트래킹/지우/BOJ_18429_근손실.cpp
- 벡터
- 백트래킹
1. DFS 깊이는 N이고, 각 단계에서 최대 N개의 분기가 있으므로 최악의 경우 시간복잡도는 O(N!).  
2. 각 경로마다 K와 kit 값을 사용해 계산하므로 각 호출의 연산은 O(1).  
3. 따라서 전체 시간복잡도는 O(N!)이고, N이 작을 때만 계산이 가능하다.  
1 2 3 4
4 3 2 1 이 다르다고 보는 문제이다.
- vis를 활용하여 0~N까지 kit를 순회
- 만약 이전에 방문하지 않았거나 || kit를 썼을 때 500 밑으로 내려가지 않는다면? => kit 사용할 자격 충분~!
- 방문해서 관련하여 dfs(다음날 kit 쓰자굿!, 키트 적용 후의 다음 중량)
- 원상복구
=> Solved: [백트래킹] BOJ_근손실 홍지우

백트래킹/지우/BOJ_18290_NM과 K (1).cpp
- 벡터
- 백트래킹
1. DFS 깊이는 최대 N×M이고, 각 위치에서 선택/비선택 두 가지 경우를 탐색하므로 최악의 경우 시간복잡도는 O(2^(N×M)).  
2. isAdj 함수는 인접 4칸을 검사하므로 호출당 O(1)의 상수 시간이 추가된다.  
3. 따라서 전체 시간복잡도는 O(2^(N×M))이며, N과 M이 작을 때만 완전탐색이 가능하다.  
- 그냥 시작점을 여러 개 주고 대각선만 보며 나아갈지, 하나하나를 볼지 고민이 있었다. 
- (근데 대각선만 보면 maps가 한 행으로만 이루어졌을 때, 한 칸 건너뛴 다음 칸을 볼 수 없게 된다.)
- 하나씩 Index를 옮기며 현재 r, c를 중심으로 가능 불가능 O, X를 판단했다.
- 만약 현재 r,c 인근 4방향에 vis된 것이 없으면 r,c는 가능!
- r,c 방문체크 + 이거 바탕으로 dfs(다음 인덱스, cnt 하나 올림!, sum+현재 수)
- 원상복구! (조건이 되더라도~ 다음 거가 더 좋을 수 있으니까~)
- (조건 안되는 경우 + 되더라도 다른 경우도 볼 거임) 현재는 선택 안 한 것으로 하고 dfs에 인덱스만 다음 걸로~
- **예외케이스**: 값에 음수도 들어갈 수 있다. ans 초기화를 제일 낮은 수로 해줘야 max(ans, _ )를 올바르게 할 수 있다.
=> Solved: [백트래킹] BOJ_NM과 K (1) 홍지우

그래프 탐색/나영/BOJ_15558_점프 게임.java
- 배열
- 그래프 탐색
- BFS
- BFS : 길이 n의 배열 2개를 탐색 => O(n)
- 최종 시간복잡도 : **O(n)**
- 해당 문제의 핵심은 **시간이 지나면 삭제되는 발판** 과 **리턴** 처리였다
- cnt에 현재 시간을 저장하고, q[2]에 다음 시간을 저장해 que에 넣는다.
- q를 poll 했을 때, 만약 q[2]가 cnt보다 커지면 한 턴을 다 돈 것 => 시간이 지났다는 의미이므로 해당 시간의 발판을 삭제해야 한다.
- 해당 cnt의 발판을 삭제 처리하고, cnt++해 다음 턴을 시작한다.
- 그리고 만약 q[2] == n인 경우 n초 동안 게임이 진행된 것이므로 모든 발판은 삭제 처리된다. 이 때까지 도달하지 못했으면 실패로 봐야 한다.
=> Solved: [그래프 탐색] BOJ_점프 게임 김나영

그래프 탐색/지우/BOJ_18405_경쟁적 전염.cpp
- 벡터, Priority_Queue
- 그래프 탐색
- BFS는 최대 S초 동안 수행되며, 각 초마다 O(N^2)개의 칸을 큐에서 처리 가능
- 각 칸은 최대 한 번만 감염되므로 전체 확산 과정은 O(N^2)
- 총 시간복잡도는 O(N^2 + K log K) (초기 우선순위 큐 정렬 포함)
- `단, 매 초마다 번호가 낮은 종류의 바이러스부터 먼저 증식한다.` => PQ 사용했다.
- S가 0초가 될 때까지 -- 하며 whlie문 돌린다.
- 다음 전염될 pq를 저장하기 위해 pq2를 선언한다.
- pq 모두 털어준다.
- 무조건 낮은 수부터 나오게 된다. 그걸 중심으로 4방향 돌려서 0 이면 전염되게 한다.
- pq2가 이제 털어야 할 차례이니 pq로 옮겨준다. (pq2는 22번 줄에서 다시 초기화 됨)
=> Solved: [그래프 탐색] BOJ_경쟁적 전염 홍지우

백트래킹/지우/BOJ_2529_부등호.cpp
- String , 벡터
- 백트래킹
- 백트래킹으로 가능한 숫자 조합을 전부 탐색 → 최대 O(10! = 3628800)
- 하지만 부등호 조건과 방문 체크로 가지치기 수행 → 실제 탐색은 O(P(10, k+1))
- 총 시간복잡도는 O(P(10, k+1)) = O(10 x 9 x 8 ... (10 - k))
- [ `1 <` `2 <` `3 < `4 ] 이런 식으로 묶어서 dfs 돌려줬다.
- currNum  < **' _다음 숫자 **i**_ '**
- 처음엔 그냥 num*10 + i 이런 식으로 숫자 자체를 넘기려고 했는데 -> 그럼 021 이 21로 나온다 (일단 int형 안에도 안 들어감)
- ➡️ string 자체를 넘겨줬다.
- 또한, string 안에서도 사전순으로 대소 비교가 가능함을 이용해 min, max를 활용해 대소비교를 해줬다.
=> Solved: [백트래킹] BOJ_부등호 홍지우

그래프 탐색/나영/BOJ_18405_경쟁적 전염.java
- PriorityQueue
- 배열
- 그래프 탐색
- BFS
- 최대 n*n개의 칸을 탐색 : O(n^2)
- PQ에서 poll() : O(log Npq)
- PQ에 offer() : O(log Npq)
- Npq = 현재 PQ 크기, 최악의 경우 최대 n²
- 따라서 최종 시간복잡도 : **O(n^2 * log n)**
- PQ를 쓰지 않고 풀고 싶었지만,, 무조건 바이러스 정렬은 필수로 해야 하는 듯
- PQ에 정렬 조건을 넣고 바이러스를 하나씩 넣으며 시간 순 -> 바이러스 타입 순으로 오름차순 정렬한다
- 그리고 s초까지 bfs 돌려돌려
- 처음에 바이러스를 ArrayList로 받고, 정렬한 뒤 que에 넣어주면 굳이 PQ 안 써도 될 듯
=> Solved: [그래프 탐색] BOJ_경쟁적 전염 김나영

그래프 탐색/나영/BOJ_16928_뱀과 사다리 게임.java
- HashMap
- Queue
- 배열
- 그래프 탐색
- BFS
- 방문 가능한 칸의 개수 = 100
- 1~6까지 주사위를 돌리며 말을 이동 = 6
- 최종 시간복잡도 : **O(100 * 6) = O(600)**
- 문제의 핵심은 **뱀과 사다리를 얼마나 탈 수 있느냐** 이다
- 각 칸에는 뱀 하나, 사다리 하나를 놓을 수 있다 => 사다리를 타고 도착한 칸에 또 다른 사다리나 뱀이 있을 수 있다
- 이를 명시하고 현재 인덱스 + 주사위 수 = nr을 구한 뒤 nr 위치에 뱀/사다리가 있다면 while 문으로 다음 칸으로 넘기며 그 다음 칸에도 뱀과 사다리가 있는지 확인하며 없을 때까지 탐색한다
=> Solved: [그래프 탐색] BOJ_뱀과 사다리 게임 김나영

그래프 탐색/지우/BOJ_16928_뱀과 사다리 게임.cpp
- 큐, 벡터, map
- map.insert({key, value}); if(map.find(key) != map.end())
- 그래프 탐색
- 주사위 범위(1~6) 내에서 100칸까지 탐색하므로 BFS는 O(100)
- 각 칸에서 사다리/뱀 여부를 map에서 조회 → O(log N) (map 사용 시)
- 총 시간복잡도는 O(100 * log(N + M)) = O(600) 수준 (실질적으로 매우 빠름)
- 처음에 주사위 돌리는 걸 까먹고 visited를 안 썼다가 예외케이스 시간 돌아가는 거 보고 다시 추가함 헤헷
- PQ를 사용해서 가장 pos가 큰 것부터 인출하여 처리하려고 했으나 min(ans, cnt) 과정이 들어갈 수 밖에 없어 dfs 처럼 모두 돌게 된다. 
- 중요한 것은 cnt가 가장 작은 것이라  가장 최소의 cnt 에서 100을 발견할 수 있는 그냥 q를 쓰는게 맞았음
- 사다리, 뱀에 대한 vis 처리를 미리 해두면 나중에 정상적으로 오면서 해당 위치를 방문했을 땐 그냥 사다리 타지도 않았는데 이미 방문한 것으로 처리가 되어버려서 해당 부분 vis 되었는지 체크하는 것은 뺐다.
=> Solved: [그래프 탐색] BOJ_뱀과 사다리 게임 홍지우

그래프 탐색/나영/BOJ_9019_DSLR_1.java, 그래프 탐색/나영/BOJ_9019_DSLR_2.java
- Queue
- 배열
- 그래프 탐색
- BFS
- 두 코드 모두 que에 들어가는 노드 수가 동일하게 10,000까지 간다.
- 내부 연산은 O(1) 수준
- find() 메서드에서 최대 10,000 번까지 이동할 수 있음
- 최종 시간복잡도 : **O(10,000)**
- DSLR 구현이 오히려 더 어려웠던,,
- 처음에는 que에 String 배열을 넣고, DSLR 처리 시 String 값을 Integer로 바꾸거나 char의 위치를 replace 하는 등의 방식으로 구현하려고 했는데, 하다 보니 100% 터질 거 같아서 P 클래스로 바꿨다
- 클래스 P를 통해 이동할 다음 값, 선택한 연산자를 a, ans에 저장한 뒤 que에서 하나씩 꺼내면서 DSLR 연산을 통해 값을 바꿔주고, visited 처리한다.
- 2번째 방법은 역방향 탐색으로 que에는 Integer만 넣어 놓고, DSLR 연산 시 nr이 방문 처리되지 않았다면 prev[nr] 의 값에 n을 넣어 주고 charn[nr]에도 해당 연산자를 넣어 준다.
- 그리고 n == y가 되면 charn[n] 에서부터 역방향 탐색해 연산자를 StringBuilder path에 저장하고, prev[n] = -1, 즉 n 이 x까지 다시 돌아왔을 때 break 하고 path.reverse.toString()을 return해 sb에 append 한다.
=> Solved: [그래프 탐색] BOJ_DSLR 김나영

백트래킹/나영/BOJ_19949_영재의 시험.java
- 배열
- 백트래킹
- 5개의 숫자에서 중복 허용 10개의 수를 뽑음 => 5^10
- 3자리에 같은 수가 연속으로 나오는 경우를 제외하면 5^10 까지 가지는 않지만, 상수 비율
- 최종 시간복잡도 : **O(5^10)**
- 중복 허용 순열 추출하는 문제
- 이 때 3자리 연속된 수가 모두 같은 경우만 제외시켰다
=> Solved: [백트래킹] BOJ_영재의 시험 김나영

백트래킹/지우/BOJ_12908_텔레포트 3.cpp
- 벡터
- 백트래킹
- 최대 3쌍(6개)의 포탈을 사용할 수 있고, DFS로 포탈 사용 여부를 탐색 → O(6!)
- 각 DFS 호출마다 거리 계산은 O(1)이며, 중복 사용 방지를 위한 백트래킹 적용
- 총 시간복잡도는 O(720) 수준으로 매우 빠르게 동작
- 어제 푼 진우의 민초우유랑 비슷한 문제이다
- 이동거리를 abs(r-r1) + abs(c-c1)로 풀 수 있다면 대체로 이런 형태의 문제가 된다.
- distance라는 점을 유의해 Long long으로 처리하는 것도 중요 포인트! (나영이가 쏘옥~ 반례 알려줬다)
[Solved]
- 우선 현재까지 가장 작은 Distance는 `dist(시작, 도착)`
- dfs(현재 위치, 시간)
- 중간 중간 `현재 위치에서 목적지까지의 거리` + `지금까지의 시간`을 더했을 때 ans보다 작아지면 업데이트 해준다. 
- return 하면 안됨 사실 초기값도 얘가 갱신하지~ -> 뒤 코드 돌려서 텔레포트 이용하면 더 빠를 수도 있으니까!
- ans보다 큰 time들은 모두 가지치기 해준다.
- 텔레포드 6 정거장을 모두 돌면서 기존time + 포트까지의 거리 + 10초를 하고 dfs를 돌린다.
- 이때, 텔레포트 정류장 다녀온 곳은 2 곳 모두 vis 처리를 해줘야 한다.
=> Solved: [백트래킹] BOJ_텔레포트 3 홍지우

백트래킹/나영/BOJ_10597_순열장난.java
- ArrayList
- 배열
- 백트래킹
- 조합
- 입력 문자열 길이가 L일 때, 첫 시작점 start에서 다음 값까지 하나씩 추가해가며 50 이하/1 이상인지, 방문 처리되었는지 확인하여 순열을 탐색해 list에 넣는다.
- 1 2 3이 있으면 1 2 3, 1 23, 12 3 이런 식으로 탐색함
- 2자리까지만 탐색하므로 한 자리에서 최대 2번의 선택 가능 : 시간복잡도 = O(2^L)
- check() 메서드의 경우 최대 50까지밖에 안 가므로 상수 처리 가능
- 최악 시간복잡도 : **O(2^L)** 이지만 visited 처리와 1~50 조건으로 거기까지 가진 않음
- 그리고 list.add()와 remove의 경우 끝에서 더하고 삭제하므로 O(n)이 아닌 O(1)의 시간이 걸린다.
- 받은 문자열을 int 배열 arr로 바꾸고, dfs 재귀에서 arr에서 조건에 적합한 조합을 탐색한다.
- 이 때 arr의 이전 인덱스 값을 탐색하면 중복이 발생하므로 start를 재귀에서 넘겨 start ~ arr.length-1 까지 for문을 돌게 하고, 현재 위치의 바로 다음 위치의 값만 n으로 조합해 재귀를 돌려 탐색한다.
- 만약 start가 arr.length까지 왔다면, check() 메서드로 visited 배열이 1~list 길이까지 순서대로 true 체크가 되었는지 확인하고 가능하다면 출력 후 바로 끝낸다.
=> Solved: [백트래킹] BOJ_순열장난 김나영

백트래킹/지우/BOJ_10597_순열장난.cpp
- 벡터
- 백트래킹
- 문자열 길이 N에 대해 한 자리 또는 두 자리 숫자를 조합하므로 분기 최대 O(2^N)
- 각 숫자는 1~N 사이에서 중복 없이 선택되며 used 체크 → O(1)
- 총 시간복잡도는 O(2^N) (단, 백트래킹 및 조기 종료로 실제 탐색은 훨씬 적음)
- 1개 또는 2개 숫자 조합으로 dfs를 돌리고 _마지막에 연속된 숫자인지 확인 O(N)_ 하니까 시간초과
- 어떻게 저 O(N) 더 도는 걸 짜를까 너무너무너무 고민핑...
- 근데 생각해보니까 모은 수의 개수랑 가장 큰 수랑 똑같아야 하잖아..? 라는 생각이 듦
- 1 2 3 4 (이 순열의 가장 끝 수 4랑 모은 개수 4개랑 꼭 같아야 함)
- 헤헤헤 이거 했더니 통과~
=> Solved: [백트래킹] BOJ_순열장난 홍지우

백트래킹/나영/BOJ_1469_숌 사이 수열.java
- 배열
- 브루트 포스
- 백트래킹
- n개의 숫자에 대해 2번 선택해 2n 크기의 수열을 탐색해야 함 => nPn => O(n!)
- 하지만 동일한 숫자를 2개만 선택할 수 있고, 배치 조건도 있으므로 가지치기가 됨
- 최악의 경우 : **O(n!)**
- 처음에는 2n까지 모든 수를 dfs를 돌며 뽑으려고 했는데, 그럼 depth의 깊이가 너무 커져서 시간초과 발생
- 그래서 dfs 시 숫자를 하나 선택하면 해당 숫자를 알맞은 위치에 배치시킨 뒤 dfs를 돌렸다
- 이렇게 하면 불가능한 경우의 수도 자동으로 가지치기됨.
- 그리고 **Arrays.sort** 잊지 않기로 해요
- 이거 안 하면 사전 순 정렬 불가
=> Solved: [백트래킹] BOJ_숌 사이 수열 김나영

문자열/지우/BOJ_1316_그룹 단어 체커.cpp
- Set, String
- 문자열, 구현
1. 문자열 N개에 대해 각각 한 번씩 순회 → O(N)
2. 각 문자열 길이 L에 대해 문자 순회하며 set 연산 수행 → O(L × log 26)
3. 총 시간복잡도는 **O(N × L)** (L은 평균 문자열 길이, 최대 100 정도로 보통 상수 취급 가능)
- pre와의 비교를 통해 연속 여부를 판단한다.
- pre와 일치하지 않으면 우선 연속된 글자는 아니다.
- sets에 없던 단어는 그룹 단어의 조건을 헤치지 않는다. 고대~로 sets에 넣어준다.
- 근데 sets에 있던 단어가 연속되지도 않았으면서 등장~?? : 그룹 단어 놉!
=> Solved: [문자열] BOJ_그룹 단어 체커 홍지우

그래프 탐색/나영/BOJ_13913_숨바꼭질 4.java
- ArrayList
- 배열
- 그래프 탐색
-  BFS
- BFS : 모든 칸에 대하여 최대 1번씩만 접근 가능 : 100,001
- BFS 시 한 자리에 3개의 경로 이동 방법이 존재하지만 결국 한 칸에 한 경로만 사용 가능하므로 100,001 * 3이 아니라 100,001
- find() : 방문한 칸에 한하여 이전 경로를 탐색하므로 BFS와 선형
- 최종 시간복잡도 : **O(100,001) = O(10 ^ 5)**
- 어제 풀었던 숨바꼭질 오늘 또 풀었네
- 이번 문제는 경로 탐색은 그대로 이어가되, 도착한다면 지금까지 이동한 경로를 모두 출력하는 방식이었다.
- prev 배열을 만들어 r -> nr로 이동 시 prev[nr]에 이전 이동 값 r을 저장해 이전 경로를 저장했다.
- 그리고 k까지 다다른다면 find(k)를 통해 k ~ n까지 이동하며 prev에 저장된 경로를 탐색하여 list에 저장한다.
- 그리고 list의 뒤 - 앞 순서로 돌며 sb에 경로를 append 한다.
=> Solved: [그래프 탐색] BOJ_숨바꼭질 4 김나영

그래프 탐색/나영/BOJ_11559_Puyo Puyo.java
- Queue
- ArrayList
- 배열
- 그래프 탐색
- bfs
- BFS : 한 번 돌 때 모든 칸을 최대 한 번만 탐색 : 12 * 6
- reMap : 그래프 탐색 후 map에서 떨어져야 할 뿌요뿌요 위치 변경 : 12 * 6
- 라운드는 최악의 경우 18번까지만 반복됨
- BFS 한 번은 최대 72칸 탐색 → 한 라운드(전체 탐색)는 O(72 * 72)
- 연쇄가 일어날 때마다 최소 4개 이상이 터지므로, 최대 연쇄 횟수는 72 / 4 = 18.
- 최종 시간복잡도 : **O((12 * 6) ^ 2 * 18)**
- prev 배열을 통해 풀고 싶었는데 그냥 List 쓰는 게 깔끔할 것 같았다
- bfs로 map을 돌며 동일한 색상이 있는지 확인하고 좌표를 List에 저장
- 이후 List의 크기가 4 이상이라면 하나씩 꺼내서 제거한다
- 전부 제거 후 reMap을 통해 제거된 빈 공간 위에 있는 뿌요뿌요들을 내려줬다
- reMap을 하는 게 좀 힘들었다 헤헷
=> Solved: [그래프 탐색] BOJ_Puyo Puyo 김나영

구현/나영/BOJ_16927_배열 돌리기 2.java
- 배열
- 구현
- 최대 회전 수 : R % 전체 테두리 길이(len) 이므로 최대 O(2n + 2m - 4) = O(N + M)
- find 메서드 : 한 회전에 while문을 통해 모든 테두리의 원소를 한 번씩 이동 = O(LEN) = O(N + M)
- find 메서드가 도는 횟수는 테두리 개수 : Math.min(N, M) / 2
- 최종 시간복잡도 : **O(min(N, M) * (N + M) ^ 2)**
- 돌리는 것까진 됐는데 시간복잡도를 줄이는 방법이 고심이었다
- 가장 큰 문제는 R이 10^9까지 간다는 것이므로 입력받은 네모의 테두리 길이를 구한 뒤 **R % len = size**로 해당 회전에서 각 원소가 몇 번째까지 이동할 수 있는지 확인했다. (어차피 아무리 R이 커도 원소의 이동이 계속 반복되는 것이므로 R / 테두리의 나머지 값만 회전시키면 된다. 원소가 얼마나 이동하는지만 확인)
- 그리고 size 번 반복하며 해당 테두리의 모든 원소의 위치를 바꿔 준다.
=> Solved: [구현] BOJ_배열 돌리기 2 김나영

시뮬레이션/나영/BOJ_21922_학부 연구생 민상.java
- Queue
- 배열
- 시뮬레이션
- 구현
- vis[r][c][d] 배열 덕분에 같은 (r, c, d) 상태는 최대 한 번만 큐에 들어감
- 가능한 상태 개수는 n * m * 4 (4방향)
- BFS의 전체 시간복잡도는 **O(n*m*4) = O(n*m)**
- 헤헤 꼬아서 생각하다 리셋하고 다시 품
- vis 배열을 방향별로 저장해 방문 여부 체크
- counted 배열로 해당 칸을 이미 셌다면 ans에 ++ 하지 않도록 한다
=> Solved: [시뮬레이션] BOJ_학부 연구생 민상 김나영

투 포인터/나영/BOJ_11728_배열 합치기.java
- 배열
- 투포인터
- 두 배열 a, b를 각각 한 번씩만 순회
- while문에서 p1 또는 p2가 매번 증가 → 최대 n+m번 반복
- 남은 원소 복사도 각각 한 번씩만 수행
- 최종 시간복잡도: 𝑂(𝑛+𝑚)
- 투포인터로 안 푸는 게 더 나을듯,,
- 배열을 각각 a, b로 받은 뒤 포인터 p1, p2를 통해 a[p1]와 b[p2] 중 더 큰 값이 있다면 해당 값을 sb에 넣어주고 p1 또는 p2++한다
- 배열 한 쪽을 다 담지 못하는 경우도 있을 수 있으므로 if(p1==n) 을 통해 양쪽 배열의 값이 모두 담길 수 있도록 한다
=> Solved: [투포인터] BOJ_배열 합치기 김나영

백트래킹/나영/BOJ_6987_월드컵.java
- 배열
- 브루트포스
- 백트래킹
- 15경기(6팀 조합) 결과를 백트래킹(DFS) 으로 탐색
- 최악 시간복잡도: **O(3^15) ≈ 1.4천만**
- 하지만 입력 합이 30 초과 시 바로 종료
- 불가능한 가지는 바로 잘라내기(백트래킹)
- 가능한 해를 찾으면 즉시 리턴
➡ 실제 실행 시간은 평균적으로 훨씬 빠르며, BOJ 기준 1초 내 통과 가능
- 바보같이 승/무/패 합계 기준으로 풀라다가 예외 왕창 발견하고 후퇴
- 경기 조합이 총 15개이므로, 해당 조합을 미리 배열에 구한 뒤 그 조합을 이용하여 승/무/패 여부를 정한다
=> Solved: [백트래킹] BOJ_월드컵 김나영

시뮬레이션/지우/BOJ_20165_인내의 도미노 장인 호석.cpp
- 시뮬레이션
- 총 R번의 라운드가 진행되므로, 전체 시간 복잡도는 R × (한 라운드의 복잡도) 입니다.
- 한 번의 공격(bfs)은 최악의 경우 모든 도미노(N*M개)를 쓰러뜨리며, 각 도미노는 자신의 길이(L)만큼 연쇄 반응을 확인합니다.
- 따라서 총 시간 복잡도는 O(R * N * M * L) 이며, 10000 * 100 * 100 * 5는 약 5억이지만, 실제로는 모든 도미노가 최대 길이도 아니고 한번 쓰러지면 다시 확인하지 않으므로 충분히 통과합니다.
- 1-Based 문제를 0-based 문제로 풀려고 했으면 미리 종이에 1->0!!!! 이렇게 적어놓자.. 또 구현하닥 빼먹어서 디버깅 함..
- 풀이방법: 쓰러트릴 시작점, 방향을 q에 넣어주고 
- -> 만약 이미 쓰러진 경우가 아니라면 본인을 포함해 해당 길이만큼 쓰러트릴 수 있다. 연쇄적으로 쓰러트리면서 아직 안 쓰러트린 애들 cnt 해주며 진행된다.
=> Solved: [시뮬레이션] BOJ_인내의 도미노 장인 호석 홍지우

그래프 탐색/지우/BOJ_2151_거울 설치.cpp
- Deque, Vector
- 그래프 탐색
1. BFS는 각 방향(4개)마다 모든 좌표(N×N)에 대해 탐색 → 최대 O(4×N²)
2. 덱을 이용한 0-1 BFS로 거울 설치/비설치 상황을 빠르게 처리
3. 총 시간복잡도는 O(N²), N ≤ 50일 때 최대 약 10,000번 연산으로 충분히 통과
- 와.. dp[r][c][dir] 을 dp[r][c][d]로 적어서 디버깅을 을매나 한 건지... "제발 처음부터 잘하자 제발"
- 현재 위치 기준으로 #이나 . 에 와있으면 무조건 dir 방향으로만 가고 
- !에 와있으면 현재 각도 + 90도 회전한 방향 2로 갈 수 있게끔 설계했다.
- 덱을 사용해 최소 거울을 사용한 경우가 더 앞에 배치되도록 해줬다.
=> Solved: [그래프 탐색] BOJ_거울 설치 홍지우

문자열/지우/BOJ_17609_회문.cpp
- 문자열
1. 한 문자열에 대해 최악의 경우 `dfs`는 두 분기로 나뉘며 → 시간복잡도는 O(2^d), 여기서 d는 허용되는 삭제 횟수 (최대 2)
2. 따라서 **문자열 길이 N에 대해 O(N)**의 길이만큼 탐색하며, 분기 깊이가 최대 2라서 전체 탐색은 **상수 수준**의 재귀 호출만 발생
3. 전체 시간복잡도는 **O(T × N)** — T: 테스트케이스 수, N: 문자열 길이
- 회문 : 양 끝이 서로 같아야 한다. 
- 유사회문: 양 끝 중 하나의 포인터만 옮기면 그 후론 다 같아야 한다.
- 그 외 문자열: 옮기는 횟수가 2개 이상이다!
dfs(왼쪽, 오른쪽, 옮긴 횟수) 를 점점 영역을 좁히며 돌려서
포인터가 서로 마주한 지점에 가장 옮긴 횟수가 작은 걸 => ans
(가지치기: 옮긴 횟수가 2 이상이면 이미 탈락! out!)
=> Solved: [문자열] BOJ_회문 홍지우

그래프 탐색/지우/BOJ_17616_등수 찾기.cpp
- 그래프 탐색
1. 각 BFS 탐색은 한 번의 방문으로 노드들을 큐에 넣고 탐색 → O(N + M)
2. 입력으로 들어오는 간선 정보 M개에 대해 인접 리스트를 구성 → O(M)
3. 전체 시간복잡도는 **O(N + M)** (BFS 2번 호출 포함)
- 아이디어가 중요한 문제였다.
- 인접리스트 2개를 사용하여 **win_lose[이긴] = {진 리스트}** | **lose_win[진] = {이긴 리스트}** 이렇게 저장한다.
- X 기준으로 그거보다 이긴 사람들 수를 구하면 -> 최대로는 확실히 이긴 리스트 이후엔 바로 이겼다는 뜻
- X 기준으로 그거보다 진 사람들 수를 구하면 -> 최소 이거 보다는 높다는 뜻
=> Solved: [그래프 탐색] BOJ_등수 찾기 홍지우
